Repository bcgov/sbc-pay, pull requests merged in 2020-07, with the labels that each got.

#258 Code cleanup and add release drafter.
  .github/release-drafter.yml
  .github/workflows/bcol-api-dev.yml
  .github/workflows/bcol-api-test.yml
  .github/workflows/check-master.yml
  .github/workflows/draft-release.yml
  .github/workflows/main-pr-check.yml
  .github/workflows/pay-api-dev.yml
  .github/workflows/pay-api-test.yml
  .github/workflows/report-api-dev.yml
  .github/workflows/report-api-test.yml
  README.md
  bcol-api/jenkins/staging.groovy
  bcol-api/jenkins/test.groovy
  codecov.yaml
  jobs/update-stale-payment/openshift/cron-update-stale-payment.yaml
  openshift/dockerfile-jenkins-slave-python3-nodejs10
  openshift/templates/api-config.json
  pay-api/jenkins/staging.groovy
  pay-api/jenkins/test.groovy
  report-api/jenkins/test.groovy
  scripts/1pass.sh
  scripts/1pass_dc.sh
  scripts/1pass_secret.sh
  scripts/install_tools.sh
Labels: DoNotMerge

#261 Dev to Test merge
  .github/release-drafter.yml
  .github/workflows/bcol-api-check.yml
  .github/workflows/bcol-api-dev.yml
  .github/workflows/bcol-api-test.yml
  .github/workflows/check-master.yml
  .github/workflows/draft-release.yml
  .github/workflows/main-pr-check.yml
  .github/workflows/pay-api-dev.yml
  .github/workflows/pay-api-test.yml
  .github/workflows/report-api-dev.yml
  .github/workflows/report-api-test.yml
  README.md
  bcol-api/config.py
  bcol-api/jenkins/staging.groovy
  bcol-api/jenkins/test.groovy
  bcol-api/requirements.txt
  bcol-api/requirements/dev.txt
  bcol-api/requirements/prod.txt
  bcol-api/src/bcol_api/resources/bcol_payment.py
  bcol-api/src/bcol_api/schemas/schemas/payment_request.json
  bcol-api/src/bcol_api/services/bcol_payment.py
  bcol-api/src/bcol_api/services/bcol_soap.py
  bcol-api/src/bcol_api/utils/constants.py
  bcol-api/tests/unit/services/test_bcol_payment.py
  bcol-api/tests/utilities/base_test.py
  codecov.yaml
  jobs/update-stale-payment/openshift/cron-update-stale-payment.yaml
  jobs/update-stale-payment/requirements/prod.txt
  openshift/dockerfile-jenkins-slave-python3-nodejs10
  openshift/templates/api-config.json
  pay-api/config.py
  pay-api/jenkins/staging.groovy
  pay-api/jenkins/test.groovy
  pay-api/migrations/versions/cf9a60955b68_bcol_staff_payment.py
  pay-api/requirements.txt
  pay-api/src/pay_api/factory/payment_system_factory.py
  pay-api/src/pay_api/models/corp_type.py
  pay-api/src/pay_api/models/invoice.py
  pay-api/src/pay_api/schemas/schemas/account_info.json
  pay-api/src/pay_api/services/base_payment_system.py
  pay-api/src/pay_api/services/bcol_service.py
  pay-api/src/pay_api/services/fee_schedule.py
  pay-api/src/pay_api/services/internal_pay_service.py
  pay-api/src/pay_api/services/invoice.py
  pay-api/src/pay_api/services/paybc_service.py
  pay-api/src/pay_api/services/payment_service.py
  pay-api/src/pay_api/utils/enums.py
  pay-api/src/pay_api/utils/user_context.py
  pay-api/src/pay_api/utils/util.py
  pay-api/tests/unit/api/test_fee.py
  pay-api/tests/unit/api/test_payment.py
  pay-api/tests/unit/services/test_bcol_service.py
  pay-api/tests/unit/services/test_invoice.py
  pay-api/tests/utilities/base_test.py
  report-api/jenkins/test.groovy
  report-api/report-templates/payment_receipt.html
  scripts/1pass.sh
  scripts/1pass_dc.sh
  scripts/1pass_secret.sh
  scripts/install_tools.sh
Labels: enhancement

#262 Move pr label check to development branch.
  .github/workflows/draft-release.yml
  .github/workflows/main-pr-check.yml
  .github/workflows/pr-label-check.yml
  jobs/update-stale-payment/openshift/cron-update-stale-payment.yaml
Labels: devops

#264 Changes for supporting BCOL payments using service account.
  bcol-api/src/bcol_api/resources/bcol_payment.py
  bcol-api/src/bcol_api/services/bcol_payment.py
  bcol-api/src/bcol_api/utils/constants.py
  pay-api/config.py
  pay-api/migrations/versions/7ea7ba8fe991_alteration_filing.py
  pay-api/src/pay_api/factory/payment_system_factory.py
  pay-api/src/pay_api/models/bcol_payment_account.py
  pay-api/src/pay_api/services/base_payment_system.py
  pay-api/src/pay_api/services/bcol_service.py
  pay-api/src/pay_api/services/internal_pay_service.py
  pay-api/src/pay_api/services/paybc_service.py
  pay-api/src/pay_api/services/payment.py
  pay-api/src/pay_api/services/payment_account.py
  pay-api/src/pay_api/services/payment_service.py
  pay-api/src/pay_api/utils/enums.py
  pay-api/src/pay_api/utils/user_context.py
  pay-api/tests/conftest.py
  pay-api/tests/unit/api/test_payment.py
  pay-api/tests/unit/factory/test_payment_system_factory.py
  pay-api/tests/unit/services/test_payment_service.py
  pay-api/tests/unit/services/test_payment_system_service.py
Labels: enhancement

#266 dev to test
  .github/workflows/draft-release.yml
  .github/workflows/main-pr-check.yml
  .github/workflows/pr-label-check.yml
  bcol-api/src/bcol_api/resources/bcol_payment.py
  bcol-api/src/bcol_api/services/bcol_payment.py
  bcol-api/src/bcol_api/utils/constants.py
  jobs/update-stale-payment/openshift/cron-update-stale-payment.yaml
  pay-api/config.py
  pay-api/migrations/versions/7ea7ba8fe991_alteration_filing.py
  pay-api/src/pay_api/factory/payment_system_factory.py
  pay-api/src/pay_api/models/bcol_payment_account.py
  pay-api/src/pay_api/services/base_payment_system.py
  pay-api/src/pay_api/services/bcol_service.py
  pay-api/src/pay_api/services/internal_pay_service.py
  pay-api/src/pay_api/services/paybc_service.py
  pay-api/src/pay_api/services/payment.py
  pay-api/src/pay_api/services/payment_account.py
  pay-api/src/pay_api/services/payment_service.py
  pay-api/src/pay_api/utils/enums.py
  pay-api/src/pay_api/utils/user_context.py
  pay-api/tests/conftest.py
  pay-api/tests/unit/api/test_payment.py
  pay-api/tests/unit/factory/test_payment_system_factory.py
  pay-api/tests/unit/services/test_payment_service.py
  pay-api/tests/unit/services/test_payment_system_service.py
Labels: enhancement

#263 Changes for distribution and fee schedules
  pay-api/migrations/versions/a11be9fe1a6a_distribution_code.py
  pay-api/migrations/versions/e385e278cf3e_merge_heads.py
  pay-api/src/pay_api/models/__init__.py
  pay-api/src/pay_api/models/corp_type.py
  pay-api/src/pay_api/models/distribution_code.py
  pay-api/src/pay_api/models/fee_schedule.py
  pay-api/src/pay_api/models/payment_line_item.py
  pay-api/src/pay_api/resources/__init__.py
  pay-api/src/pay_api/resources/distributions.py
  pay-api/src/pay_api/resources/fee_schedule.py
  pay-api/src/pay_api/schemas/schemas/distribution_code.json
  pay-api/src/pay_api/services/__init__.py
  pay-api/src/pay_api/services/distribution_code.py
  pay-api/src/pay_api/services/fee_schedule.py
  pay-api/src/pay_api/services/invoice.py
  pay-api/src/pay_api/services/paybc_service.py
  pay-api/src/pay_api/services/payment_line_item.py
  pay-api/src/pay_api/utils/enums.py
  pay-api/tests/unit/api/test_distributions.py
  pay-api/tests/unit/api/test_fee.py
  pay-api/tests/unit/services/test_distribution_code.py
  pay-api/tests/unit/services/test_fee_schedule.py
  pay-api/tests/unit/services/test_payment.py
  pay-api/tests/unit/services/test_payment_service.py
  pay-api/tests/utilities/base_test.py
Labels: DoNotMerge, enhancement
