Repository bcgov/sbc-pay, pull requests merged in 2020-10, with the labels that each got.

#354 Error Message Doesn't Specify BCOL Account has Insufficient Funds#4871
  pay-api/migrations/versions/872760122cc9_create_insufficient_fund_bcol_error.py
  pay-api/src/pay_api/utils/errors.py
  pay-api/tests/unit/utils/test_error.py
Labels: bug

#358 Fix for wrong start date for frequency change in statements
  pay-api/src/pay_api/services/statement_settings.py
  pay-api/tests/conftest.py
  pay-api/tests/unit/api/test_statement_settings.py
Labels: bug

#360 Dev to Test
  pay-api/migrations/versions/872760122cc9_create_insufficient_fund_bcol_error.py
  pay-api/requirements.txt
  pay-api/src/pay_api/factory/payment_system_factory.py
  pay-api/src/pay_api/resources/account.py
  pay-api/src/pay_api/services/__init__.py
  pay-api/src/pay_api/services/auth.py
  pay-api/src/pay_api/services/base_payment_system.py
  pay-api/src/pay_api/services/bcol_service.py
  pay-api/src/pay_api/services/cfs_service.py
  pay-api/src/pay_api/services/direct_pay_service.py
  pay-api/src/pay_api/services/internal_pay_service.py
  pay-api/src/pay_api/services/online_banking_service.py
  pay-api/src/pay_api/services/paybc_service.py
  pay-api/src/pay_api/services/payment.py
  pay-api/src/pay_api/services/payment_account.py
  pay-api/src/pay_api/services/payment_service.py
  pay-api/src/pay_api/services/payment_transaction.py
  pay-api/src/pay_api/services/statement_settings.py
  pay-api/src/pay_api/utils/enums.py
  pay-api/src/pay_api/utils/errors.py
  pay-api/tests/conftest.py
  pay-api/tests/unit/api/test_account.py
  pay-api/tests/unit/api/test_payment.py
  pay-api/tests/unit/api/test_statement_settings.py
  pay-api/tests/unit/services/test_bcol_service.py
  pay-api/tests/unit/services/test_payment_service.py
  pay-api/tests/unit/services/test_payment_system_service.py
  pay-api/tests/unit/utils/test_error.py
  pay-api/tests/utilities/base_test.py
Labels: skip-changelog

#361 Fixing issues with failed migration
  pay-api/migrations/versions/8652bf9c03ff_payment_to_invoice.py
Labels: skip-changelog

#363 added a basic spec for /accounts endpoint
  docs/docs/api_contract/pay-api-1.0.0.yaml
Labels: skip-changelog

#364 Adding invoices endpoint to unblock names team.
  pay-api/src/pay_api/resources/__init__.py
  pay-api/src/pay_api/resources/invoice.py
  pay-api/tests/unit/api/test_invoice.py
Labels: skip-changelog

#365 Updating the GHA to use jwt application from relationship vault
  .github/workflows/bcol-api-cd.yml
  .github/workflows/pay-api-cd.yml
  .github/workflows/payment-jobs-cd.yml
  .github/workflows/report-api-cd.yml
Labels: skip-changelog

#362 update-stale-payment converted to crond
  jobs/payment-jobs/cron/crontab
  jobs/payment-jobs/invoke_jobs.py
  jobs/payment-jobs/run_stale_payments.sh
  jobs/payment-jobs/tasks/stale_payment_task.py
Labels: skip-changelog

#366 Fixing the typo
  jobs/payment-jobs/tasks/stale_payment_task.py
Labels: skip-changelog

#367 Fixing requirements
  queue_services/events-listener/requirements.txt
Labels: skip-changelog

#369 Fixing issue with migration where it skips DELETE_ACCEPTED and GL_UPDATED
  pay-api/migrations/versions/8652bf9c03ff_payment_to_invoice.py
Labels: skip-changelog

#371 added the missing configs
  jobs/payment-jobs/config.py
Labels: skip-changelog

#370 Changes for create CFS Account job
  jobs/payment-jobs/config.py
  jobs/payment-jobs/invoke_jobs.py
  jobs/payment-jobs/run_create_cfs_accounts.sh
  jobs/payment-jobs/run_create_cfs_invoices.sh
  jobs/payment-jobs/setup.cfg
  jobs/payment-jobs/tasks/__init__.py
  jobs/payment-jobs/tasks/cfs_create_account_task.py
  jobs/payment-jobs/tasks/cfs_create_invoice.py
  jobs/payment-jobs/tasks/distribution_task.py
  jobs/payment-jobs/tasks/stale_payment_task.py
  jobs/payment-jobs/tasks/statement_notification_task.py
  jobs/payment-jobs/tasks/statement_task.py
  jobs/payment-jobs/tests/__init__.py
  jobs/payment-jobs/tests/jobs/__init__.py
  jobs/payment-jobs/tests/jobs/conftest.py
  jobs/payment-jobs/tests/jobs/factory.py
  jobs/payment-jobs/tests/jobs/test_generate_statements.py
  pay-api/migrations/versions/70af1f70f6bf_cfs_account_status.py
  pay-api/src/pay_api/models/__init__.py
  pay-api/src/pay_api/models/cfs_account.py
  pay-api/src/pay_api/models/cfs_account_status_code.py
  pay-api/src/pay_api/utils/enums.py
Labels: enhancement

#372 Changes for creating customer profile in CFS for PAD accounts
  docs/docs/PayBC Mocking/paybc-1.0.0.yaml
  pay-api/migrations/versions/320f9f89eb68_.py
  pay-api/src/pay_api/config.py
  pay-api/src/pay_api/factory/payment_system_factory.py
  pay-api/src/pay_api/models/cfs_account.py
  pay-api/src/pay_api/models/payment_account.py
  pay-api/src/pay_api/services/cfs_service.py
  pay-api/src/pay_api/services/online_banking_service.py
  pay-api/src/pay_api/services/pad_service.py
  pay-api/src/pay_api/services/payment_account.py
  pay-api/src/pay_api/utils/constants.py
  pay-api/src/pay_api/utils/enums.py
  pay-api/tests/docker/docker-compose.yml
  pay-api/tests/unit/services/test_payment_account.py
  pay-api/tests/utilities/base_test.py
Labels: enhancement

#373 Fixing error with jobs and pytest
  jobs/payment-jobs/LICENSE
  jobs/payment-jobs/requirements/dev.txt
  jobs/payment-jobs/setup.py
  jobs/payment-jobs/tasks/cfs_create_account_task.py
  jobs/payment-jobs/tasks/cfs_create_invoice.py
  jobs/payment-jobs/tasks/statement_task.py
  jobs/payment-jobs/tests/jobs/conftest.py
  jobs/payment-jobs/tests/jobs/factory.py
  jobs/payment-jobs/tests/jobs/test_cfs_create_account_task.py
  jobs/payment-jobs/tests/jobs/test_cfs_create_invoice_task.py
  jobs/payment-jobs/tests/jobs/test_distribution_task.py
  jobs/payment-jobs/tests/jobs/test_generate_statements.py
  jobs/payment-jobs/tests/jobs/test_statement_notification_task.py
  pay-api/src/pay_api/services/payment_account.py
Labels: skip-changelog

#377 Fixing issue with stale payment not picking correct txn number
  jobs/payment-jobs/tasks/stale_payment_task.py
Labels: bug

#378 Dev to Test
  jobs/payment-jobs/tasks/stale_payment_task.py
Labels: skip-changelog

#376 Handling Online Banking and PAD account creation when CFS is down
  pay-api/src/pay_api/config.py
  pay-api/src/pay_api/models/cfs_account.py
  pay-api/src/pay_api/resources/account.py
  pay-api/src/pay_api/services/base_payment_system.py
  pay-api/src/pay_api/services/bcol_service.py
  pay-api/src/pay_api/services/cfs_service.py
  pay-api/src/pay_api/services/direct_pay_service.py
  pay-api/src/pay_api/services/internal_pay_service.py
  pay-api/src/pay_api/services/online_banking_service.py
  pay-api/src/pay_api/services/pad_service.py
  pay-api/src/pay_api/services/paybc_service.py
  pay-api/src/pay_api/services/payment_account.py
  pay-api/tests/unit/api/test_account.py
  pay-api/tests/unit/services/test_pad_service.py
  pay-api/tests/unit/services/test_payment_system_service.py
  pay-api/tests/utilities/base_test.py
Labels: enhancement

#374 Bank validation service added
  docs/docs/PayBC Mocking/paybc-1.0.0.yaml
  pay-api/requirements.txt
  pay-api/src/pay_api/resources/__init__.py
  pay-api/src/pay_api/resources/bank_accounts.py
  pay-api/src/pay_api/schemas/schemas/bank_accounts.json
  pay-api/src/pay_api/services/cfs_service.py
  pay-api/src/pay_api/utils/errors.py
  pay-api/tests/docker/docker-compose.yml
  pay-api/tests/unit/api/test_bank_accounts.py
  pay-api/tests/unit/api/test_payment.py
  pay-api/tests/unit/services/test_cfs_service.py
Labels: enhancement

#344 Updating pay-api spec with draft changes for API gateway publishing
  docs/docs/api_contract/pay-api-1.0.0.yaml
  pay-api/tests/docker/nginx.conf
Labels: documentation

#379 Added the missing field in payment_account schema
  pay-api/src/pay_api/models/payment_account.py
Labels: skip-changelog

#380 added missing tests for bank endpoint
  docs/docs/PayBC Mocking/paybc-1.0.0.yaml
  pay-api/tests/docker/docker-compose.yml
  pay-api/tests/docker/nginx.conf
  pay-api/tests/unit/api/test_bank_accounts.py
Labels: skip-changelog

#381 Dev to Test
  docs/docs/PayBC Mocking/paybc-1.0.0.yaml
  docs/docs/api_contract/pay-api-1.0.0.yaml
  pay-api/requirements.txt
  pay-api/src/pay_api/config.py
  pay-api/src/pay_api/models/cfs_account.py
  pay-api/src/pay_api/models/payment_account.py
  pay-api/src/pay_api/resources/__init__.py
  pay-api/src/pay_api/resources/account.py
  pay-api/src/pay_api/resources/bank_accounts.py
  pay-api/src/pay_api/schemas/schemas/bank_accounts.json
  pay-api/src/pay_api/services/base_payment_system.py
  pay-api/src/pay_api/services/bcol_service.py
  pay-api/src/pay_api/services/cfs_service.py
  pay-api/src/pay_api/services/direct_pay_service.py
  pay-api/src/pay_api/services/internal_pay_service.py
  pay-api/src/pay_api/services/online_banking_service.py
  pay-api/src/pay_api/services/pad_service.py
  pay-api/src/pay_api/services/paybc_service.py
  pay-api/src/pay_api/services/payment_account.py
  pay-api/src/pay_api/utils/errors.py
  pay-api/tests/docker/docker-compose.yml
  pay-api/tests/docker/nginx.conf
  pay-api/tests/unit/api/test_account.py
  pay-api/tests/unit/api/test_bank_accounts.py
  pay-api/tests/unit/api/test_payment.py
  pay-api/tests/unit/services/test_cfs_service.py
  pay-api/tests/unit/services/test_pad_service.py
  pay-api/tests/unit/services/test_payment_system_service.py
  pay-api/tests/utilities/base_test.py
Labels: skip-changelog

#384 Bank validation error handled
  docs/docs/PayBC Mocking/paybc-1.0.0.yaml
  pay-api/src/pay_api/services/cfs_service.py
  pay-api/tests/docker/docker-compose.yml
  pay-api/tests/unit/services/test_cfs_service.py
Labels: skip-changelog

#385 Handling default payments to DIRECT_PAY
  pay-api/src/pay_api/services/payment_account.py
  pay-api/src/pay_api/services/payment_service.py
  pay-api/tests/unit/api/test_payment.py
Labels: bug

#382 Creating CFS accounts offline
  .github/workflows/payment-jobs-cd.yml
  .github/workflows/payment-jobs-ci.yml
  jobs/payment-jobs/config.py
  jobs/payment-jobs/requirements/dev.txt
  jobs/payment-jobs/requirements/prod.txt
  jobs/payment-jobs/tasks/cfs_create_account_task.py
  jobs/payment-jobs/tests/docker/docker-compose.yml
  jobs/payment-jobs/tests/docker/nginx.conf
  jobs/payment-jobs/tests/docker/run.sh
  jobs/payment-jobs/tests/docker/setup/demo-realm.json
  jobs/payment-jobs/tests/jobs/conftest.py
  jobs/payment-jobs/tests/jobs/factory.py
  jobs/payment-jobs/tests/jobs/test_cfs_create_account_task.py
  pay-api/src/pay_api/services/cfs_service.py
  pay-api/src/pay_api/services/online_banking_service.py
  pay-api/src/pay_api/services/pad_service.py
  pay-api/src/pay_api/services/queue_publisher.py
  pay-api/tests/unit/api/test_account.py
  pay-api/tests/unit/services/test_payment_account.py
Labels: enhancement

#387 Updating pay dependency to bcgov repo
  jobs/payment-jobs/requirements/prod.txt
Labels: skip-changelog
