Repository bcgov/sbc-pay, pull requests merged in 2020-12, with the labels that each got.

#440 Fixing issue with amount not matching on new payment for NSF
  pay-api/src/pay_api/models/invoice.py
  pay-api/src/pay_api/models/payment.py
  pay-api/src/pay_api/services/payment.py
Labels: skip-changelog

#441 Fixing refund to accept None request
  pay-api/src/pay_api/resources/refund.py
Labels: skip-changelog

#445 Fixing creditbalance URL
  docs/docs/PayBC Mocking/paybc-1.0.0.yaml
  pay-api/src/pay_api/services/cfs_service.py
  pay-api/src/pay_api/services/paybc_service.py
  pay-api/src/pay_api/services/payment.py
  pay-api/tests/docker/docker-compose.yml
Labels: bug

#442 Releasing records for PAD on invoice creation
  pay-api/src/pay_api/services/pad_service.py
  pay-api/src/pay_api/services/payment_transaction.py
  pay-api/tests/unit/services/test_payment_service.py
  pay-api/tests/utilities/base_test.py
Labels: enhancement

#444 Hold creating invoices if CFS Account is FROZEN
  jobs/payment-jobs/tasks/cfs_create_invoice_task.py
  jobs/payment-jobs/tests/docker/docker-compose.yml
  jobs/payment-jobs/tests/jobs/test_cfs_create_invoice_task.py
  pay-api/tests/docker/docker-compose.yml
  queue_services/payment-reconciliations/tests/docker-compose.yml
Labels: skip-changelog

#446 Dev to Test
  docs/docs/PayBC Mocking/paybc-1.0.0.yaml
  jobs/payment-jobs/requirements/prod.txt
  jobs/payment-jobs/tasks/cfs_create_invoice_task.py
  jobs/payment-jobs/tests/docker/docker-compose.yml
  jobs/payment-jobs/tests/jobs/test_cfs_create_invoice_task.py
  pay-api/src/pay_api/services/cfs_service.py
  pay-api/src/pay_api/services/pad_service.py
  pay-api/src/pay_api/services/paybc_service.py
  pay-api/src/pay_api/services/payment.py
  pay-api/src/pay_api/services/payment_transaction.py
  pay-api/tests/docker/docker-compose.yml
  pay-api/tests/unit/services/test_payment_service.py
  pay-api/tests/utilities/base_test.py
  queue_services/payment-reconciliations/tests/docker-compose.yml
Labels: skip-changelog

#448 Adding Auth and Pay flow
  docs/docs/architecture/Authentication.gliffy
  docs/docs/architecture/Authentication.png
  docs/docs/architecture/Pay.gliffy
  docs/docs/architecture/Pay.png
Labels: skip-changelog

#449 Adding Auth and Pay flow
  docs/docs/architecture/Pay.png
Labels: skip-changelog

#450 Adding Auth and Pay flow
  docs/docs/architecture/Authentication Flow.png
  docs/docs/architecture/Pay Flow.png
Labels: skip-changelog

#447 Patch endpoint added for changing the payment method
  pay-api/src/pay_api/resources/invoice.py
  pay-api/src/pay_api/services/payment_service.py
  pay-api/tests/unit/services/test_payment_service.py
Labels: enhancement

#452 fixed misc error and added tests
  pay-api/src/pay_api/resources/invoice.py
  pay-api/tests/unit/api/test_payment_request.py
Labels: enhancement

#451 Adding service classes for EFT and Wire transfer.
  pay-api/src/pay_api/factory/payment_system_factory.py
  pay-api/src/pay_api/services/deposit_service.py
  pay-api/src/pay_api/services/eft_service.py
  pay-api/src/pay_api/services/payment_transaction.py
  pay-api/src/pay_api/services/wire_service.py
  pay-api/tests/unit/factory/test_payment_system_factory.py
  pay-api/tests/unit/services/test_eft_service.py
  pay-api/tests/unit/services/test_payment_service.py
  pay-api/tests/unit/services/test_wire_service.py
Labels: enhancement

#454 Fixed invoice ref creation on direct pay
  pay-api/src/pay_api/services/payment_service.py
  pay-api/tests/unit/api/test_payment_request.py
Labels: skip-changelog

#455 Dev to Test
  docs/docs/architecture/Authentication Flow.png
  docs/docs/architecture/Authentication.gliffy
  docs/docs/architecture/Pay Flow.png
  docs/docs/architecture/Pay.gliffy
  pay-api/src/pay_api/factory/payment_system_factory.py
  pay-api/src/pay_api/resources/invoice.py
  pay-api/src/pay_api/services/deposit_service.py
  pay-api/src/pay_api/services/eft_service.py
  pay-api/src/pay_api/services/payment_service.py
  pay-api/src/pay_api/services/payment_transaction.py
  pay-api/src/pay_api/services/wire_service.py
  pay-api/tests/unit/api/test_payment_request.py
  pay-api/tests/unit/factory/test_payment_system_factory.py
  pay-api/tests/unit/services/test_eft_service.py
  pay-api/tests/unit/services/test_payment_service.py
  pay-api/tests/unit/services/test_wire_service.py
Labels: skip-changelog

#453 Create EFT, WIRE invoice from job
  jobs/payment-jobs/tasks/cfs_create_invoice_task.py
  jobs/payment-jobs/tests/jobs/factory.py
  jobs/payment-jobs/tests/jobs/test_cfs_create_invoice_task.py
  pay-api/src/pay_api/services/refund.py
  pay-api/src/pay_api/services/wire_service.py
Labels: enhancement

#458 Updating PR template as CI does the checklist tasks
  .github/PULL_REQUEST_TEMPLATE.md
Labels: skip-changelog

#457 Changes for creating EFT/WIRE receipts
  pay-api/migrations/versions/0449261c3fa7_.py
  pay-api/src/pay_api/config.py
  pay-api/src/pay_api/models/payment.py
  pay-api/src/pay_api/resources/payment.py
  pay-api/src/pay_api/schemas/schemas/payment.json
  pay-api/src/pay_api/services/cfs_service.py
  pay-api/src/pay_api/services/payment.py
  pay-api/src/pay_api/utils/constants.py
  pay-api/src/pay_api/utils/enums.py
  pay-api/src/pay_api/utils/util.py
  pay-api/tests/unit/api/test_payment.py
  pay-api/tests/utilities/base_test.py
Labels: enhancement

#460 Fixing receipt URL
  docs/docs/PayBC Mocking/paybc-1.0.0.yaml
  pay-api/src/pay_api/services/cfs_service.py
  pay-api/tests/docker/docker-compose.yml
Labels: skip-changelog

#461 Fixing payment account id in payments table.
  pay-api/migrations/versions/331c2cdb0b94_fix_payment_account_id_in_payment_table.py
  pay-api/src/pay_api/services/payment_transaction.py
  pay-api/tests/docker/docker-compose.yml
  queue_services/payment-reconciliations/src/reconciliations/worker.py
Labels: bug

#456 TOS Flags added
  pay-api/src/pay_api/schemas/schemas/account_info.json
  pay-api/src/pay_api/services/payment_account.py
Labels: skip-changelog

#462 Fix for OB paying with CC invoiced flow
  pay-api/src/pay_api/services/payment_transaction.py
Labels: skip-changelog

#470 Role based masking added
  jobs/payment-jobs/config.py
  jobs/payment-jobs/requirements/prod.txt
  jobs/payment-jobs/tasks/cfs_create_account_task.py
  pay-api/src/pay_api/config.py
  pay-api/src/pay_api/services/auth.py
  pay-api/src/pay_api/services/payment_account.py
  pay-api/src/pay_api/utils/user_context.py
  pay-api/src/pay_api/utils/util.py
  pay-api/tests/docker/docker-compose.yml
  pay-api/tests/unit/api/test_account.py
Labels: enhancement

#471 fixed the wrong permissions
  pay-api/src/pay_api/utils/user_context.py
Labels: skip-changelog

#472 updating the wrong branch name
  pay-api/tests/docker/docker-compose.yml
Labels: skip-changelog

#474 Payment settlement
  jobs/payment-jobs/tasks/cfs_create_invoice_task.py
  jobs/payment-jobs/tests/jobs/test_cfs_create_invoice_task.py
  pay-api/src/pay_api/models/payment.py
  pay-api/src/pay_api/services/payment.py
  pay-api/tests/unit/models/test_payment.py
  pay-api/tests/unit/services/test_payment.py
  pay-api/tests/utilities/base_test.py
  queue_services/payment-reconciliations/requirements.txt
  queue_services/payment-reconciliations/requirements/repo-libraries.txt
  queue_services/payment-reconciliations/src/reconciliations/enums.py
  queue_services/payment-reconciliations/src/reconciliations/worker.py
  queue_services/payment-reconciliations/tests/conftest.py
  queue_services/payment-reconciliations/tests/integration/test_payment_reconciliations.py
Labels: enhancement

#473 added the pad tos accepted user id in event reponse , masking corrected
  jobs/payment-jobs/tasks/cfs_create_account_task.py
  pay-api/src/pay_api/services/payment_account.py
Labels: enhancement

#477 Dev to Test
  jobs/payment-jobs/tasks/cfs_create_account_task.py
  pay-api/src/pay_api/services/payment_account.py
Labels: skip-changelog

#478 Handling PAD Reversals
  queue_services/payment-reconciliations/src/reconciliations/enums.py
  queue_services/payment-reconciliations/src/reconciliations/worker.py
  queue_services/payment-reconciliations/tests/integration/factory.py
  queue_services/payment-reconciliations/tests/integration/test_payment_reconciliations.py
Labels: enhancement

#481 Routing namex payments to different subject
  pay-api/src/pay_api/config.py
  pay-api/src/pay_api/services/pad_service.py
  pay-api/src/pay_api/services/payment_transaction.py
  pay-api/src/pay_api/services/queue_publisher.py
  pay-api/src/pay_api/utils/enums.py
  pay-api/src/pay_api/utils/util.py
  pay-api/tests/unit/services/test_queue_publisher.py
  queue_services/payment-reconciliations/requirements.txt
  queue_services/payment-reconciliations/requirements/repo-libraries.txt
  queue_services/payment-reconciliations/src/reconciliations/config.py
  queue_services/payment-reconciliations/src/reconciliations/worker.py
Labels: enhancement, skip-changelog

#483 Dev to Test
  queue_services/payment-reconciliations/src/reconciliations/enums.py
  queue_services/payment-reconciliations/src/reconciliations/worker.py
  queue_services/payment-reconciliations/tests/integration/factory.py
  queue_services/payment-reconciliations/tests/integration/test_payment_reconciliations.py
Labels: skip-changelog

#484 Master to Dev
  pay-api/src/pay_api/config.py
  pay-api/src/pay_api/services/pad_service.py
  pay-api/src/pay_api/services/payment_transaction.py
  pay-api/src/pay_api/services/queue_publisher.py
  pay-api/src/pay_api/utils/enums.py
  pay-api/src/pay_api/utils/util.py
  pay-api/tests/unit/services/test_queue_publisher.py
  queue_services/payment-reconciliations/requirements.txt
  queue_services/payment-reconciliations/requirements/repo-libraries.txt
  queue_services/payment-reconciliations/src/reconciliations/config.py
  queue_services/payment-reconciliations/src/reconciliations/worker.py
Labels: skip-changelog

#489 Changes for capturing Credits and syncing with CFS
  pay-api/migrations/versions/15682073c535_account_credits.py
  pay-api/src/pay_api/models/__init__.py
  pay-api/src/pay_api/models/credit.py
  pay-api/src/pay_api/models/payment_account.py
  pay-api/src/pay_api/services/cfs_service.py
  queue_services/payment-reconciliations/requirements.txt
  queue_services/payment-reconciliations/src/reconciliations/worker.py
  queue_services/payment-reconciliations/tests/docker-compose.yml
  queue_services/payment-reconciliations/tests/integration/test_payment_reconciliations.py
Labels: enhancement

#487 Return bank details and a new flag for pad activation pending accounts
  pay-api/src/pay_api/services/payment_account.py
  pay-api/tests/unit/api/test_account.py
Labels: enhancement

#491 Dev to Test
  jobs/payment-jobs/requirements.txt
  jobs/payment-jobs/requirements/prod.txt
  pay-api/migrations/versions/15682073c535_account_credits.py
  pay-api/src/pay_api/models/__init__.py
  pay-api/src/pay_api/models/credit.py
  pay-api/src/pay_api/models/payment_account.py
  pay-api/src/pay_api/services/cfs_service.py
  pay-api/src/pay_api/services/payment_account.py
  pay-api/tests/unit/api/test_account.py
  queue_services/payment-reconciliations/requirements.txt
  queue_services/payment-reconciliations/requirements/repo-libraries.txt
  queue_services/payment-reconciliations/src/reconciliations/worker.py
  queue_services/payment-reconciliations/tests/docker-compose.yml
  queue_services/payment-reconciliations/tests/integration/test_payment_reconciliations.py
Labels: skip-changelog

#490 Creating credit memos for refunds
  pay-api/src/pay_api/resources/refund.py
  pay-api/src/pay_api/services/cfs_service.py
  pay-api/src/pay_api/services/refund.py
  pay-api/src/pay_api/utils/constants.py
  queue_services/payment-reconciliations/src/reconciliations/worker.py
Labels: enhancement

#492 Dev to Test
  pay-api/src/pay_api/resources/refund.py
  pay-api/src/pay_api/services/cfs_service.py
  pay-api/src/pay_api/services/refund.py
  pay-api/src/pay_api/utils/constants.py
  queue_services/payment-reconciliations/src/reconciliations/worker.py
Labels: skip-changelog

#493 deactivte cfs account when goes to bcol
  pay-api/src/pay_api/services/payment_account.py
  pay-api/tests/unit/api/test_account.py
Labels: enhancement

#494 Fix duplicate row
  pay-api/src/pay_api/services/cfs_service.py
  pay-api/src/pay_api/utils/constants.py
  queue_services/payment-reconciliations/requirements.txt
  queue_services/payment-reconciliations/requirements/repo-libraries.txt
  queue_services/payment-reconciliations/src/reconciliations/worker.py
Labels: skip-changelog

#495 Dev to test
  pay-api/src/pay_api/services/cfs_service.py
  pay-api/src/pay_api/services/payment_account.py
  pay-api/src/pay_api/utils/constants.py
  pay-api/tests/unit/api/test_account.py
  queue_services/payment-reconciliations/requirements.txt
  queue_services/payment-reconciliations/requirements/repo-libraries.txt
  queue_services/payment-reconciliations/src/reconciliations/worker.py
Labels: skip-changelog

#496 Changes for handling BC Online Drawdown balance in CFS
  pay-api/src/pay_api/resources/payment.py
  pay-api/src/pay_api/services/cfs_service.py
  pay-api/src/pay_api/services/payment.py
  pay-api/src/pay_api/utils/constants.py
Labels: skip-changelog

#497 UI needs PAD accepted details.
  pay-api/src/pay_api/models/payment_account.py
Labels: skip-changelog

#498 Adding DRAWDOWN to enum
  pay-api/src/pay_api/schemas/schemas/payment.json
Labels: skip-changelog

#499 Dev to Test
  pay-api/src/pay_api/models/payment_account.py
  pay-api/src/pay_api/resources/payment.py
  pay-api/src/pay_api/schemas/schemas/payment.json
  pay-api/src/pay_api/services/cfs_service.py
  pay-api/src/pay_api/services/payment.py
  pay-api/src/pay_api/utils/constants.py
Labels: skip-changelog

#500 added more events
  jobs/payment-jobs/tasks/activate_pad_account_task.py
  jobs/payment-jobs/tasks/cfs_create_invoice_task.py
  jobs/payment-jobs/tests/jobs/factory.py
  jobs/payment-jobs/tests/jobs/test_generate_statements.py
  jobs/payment-jobs/utils/mailer.py
Labels: enhancement

#486 Fix for adding corp type to support names authorised requests
  pay-api/src/pay_api/services/auth.py
  pay-api/src/pay_api/services/oauth_service.py
  pay-api/tests/unit/services/test_direct_pay_service.py
Labels: enhancement

#501 Fixing misc. UAT issues
  jobs/payment-jobs/tasks/cfs_create_invoice_task.py
Labels: skip-changelog

#502 Dev to Test
  jobs/payment-jobs/tasks/activate_pad_account_task.py
  jobs/payment-jobs/tasks/cfs_create_invoice_task.py
  jobs/payment-jobs/tests/jobs/factory.py
  jobs/payment-jobs/tests/jobs/test_generate_statements.py
  jobs/payment-jobs/utils/mailer.py
  pay-api/src/pay_api/services/auth.py
  pay-api/src/pay_api/services/oauth_service.py
  pay-api/tests/unit/services/test_direct_pay_service.py
Labels: skip-changelog

#503 Adding missing config details for mailer
  jobs/payment-jobs/config.py
Labels: skip-changelog

#504 Adding missing config details for mailer (#503)
  jobs/payment-jobs/config.py
Labels: skip-changelog

#505 Handling DWRP, and partial paid NSF payments
  pay-api/src/pay_api/models/payment.py
  pay-api/src/pay_api/services/payment.py
  pay-api/src/pay_api/services/payment_transaction.py
  queue_services/payment-reconciliations/src/reconciliations/enums.py
  queue_services/payment-reconciliations/src/reconciliations/worker.py
Labels: enhancement

#506 6038 : Fixing NSF partial payments
  pay-api/src/pay_api/services/payment.py
  pay-api/src/pay_api/services/payment_transaction.py
Labels: skip-changelog

#507 Dev to Test
  pay-api/src/pay_api/models/payment.py
  pay-api/src/pay_api/services/payment.py
  pay-api/src/pay_api/services/payment_transaction.py
  queue_services/payment-reconciliations/src/reconciliations/enums.py
  queue_services/payment-reconciliations/src/reconciliations/worker.py
Labels: skip-changelog

#508 Adding INACTIVE status to cfs account on creating invoice in PayBC.
  jobs/payment-jobs/tasks/cfs_create_invoice_task.py
Labels: bug

#509 Adding INACTIVE status to cfs account on creating invoice in PayBC.
  jobs/payment-jobs/tasks/cfs_create_invoice_task.py
  pay-api/src/pay_api/services/payment_transaction.py
  pay-api/tests/unit/services/test_payment_service.py
Labels: skip-changelog

#510 Dev to Test
  jobs/payment-jobs/tasks/cfs_create_invoice_task.py
  pay-api/src/pay_api/services/payment_transaction.py
  pay-api/tests/unit/services/test_payment_service.py
Labels: skip-changelog

#511 Fixing issue with PAD account update
  pay-api/src/pay_api/resources/account.py
  pay-api/src/pay_api/services/pad_service.py
  pay-api/src/pay_api/services/payment_account.py
  pay-api/tests/unit/api/test_account.py
Labels: bug

#513 Changes for generating invoice PDF
  pay-api/src/pay_api/resources/invoice.py
  pay-api/src/pay_api/services/invoice.py
  pay-api/tests/unit/api/test_payment_request.py
  report-api/report-templates/invoice.html
Labels: enhancement
