Repository bcgov/sbc-pay, pull requests merged in 2020-09, with the labels that each got.

#320 Corrected sort order and added test to verify it
  pay-api/src/pay_api/models/statement.py
  pay-api/tests/unit/api/test_statement.py
Labels: skip-changelog

#321 dev to test merge
  jobs/payment-jobs/statement_notification.html
  pay-api/src/pay_api/models/statement.py
  pay-api/tests/unit/api/test_statement.py
Labels: skip-changelog

#319 statement pdf layout fixes
  pay-api/src/pay_api/models/audit.py
  pay-api/src/pay_api/models/distribution_code.py
  pay-api/src/pay_api/models/invoice.py
  pay-api/src/pay_api/models/payment.py
  pay-api/src/pay_api/models/payment_transaction.py
  pay-api/src/pay_api/models/receipt.py
  pay-api/src/pay_api/models/statement.py
  pay-api/src/pay_api/services/auth.py
  pay-api/src/pay_api/services/payment.py
  pay-api/src/pay_api/utils/constants.py
  report-api/report-templates/statement_report.html
  report-api/src/api/__init__.py
  report-api/src/api/services/report_service.py
Labels: skip-changelog

#322 Dev to Test
  pay-api/src/pay_api/models/audit.py
  pay-api/src/pay_api/models/distribution_code.py
  pay-api/src/pay_api/models/invoice.py
  pay-api/src/pay_api/models/payment.py
  pay-api/src/pay_api/models/payment_transaction.py
  pay-api/src/pay_api/models/receipt.py
  pay-api/src/pay_api/models/statement.py
  pay-api/src/pay_api/services/auth.py
  pay-api/src/pay_api/services/payment.py
  pay-api/src/pay_api/utils/constants.py
  report-api/report-templates/statement_report.html
  report-api/src/api/__init__.py
  report-api/src/api/services/report_service.py
Labels: skip-changelog

#323 Fixing issue with a variable in statement report
  report-api/report-templates/statement_report.html
Labels: skip-changelog

#324 Dev to Test
  report-api/report-templates/statement_report.html
Labels: skip-changelog

#325 skip sending if no recipients ; modify script to create statements only for bcol accounts
  jobs/payment-jobs/tasks/statement_notification_task.py
  pay-api/migrations/versions/71c733c91cbf_add_default_weekly_frequency_to_.py
Labels: enhancement

#326 test deployment
  jobs/payment-jobs/tasks/statement_notification_task.py
  pay-api/migrations/versions/71c733c91cbf_add_default_weekly_frequency_to_.py
  report-api/report-templates/statement_report.html
Labels: skip-changelog

#329 statement endpoint returns more details
  pay-api/src/pay_api/services/statement_settings.py
Labels: enhancement

#330 statement-pdf-due-date always show
  report-api/report-templates/statement_report.html
Labels: skip-changelog

#331 Test Deployment
  pay-api/src/pay_api/services/statement_settings.py
  report-api/report-templates/statement_report.html
Labels: skip-changelog

#332 Fix for weekly statements not getting generated
  jobs/payment-jobs/tasks/statement_task.py
  pay-api/src/pay_api/services/statement_settings.py
  pay-api/tests/unit/api/test_statement_settings.py
  pay-api/tests/unit/services/test_statement_settings.py
Labels: bug

#328 Entity event listener to update transaction references
  .github/workflows/events-listener-check.yml
  .github/workflows/events-listener-dev.yml
  .github/workflows/events-listener-test.yml
  codecov.yaml
  pay-api/src/pay_api/__init__.py
  pay-api/src/pay_api/config.py
  pay-api/src/pay_api/models/credit_payment_account.py
  pay-api/src/pay_api/models/internal_payment_account.py
  pay-api/src/pay_api/models/invoice.py
  pay-api/src/pay_api/utils/util.py
  pay-api/tests/unit/conf/test_configuration.py
  queue_services/events-listener/.envrc
  queue_services/events-listener/Dockerfile
  queue_services/events-listener/LICENSE
  queue_services/events-listener/MANIFEST.in
  queue_services/events-listener/Makefile
  queue_services/events-listener/README.md
  queue_services/events-listener/app.py
  queue_services/events-listener/coverage.xml
  queue_services/events-listener/jenkins/dev.groovy
  queue_services/events-listener/jenkins/prod.groovy
  queue_services/events-listener/jenkins/test.groovy
  queue_services/events-listener/logging.conf
  queue_services/events-listener/openshift/templates/events-listener-build.json
  queue_services/events-listener/openshift/templates/events-listener-deploy.json
  queue_services/events-listener/openshift/templates/events-listener-pipeline.json
  queue_services/events-listener/q_cli.py
  queue_services/events-listener/requirements.txt
  queue_services/events-listener/requirements/dev.txt
  queue_services/events-listener/requirements/prod.txt
  queue_services/events-listener/requirements/repo-libraries.txt
  queue_services/events-listener/scripts/verify_license_headers.sh
  queue_services/events-listener/setup.cfg
  queue_services/events-listener/setup.py
  queue_services/events-listener/src/events_listener/__init__.py
  queue_services/events-listener/src/events_listener/config.py
  queue_services/events-listener/src/events_listener/utils.py
  queue_services/events-listener/src/events_listener/version.py
  queue_services/events-listener/src/events_listener/worker.py
  queue_services/events-listener/tests/__init__.py
  queue_services/events-listener/tests/conftest.py
  queue_services/events-listener/tests/docker-compose.yml
  queue_services/events-listener/tests/integration/__init__.py
  queue_services/events-listener/tests/integration/test_worker_queue.py
  queue_services/events-listener/tests/integration/utils.py
Labels: enhancement

#334 Changes to align with the message changes from entities
  queue_services/events-listener/requirements/repo-libraries.txt
  queue_services/events-listener/src/events_listener/worker.py
  queue_services/events-listener/tests/integration/utils.py
Labels: skip-changelog

#333 Switch CD process to bcrs_cd_action.
  .github/workflows/bcol-api-cd.yml
  .github/workflows/bcol-api-ci.yml
  .github/workflows/bcol-api-dev.yml
  .github/workflows/bcol-api-test.yml
  .github/workflows/events-listener-cd.yml
  .github/workflows/events-listener-ci.yml
  .github/workflows/events-listener-dev.yml
  .github/workflows/events-listener-test.yml
  .github/workflows/pay-api-cd.yml
  .github/workflows/pay-api-ci.yml
  .github/workflows/pay-api-dev.yml
  .github/workflows/pay-api-test.yml
  .github/workflows/payment-jobs-cd.yml
  .github/workflows/payment-jobs-ci.yml
  .github/workflows/report-api-cd.yml
  .github/workflows/report-api-ci.yml
  .github/workflows/report-api-dev.yml
  .github/workflows/report-api-test.yml
  codecov.yaml
  scripts/1pass.sh
  scripts/install_tools.sh
Labels: DoNotMerge, devops

#335 Upgrade cd action to 1.1.1.
  .github/workflows/bcol-api-cd.yml
  .github/workflows/events-listener-cd.yml
  .github/workflows/pay-api-cd.yml
  .github/workflows/payment-jobs-cd.yml
  .github/workflows/report-api-cd.yml
Labels: skip-changelog

#336 Update the cd action tag to latest.
  .github/workflows/bcol-api-cd.yml
  .github/workflows/events-listener-cd.yml
  .github/workflows/pay-api-cd.yml
  .github/workflows/payment-jobs-cd.yml
  .github/workflows/report-api-cd.yml
Labels: skip-changelog

#337 Changes to align with the message changes from entities
  queue_services/events-listener/q_cli.py
Labels: skip-changelog

#339 Changes to align with the message changes from entities
  queue_services/events-listener/q_cli.py
Labels: skip-changelog

#340 Update vaults's setting.
  .github/workflows/bcol-api-cd.yml
  .github/workflows/events-listener-cd.yml
  .github/workflows/pay-api-cd.yml
  .github/workflows/payment-jobs-cd.yml
  .github/workflows/report-api-cd.yml
Labels: skip-changelog

#341 Add OPENSHIFT_REPOSITORY_DEPLOYMENT input.
  .github/workflows/bcol-api-cd.yml
  .github/workflows/events-listener-cd.yml
  .github/workflows/pay-api-cd.yml
  .github/workflows/payment-jobs-cd.yml
  .github/workflows/report-api-cd.yml
Labels: skip-changelog

#343 fixed bug with weekly statements not getting generatd
  pay-api/src/pay_api/models/statement_settings.py
Labels: bug

#346 Fixing issue with migration
  pay-api/migrations/versions/56c5db141909_refactor_payment_account.py
Labels: skip-changelog

#347 Fixing issue with migration
  pay-api/migrations/versions/1283463d3b4a_new_payment_method_tables.py
  pay-api/migrations/versions/56c5db141909_refactor_payment_account.py
Labels: skip-changelog

#348 Changes to schema for create payment account endpoint
  pay-api/src/pay_api/schemas/schemas/account_info.json
  pay-api/src/pay_api/schemas/schemas/business_info.json
  pay-api/src/pay_api/schemas/schemas/payment_info.json
Labels: enhancement

#350 Search by username on transaction view - case insensitive search
  pay-api/src/pay_api/models/payment.py
Labels: enhancement

#349 Changes for new implementation class for online banking
  pay-api/requirements.txt
  pay-api/src/pay_api/factory/payment_system_factory.py
  pay-api/src/pay_api/services/__init__.py
  pay-api/src/pay_api/services/base_payment_system.py
  pay-api/src/pay_api/services/bcol_service.py
  pay-api/src/pay_api/services/cfs_service.py
  pay-api/src/pay_api/services/direct_pay_service.py
  pay-api/src/pay_api/services/internal_pay_service.py
  pay-api/src/pay_api/services/online_banking_service.py
  pay-api/src/pay_api/services/paybc_service.py
  pay-api/src/pay_api/services/payment.py
  pay-api/src/pay_api/services/payment_service.py
  pay-api/src/pay_api/services/payment_transaction.py
  pay-api/tests/unit/services/test_payment_system_service.py
Labels: enhancement

#351 Payment account creation endpoints
  pay-api/src/pay_api/resources/account.py
  pay-api/src/pay_api/services/auth.py
  pay-api/src/pay_api/services/base_payment_system.py
  pay-api/src/pay_api/services/bcol_service.py
  pay-api/src/pay_api/services/direct_pay_service.py
  pay-api/src/pay_api/services/internal_pay_service.py
  pay-api/src/pay_api/services/paybc_service.py
  pay-api/src/pay_api/services/payment_account.py
  pay-api/src/pay_api/services/payment_service.py
  pay-api/src/pay_api/utils/enums.py
  pay-api/src/pay_api/utils/errors.py
  pay-api/tests/unit/api/test_account.py
  pay-api/tests/unit/api/test_payment.py
  pay-api/tests/unit/services/test_bcol_service.py
  pay-api/tests/unit/services/test_payment_service.py
  pay-api/tests/utilities/base_test.py
Labels: enhancement

#355 Fixing issue with BCOL account number not populated for staff payments
  pay-api/src/pay_api/services/bcol_service.py
  pay-api/src/pay_api/services/online_banking_service.py
  pay-api/src/pay_api/services/payment_service.py
Labels: bug
