Repository bcgov/sbc-pay, pull requests merged in 2020-08, with the labels that each got.

#269 Changes for receipt to accommodate Names
  pay-api/src/pay_api/models/invoice.py
  pay-api/src/pay_api/resources/invoice_receipt.py
  pay-api/src/pay_api/services/oauth_service.py
  pay-api/src/pay_api/services/receipt.py
  pay-api/tests/unit/api/test_receipt.py
  report-api/report-templates/payment_receipt.html
Labels: enhancement

#272 changes for paybc direct payment url
  pay-api/config.py
  pay-api/src/pay_api/schemas/schemas/payment_info.json
  pay-api/src/pay_api/services/__init__.py
  pay-api/src/pay_api/services/direct_pay_service.py
  pay-api/src/pay_api/services/hashing.py
  pay-api/tests/unit/api/test_transaction.py
  pay-api/tests/unit/services/test_hashing_service.py
  pay-api/tests/unit/services/test_payment_transaction.py
Labels: enhancement

#273 Dev to Test
  pay-api/config.py
  pay-api/migrations/versions/39a97401040c_create_direct_pay_payment_method.py
  pay-api/migrations/versions/a11be9fe1a6a_distribution_code.py
  pay-api/migrations/versions/e385e278cf3e_merge_heads.py
  pay-api/src/pay_api/factory/payment_system_factory.py
  pay-api/src/pay_api/models/__init__.py
  pay-api/src/pay_api/models/corp_type.py
  pay-api/src/pay_api/models/distribution_code.py
  pay-api/src/pay_api/models/fee_schedule.py
  pay-api/src/pay_api/models/invoice.py
  pay-api/src/pay_api/models/payment_line_item.py
  pay-api/src/pay_api/resources/__init__.py
  pay-api/src/pay_api/resources/distributions.py
  pay-api/src/pay_api/resources/fee_schedule.py
  pay-api/src/pay_api/resources/invoice_receipt.py
  pay-api/src/pay_api/schemas/schemas/distribution_code.json
  pay-api/src/pay_api/schemas/schemas/payment_info.json
  pay-api/src/pay_api/services/__init__.py
  pay-api/src/pay_api/services/direct_pay_service.py
  pay-api/src/pay_api/services/distribution_code.py
  pay-api/src/pay_api/services/fee_schedule.py
  pay-api/src/pay_api/services/hashing.py
  pay-api/src/pay_api/services/invoice.py
  pay-api/src/pay_api/services/oauth_service.py
  pay-api/src/pay_api/services/paybc_service.py
  pay-api/src/pay_api/services/payment_line_item.py
  pay-api/src/pay_api/services/payment_service.py
  pay-api/src/pay_api/services/payment_transaction.py
  pay-api/src/pay_api/services/receipt.py
  pay-api/src/pay_api/utils/enums.py
  pay-api/tests/unit/api/test_distributions.py
  pay-api/tests/unit/api/test_fee.py
  pay-api/tests/unit/api/test_payment.py
  pay-api/tests/unit/api/test_receipt.py
  pay-api/tests/unit/api/test_transaction.py
  pay-api/tests/unit/factory/test_payment_system_factory.py
  pay-api/tests/unit/services/test_distribution_code.py
  pay-api/tests/unit/services/test_fee_schedule.py
  pay-api/tests/unit/services/test_hashing_service.py
  pay-api/tests/unit/services/test_payment.py
  pay-api/tests/unit/services/test_payment_account.py
  pay-api/tests/unit/services/test_payment_service.py
  pay-api/tests/unit/services/test_payment_transaction.py
  pay-api/tests/utilities/base_test.py
  report-api/report-templates/payment_receipt.html
Labels: enhancement

#274 Changes for handling return from direct pay
  pay-api/config.py
  pay-api/docs/dotenv_template
  pay-api/migrations/versions/7231303dabdf_direct_pay_error_messages.py
  pay-api/src/pay_api/models/payment_transaction.py
  pay-api/src/pay_api/resources/transaction.py
  pay-api/src/pay_api/services/base_payment_system.py
  pay-api/src/pay_api/services/bcol_service.py
  pay-api/src/pay_api/services/direct_pay_service.py
  pay-api/src/pay_api/services/internal_pay_service.py
  pay-api/src/pay_api/services/paybc_service.py
  pay-api/src/pay_api/services/payment_service.py
  pay-api/src/pay_api/services/payment_transaction.py
  pay-api/src/pay_api/utils/constants.py
  pay-api/src/pay_api/utils/errors.py
  pay-api/src/pay_api/utils/util.py
  pay-api/tests/unit/services/test_payment_transaction.py
Labels: enhancement

#277 Patch Fix to pull the account details for BUSINESS system accounts
  pay-api/src/pay_api/services/auth.py
  pay-api/src/pay_api/services/bcol_service.py
  pay-api/src/pay_api/utils/user_context.py
Labels: bug

#279 Changes to support manual alteration filing as staff filing
  pay-api/config.py
  pay-api/src/pay_api/models/corp_type.py
  pay-api/src/pay_api/services/auth.py
  pay-api/src/pay_api/services/bcol_service.py
  pay-api/src/pay_api/utils/enums.py
  pay-api/src/pay_api/utils/user_context.py
Labels: bug

#275 added test cases
  pay-api/src/pay_api/services/direct_pay_service.py
  pay-api/tests/unit/services/test_direct_pay_service.py
  pay-api/tests/utilities/base_test.py
Labels: enhancement

#280 Handling return from direct pay to auth
  docs/docs/PayBC Mocking/paybc-1.0.0.yaml
  pay-api/config.py
  pay-api/src/pay_api/models/corp_type.py
  pay-api/src/pay_api/resources/transaction.py
  pay-api/src/pay_api/services/direct_pay_service.py
  pay-api/src/pay_api/services/fee_schedule.py
  pay-api/src/pay_api/services/paybc_service.py
  pay-api/src/pay_api/utils/util.py
  pay-api/tests/docker/docker-compose.yml
  pay-api/tests/unit/api/test_transaction.py
  pay-api/tests/unit/services/test_direct_pay_service.py
  pay-api/tests/unit/services/test_payment_transaction.py
Labels: enhancement

#282 update-failed-distributions crond job added
  jobs/__init__.py
  jobs/update-failed-distributions/Dockerfile
  jobs/update-failed-distributions/README.md
  jobs/update-failed-distributions/cron/crontab
  jobs/update-failed-distributions/docker-entrypoint.sh
  jobs/update-failed-distributions/openshift/update-failed-distributions-build.json
  jobs/update-failed-distributions/openshift/update-failed-distributions-deploy.json
  jobs/update-failed-distributions/run.sh
  jobs/update-failed-distributions/src/__init__.py
  jobs/update-failed-distributions/src/config.py
  jobs/update-failed-distributions/src/logging.conf
  jobs/update-failed-distributions/src/rectify_gl_code_in_paybc.py
  jobs/update-failed-distributions/src/requirements.txt
  jobs/update-failed-distributions/src/requirements/dev.txt
  jobs/update-failed-distributions/src/requirements/prod.txt
  jobs/update-failed-distributions/src/tests/__init__.py
  jobs/update-failed-distributions/src/tests/unit/__init__.py
  jobs/update-failed-distributions/src/tests/unit/conftest.py
  jobs/update-failed-distributions/src/tests/unit/test_update_stale_payment_records.py
  jobs/update-failed-distributions/src/utils/__init__.py
  jobs/update-failed-distributions/src/utils/logger.py
Labels: enhancement

#284 Fixing issue with schema validation for distribution
  pay-api/src/pay_api/schemas/schemas/distribution_code.json
  pay-api/tests/utilities/base_test.py
Labels: bug

#283 Changes to handle direct pay transactions by update-stale-jobs
  jobs/update-stale-payment/config.py
  jobs/update-stale-payment/requirements/prod.txt
  jobs/update-stale-payment/update_stale_payment_records.py
  pay-api/src/pay_api/services/direct_pay_service.py
  pay-api/src/pay_api/services/invoice_reference.py
  pay-api/src/pay_api/services/payment_service.py
  pay-api/src/pay_api/services/payment_transaction.py
  pay-api/src/pay_api/services/receipt.py
  pay-api/tests/unit/services/test_payment_service.py
  pay-api/tests/unit/services/test_payment_transaction.py
  pay-api/tests/utilities/base_test.py
Labels: enhancement

#285 Python 3.8.5 upgrade.
  .github/workflows/bcol-api-check.yml
  .github/workflows/bcol-api-dev.yml
  .github/workflows/bcol-api-test.yml
  .github/workflows/pay-api-check.yml
  .github/workflows/pay-api-dev.yml
  .github/workflows/pay-api-test.yml
  .github/workflows/report-api-check.yml
  .github/workflows/report-api-dev.yml
  bcol-api/.dockerignore
  bcol-api/Dockerfile
  bcol-api/docker-entrypoint.sh
  bcol-api/entrypoint.sh
  bcol-api/logging.conf
  bcol-api/openshift/templates/bcol-api-build.json
  bcol-api/openshift/templates/bcol-api-deploy.e2e.json
  bcol-api/openshift/templates/bcol-api-deploy.json
  codecov.yaml
  pay-api/.dockerignore
  pay-api/Dockerfile
  pay-api/Makefile
  pay-api/config.py
  pay-api/docker-entrypoint.sh
  pay-api/entrypoint.sh
  pay-api/logging.conf
  pay-api/manage.py
  pay-api/openshift/templates/pay-api-build.json
  pay-api/openshift/templates/pay-api-deploy.e2e.json
  pay-api/openshift/templates/pay-api-deploy.json
  pay-api/pre-hook-update-db.sh
  pay-api/requirements.txt
  pay-api/src/pay_api/__init__.py
  report-api/.dockerignore
  report-api/Dockerfile
Labels: devops

#288 BCOL docker file update.
  bcol-api/Dockerfile
  bcol-api/requirements.txt
Labels: skip-changelog

#286 Update invoice status on changes to distribution code
  pay-api/migrations/versions/bb5b5cab004b_gl_updated_status.py
  pay-api/src/pay_api/models/distribution_code.py
  pay-api/src/pay_api/models/fee_schedule.py
  pay-api/src/pay_api/models/invoice.py
  pay-api/src/pay_api/services/distribution_code.py
  pay-api/src/pay_api/services/payment_transaction.py
  pay-api/src/pay_api/utils/enums.py
  pay-api/tests/unit/api/test_distributions.py
  pay-api/tests/unit/services/test_distribution_code.py
Labels: enhancement

#287 Changes for handling update for direct pay
  pay-api/src/pay_api/services/direct_pay_service.py
  pay-api/tests/unit/api/test_payment.py
Labels: bug

#291 Fix BCOL python-ldap openssl issue temporary.
  .github/workflows/report-api-test.yml
  bcol-api/Dockerfile
  bcol-api/scripts/openssl.cnf
Labels: bug

#289 Distribution update job to handle failed transactions
  jobs/update-failed-distributions/openshift/update-failed-distributions-deploy.json
  jobs/update-failed-distributions/src/config.py
  jobs/update-failed-distributions/src/rectify_gl_code_in_paybc.py
  jobs/update-failed-distributions/src/services/__init__.py
  jobs/update-failed-distributions/src/services/distribution_service.py
  jobs/update-failed-distributions/tests/__init__.py
  jobs/update-failed-distributions/tests/unit/__init__.py
  jobs/update-failed-distributions/tests/unit/conftest.py
  jobs/update-failed-distributions/tests/unit/test_update_stale_payment_records.py
  pay-api/src/pay_api/services/payment_transaction.py
Labels: enhancement

#292 Statements get endpoint;
  pay-api/migrations/versions/92fed98da61c_create_statement_tables.py
  pay-api/src/pay_api/models/__init__.py
  pay-api/src/pay_api/models/statement.py
  pay-api/src/pay_api/models/statement_invoices.py
  pay-api/src/pay_api/resources/__init__.py
  pay-api/src/pay_api/resources/account_statements.py
  pay-api/src/pay_api/services/__init__.py
  pay-api/src/pay_api/services/statement.py
Labels: enhancement

#293 Dev to Test
  .github/workflows/report-api-test.yml
  bcol-api/Dockerfile
  bcol-api/scripts/openssl.cnf
  jobs/update-failed-distributions/openshift/update-failed-distributions-deploy.json
  jobs/update-failed-distributions/src/config.py
  jobs/update-failed-distributions/src/rectify_gl_code_in_paybc.py
  jobs/update-failed-distributions/src/services/__init__.py
  jobs/update-failed-distributions/src/services/distribution_service.py
  jobs/update-failed-distributions/tests/__init__.py
  jobs/update-failed-distributions/tests/unit/__init__.py
  jobs/update-failed-distributions/tests/unit/conftest.py
  jobs/update-failed-distributions/tests/unit/test_update_stale_payment_records.py
  pay-api/migrations/versions/92fed98da61c_create_statement_tables.py
  pay-api/src/pay_api/models/__init__.py
  pay-api/src/pay_api/models/statement.py
  pay-api/src/pay_api/models/statement_invoices.py
  pay-api/src/pay_api/resources/__init__.py
  pay-api/src/pay_api/resources/account_statements.py
  pay-api/src/pay_api/services/__init__.py
  pay-api/src/pay_api/services/payment_transaction.py
  pay-api/src/pay_api/services/statement.py
Labels: skip-changelog

#294 Statement settings and statement generation job draft
  jobs/update-failed-distributions/run.sh
  jobs/update-failed-distributions/src/generate_account_statements.py
  jobs/update-failed-distributions/src/services/distribution_job.py
  jobs/update-failed-distributions/src/services/statement_job.py
  jobs/update-failed-distributions/src/update_gl_code_in_paybc.py
  pay-api/migrations/versions/4cc39da0bee7_payment_system_account.py
  pay-api/migrations/versions/567df104d26c_merge_heads.py
  pay-api/migrations/versions/7e51d3ce4005_statement_settings.py
  pay-api/src/pay_api/models/__init__.py
  pay-api/src/pay_api/models/statement.py
  pay-api/src/pay_api/models/statement_invoices.py
  pay-api/src/pay_api/models/statement_settings.py
  pay-api/src/pay_api/services/statement.py
  pay-api/src/pay_api/utils/enums.py
  pay-api/src/pay_api/utils/util.py
Labels: enhancement

#295 Added account_id to statement table
  pay-api/migrations/versions/444df7ad2d80_add_account_id_to_statements.py
  pay-api/src/pay_api/models/statement.py
Labels: enhancement

#296 Statement settings and statement generation job
  jobs/update-failed-distributions/config.py
  jobs/update-failed-distributions/generate_account_statements.py
  jobs/update-failed-distributions/jobs/__init__.py
  jobs/update-failed-distributions/jobs/distribution_job.py
  jobs/update-failed-distributions/jobs/statement_job.py
  jobs/update-failed-distributions/logging.conf
  jobs/update-failed-distributions/requirements.txt
  jobs/update-failed-distributions/requirements/dev.txt
  jobs/update-failed-distributions/requirements/prod.txt
  jobs/update-failed-distributions/src/services/__init__.py
  jobs/update-failed-distributions/tests/jobs/__init__.py
  jobs/update-failed-distributions/tests/jobs/conftest.py
  jobs/update-failed-distributions/tests/jobs/factory.py
  jobs/update-failed-distributions/tests/jobs/test_generate_statements.py
  jobs/update-failed-distributions/tests/unit/test_update_stale_payment_records.py
  jobs/update-failed-distributions/update_gl_code_in_paybc.py
  jobs/update-failed-distributions/utils/__init__.py
  jobs/update-failed-distributions/utils/logger.py
  pay-api/migrations/env.py
  pay-api/migrations/versions/bcb296e7f6f4_statement_to_date_changes.py
  pay-api/src/pay_api/models/payment_transaction.py
  pay-api/src/pay_api/models/statement.py
  pay-api/src/pay_api/models/statement_invoices.py
  pay-api/src/pay_api/models/statement_settings.py
  pay-api/src/pay_api/services/oauth_service.py
  pay-api/src/pay_api/services/statement.py
  pay-api/src/pay_api/utils/util.py
Labels: enhancement

#298 statement settings endpoints created
  pay-api/src/pay_api/models/statement_settings.py
  pay-api/src/pay_api/resources/__init__.py
  pay-api/src/pay_api/resources/account_statements_settings.py
  pay-api/src/pay_api/services/__init__.py
  pay-api/src/pay_api/services/statement.py
  pay-api/src/pay_api/services/statement_settings.py
  pay-api/tests/unit/api/test_statement_settings.py
Labels: enhancement

#301 added default frequency and added more tests
  jobs/update-failed-distributions/Dockerfile
  jobs/update-failed-distributions/cron/crontab
  jobs/update-failed-distributions/invoke_jobs.py
  jobs/update-failed-distributions/openshift/update-failed-distributions-build.json
  jobs/update-failed-distributions/run.sh
  jobs/update-failed-distributions/run_generate_statements.sh
  jobs/update-failed-distributions/run_update_gl_code_in_paybc.sh
  jobs/update-failed-distributions/update_gl_code_in_paybc.py
  jobs/update-stale-payment/openshift/cron-update-stale-payment.yaml
  pay-api/migrations/versions/71c733c91cbf_add_default_weekly_frequency_to_.py
  pay-api/requirements.txt
  pay-api/requirements/dev.txt
  pay-api/src/pay_api/models/statement_settings.py
  pay-api/src/pay_api/services/payment_account.py
  pay-api/src/pay_api/services/statement_settings.py
  pay-api/src/pay_api/utils/enums.py
  pay-api/tests/unit/api/test_statement.py
  pay-api/tests/unit/api/test_statement_settings.py
  pay-api/tests/unit/services/test_statement_settings.py
Labels: enhancement

#303 Filtering revenue update call only for direct pay invoices
  jobs/update-failed-distributions/jobs/distribution_job.py
  pay-api/src/pay_api/services/statement.py
Labels: skip-changelog

#304 Adding tables for review
  pay-api/migrations/versions/8f550bdc9491_notification_tables_added.py
  pay-api/src/pay_api/models/__init__.py
  pay-api/src/pay_api/models/notification_status_code.py
  pay-api/src/pay_api/models/payment_account.py
  pay-api/src/pay_api/models/statement.py
  pay-api/src/pay_api/models/statement_recipients.py
  pay-api/src/pay_api/resources/__init__.py
  pay-api/src/pay_api/resources/account_statements_notifications.py
  pay-api/src/pay_api/schemas/schemas/recipients.json
  pay-api/src/pay_api/schemas/schemas/statement_notification_request.json
  pay-api/src/pay_api/services/__init__.py
  pay-api/src/pay_api/services/statement_recipients.py
Labels: enhancement

#306 Statement Notification Job Added
  jobs/update-failed-distributions/config.py
  jobs/update-failed-distributions/invoke_jobs.py
  jobs/update-failed-distributions/jobs/statement_job.py
  jobs/update-failed-distributions/jobs/statement_notification_job.py
  jobs/update-failed-distributions/run_send_statement_notificaton.sh
  jobs/update-failed-distributions/statement_notification.html
  jobs/update-failed-distributions/utils/auth.py
  pay-api/migrations/versions/8f550bdc9491_notification_tables_added.py
  pay-api/src/pay_api/models/statement.py
  pay-api/src/pay_api/models/statement_recipients.py
  pay-api/src/pay_api/utils/enums.py
Labels: enhancement

#307 Adding Access-Control-Expose-Headers header to report downloads
  pay-api/src/pay_api/resources/account.py
  pay-api/src/pay_api/resources/account_statements.py
  pay-api/src/pay_api/resources/invoice_receipt.py
  pay-api/src/pay_api/services/payment.py
  pay-api/src/pay_api/services/statement.py
Labels: skip-changelog

#308 refactoring of the job project
  jobs/payment-jobs/Dockerfile
  jobs/payment-jobs/README.md
  jobs/payment-jobs/config.py
  jobs/payment-jobs/cron/crontab
  jobs/payment-jobs/docker-entrypoint.sh
  jobs/payment-jobs/invoke_jobs.py
  jobs/payment-jobs/logging.conf
  jobs/payment-jobs/openshift/payment-job-build.json
  jobs/payment-jobs/openshift/payment-job-deploy.json
  jobs/payment-jobs/requirements.txt
  jobs/payment-jobs/requirements/dev.txt
  jobs/payment-jobs/requirements/prod.txt
  jobs/payment-jobs/run_generate_statements.sh
  jobs/payment-jobs/run_send_statement_notificaton.sh
  jobs/payment-jobs/run_update_gl_code_in_paybc.sh
  jobs/payment-jobs/statement_notification.html
  jobs/payment-jobs/tasks/__init__.py
  jobs/payment-jobs/tasks/distribution_task.py
  jobs/payment-jobs/tasks/statement_notification_task.py
  jobs/payment-jobs/tasks/statement_task.py
  jobs/payment-jobs/tests/__init__.py
  jobs/payment-jobs/tests/jobs/__init__.py
  jobs/payment-jobs/tests/jobs/conftest.py
  jobs/payment-jobs/tests/jobs/factory.py
  jobs/payment-jobs/tests/jobs/test_generate_statements.py
  jobs/payment-jobs/utils/__init__.py
  jobs/payment-jobs/utils/auth.py
  jobs/payment-jobs/utils/logger.py
Labels: enhancement

#305 Adding statement PDF template
  report-api/report-templates/statement_report.html
Labels: enhancement

#311 when no payment account is created , return False
  pay-api/src/pay_api/services/statement_recipients.py
Labels: skip-changelog

#310 Adding statement PDF template (#305)
  pay-api/src/pay_api/services/statement_recipients.py
  report-api/report-templates/statement_report.html
Labels: skip-changelog

#312 statement pdf layout correction
  report-api/report-templates/statement_report.html
Labels: skip-changelog

#314 Adding payment join on statement query
  pay-api/src/pay_api/models/statement.py
Labels: skip-changelog

#315 dev to test merge
  pay-api/src/pay_api/models/statement.py
  report-api/report-templates/statement_report.html
Labels: skip-changelog

#317 test development
  report-api/report-templates/statement_report.html
Labels: skip-changelog

#318 [entity4683] Statement Email Notification Content Changes
  jobs/payment-jobs/statement_notification.html
Labels: skip-changelog
