Repository bcgov/sbc-pay, pull requests merged in 2020-11, with the labels that each got.

#390 Roll up transactions and create invoice in CFS
  jobs/payment-jobs/config.py
  jobs/payment-jobs/invoke_jobs.py
  jobs/payment-jobs/requirements/prod.txt
  jobs/payment-jobs/tasks/cfs_create_account_task.py
  jobs/payment-jobs/tasks/cfs_create_invoice_task.py
  jobs/payment-jobs/tests/jobs/factory.py
  jobs/payment-jobs/tests/jobs/test_cfs_create_account_task.py
  jobs/payment-jobs/tests/jobs/test_cfs_create_invoice_task.py
  jobs/payment-jobs/tests/jobs/test_generate_statements.py
  pay-api/migrations/versions/2d025cbefda8_settlement_sched_refund_requested_.py
  pay-api/src/pay_api/config.py
  pay-api/src/pay_api/services/bcol_service.py
  pay-api/src/pay_api/services/cfs_service.py
  pay-api/src/pay_api/services/direct_pay_service.py
  pay-api/src/pay_api/services/internal_pay_service.py
  pay-api/src/pay_api/services/paybc_service.py
  pay-api/src/pay_api/utils/enums.py
  pay-api/src/pay_api/utils/util.py
  pay-api/tests/docker/docker-compose.yml
  pay-api/tests/unit/services/test_direct_pay_service.py
Labels: enhancement

#391 Updating config keys
  jobs/payment-jobs/config.py
  pay-api/src/pay_api/config.py
  pay-api/src/pay_api/services/queue_publisher.py
  queue_services/events-listener/q_cli.py
  queue_services/events-listener/src/events_listener/config.py
  queue_services/events-listener/tests/conftest.py
  queue_services/events-listener/tests/integration/__init__.py
  queue_services/events-listener/tests/integration/test_worker_queue.py
Labels: skip-changelog

#393 Refunds
  pay-api/migrations/versions/086e16326076_refunds.py
  pay-api/src/pay_api/config.py
  pay-api/src/pay_api/models/__init__.py
  pay-api/src/pay_api/models/payment_transaction.py
  pay-api/src/pay_api/models/refund.py
  pay-api/src/pay_api/resources/__init__.py
  pay-api/src/pay_api/resources/refund.py
  pay-api/src/pay_api/schemas/schemas/refund.json
  pay-api/src/pay_api/services/__init__.py
  pay-api/src/pay_api/services/refund.py
  pay-api/src/pay_api/utils/enums.py
  pay-api/src/pay_api/utils/util.py
  pay-api/tests/unit/api/test_refund.py
  pay-api/tests/unit/services/test_refund.py
  pay-api/tests/utilities/base_test.py
Labels: enhancement

#397 Updating API spec to include refunds endpoint
  docs/docs/api_contract/pay-api-1.0.0.yaml
Labels: skip-changelog

#398 Payment Reconciliations queue listener initial setup
  .github/workflows/payment-reconciliations-cd.yml
  .github/workflows/payment-reconciliations-ci.yml
  queue_services/payment-reconciliations/.envrc
  queue_services/payment-reconciliations/Dockerfile
  queue_services/payment-reconciliations/LICENSE
  queue_services/payment-reconciliations/MANIFEST.in
  queue_services/payment-reconciliations/Makefile
  queue_services/payment-reconciliations/README.md
  queue_services/payment-reconciliations/app.py
  queue_services/payment-reconciliations/jenkins/dev.groovy
  queue_services/payment-reconciliations/jenkins/prod.groovy
  queue_services/payment-reconciliations/jenkins/test.groovy
  queue_services/payment-reconciliations/logging.conf
  queue_services/payment-reconciliations/openshift/templates/payment-reconciliations-build.json
  queue_services/payment-reconciliations/openshift/templates/payment-reconciliations-deploy.json
  queue_services/payment-reconciliations/openshift/templates/payment-reconciliations-pipeline.json
  queue_services/payment-reconciliations/q_cli.py
  queue_services/payment-reconciliations/requirements.txt
  queue_services/payment-reconciliations/requirements/dev.txt
  queue_services/payment-reconciliations/requirements/prod.txt
  queue_services/payment-reconciliations/requirements/repo-libraries.txt
  queue_services/payment-reconciliations/scripts/verify_license_headers.sh
  queue_services/payment-reconciliations/setup.cfg
  queue_services/payment-reconciliations/setup.py
  queue_services/payment-reconciliations/src/reconciliations/__init__.py
  queue_services/payment-reconciliations/src/reconciliations/config.py
  queue_services/payment-reconciliations/src/reconciliations/utils.py
  queue_services/payment-reconciliations/src/reconciliations/version.py
  queue_services/payment-reconciliations/src/reconciliations/worker.py
  queue_services/payment-reconciliations/tests/__init__.py
  queue_services/payment-reconciliations/tests/conftest.py
  queue_services/payment-reconciliations/tests/docker-compose.yml
  queue_services/payment-reconciliations/tests/integration/__init__.py
  queue_services/payment-reconciliations/tests/integration/utils.py
Labels: enhancement

#396 Adding isPaymentActionRequired flag to invoice response
  pay-api/src/pay_api/models/invoice.py
  pay-api/src/pay_api/services/invoice.py
  pay-api/tests/unit/api/test_payment.py
Labels: enhancement

#394 Ftp poller Job added
  jobs/ftp-poller/Dockerfile
  jobs/ftp-poller/LICENSE
  jobs/ftp-poller/Makefile
  jobs/ftp-poller/README.md
  jobs/ftp-poller/config.py
  jobs/ftp-poller/cron/crontab
  jobs/ftp-poller/docker-entrypoint.sh
  jobs/ftp-poller/invoke_jobs.py
  jobs/ftp-poller/logging.conf
  jobs/ftp-poller/openshift/ftp-poller-build.json
  jobs/ftp-poller/openshift/ftp-poller-deploy.json
  jobs/ftp-poller/requirements.txt
  jobs/ftp-poller/requirements/dev.txt
  jobs/ftp-poller/requirements/prod.txt
  jobs/ftp-poller/run_ftp_poller.sh
  jobs/ftp-poller/services/sftp.py
  jobs/ftp-poller/setup.cfg
  jobs/ftp-poller/setup.py
  jobs/ftp-poller/tasks/__init__.py
  jobs/ftp-poller/tasks/poll_ftp_task.py
  jobs/ftp-poller/tests/__init__.py
  jobs/ftp-poller/tests/docker/docker-compose.yml
  jobs/ftp-poller/tests/docker/ftp/test.txt
  jobs/ftp-poller/tests/docker/nginx.conf
  jobs/ftp-poller/tests/docker/run.sh
  jobs/ftp-poller/tests/jobs/__init__.py
  jobs/ftp-poller/tests/jobs/conftest.py
  jobs/ftp-poller/tests/jobs/test_sftp.py
  jobs/ftp-poller/utils/__init__.py
  jobs/ftp-poller/utils/logger.py
  jobs/ftp-poller/utils/minio.py
Labels: enhancement

#395 GH actions for poller job added
  .github/workflows/ftp-poller-cd.yml
  .github/workflows/ftp-poller-ci.yml
Labels: devops

#399 Changes for adding invice_amount and paid_amount to payment table
  jobs/payment-jobs/requirements/prod.txt
  jobs/payment-jobs/tasks/cfs_create_invoice_task.py
  pay-api/migrations/versions/7c19ee3a58aa_invoice_amount_to_payment.py
  pay-api/src/pay_api/models/payment.py
  pay-api/src/pay_api/services/base_payment_system.py
  pay-api/src/pay_api/services/bcol_service.py
  pay-api/src/pay_api/services/direct_pay_service.py
  pay-api/src/pay_api/services/internal_pay_service.py
  pay-api/src/pay_api/services/online_banking_service.py
  pay-api/src/pay_api/services/pad_service.py
  pay-api/src/pay_api/services/paybc_service.py
  pay-api/src/pay_api/services/payment.py
  pay-api/src/pay_api/services/payment_service.py
  pay-api/src/pay_api/services/payment_transaction.py
  pay-api/src/pay_api/utils/enums.py
Labels: skip-changelog

#403 Sftp adjustments (#402)
  jobs/ftp-poller/README.md
  jobs/ftp-poller/config.py
  jobs/ftp-poller/openshift/ftp-poller-deploy.json
  jobs/ftp-poller/services/sftp.py
  jobs/ftp-poller/tests/jobs/test_sftp.py
Labels: skip-changelog

#406 Update for set environment variables issue of GHA.
  .github/workflows/bcol-api-cd.yml
  .github/workflows/events-listener-cd.yml
  .github/workflows/ftp-poller-cd.yml
  .github/workflows/pay-api-cd.yml
  .github/workflows/payment-jobs-cd.yml
  .github/workflows/payment-reconciliations-cd.yml
  .github/workflows/report-api-cd.yml
Labels: devops

#405 CAS settlement
  .github/workflows/payment-reconciliations-cd.yml
  .github/workflows/payment-reconciliations-ci.yml
  .gitignore
  jobs/payment-jobs/tasks/cfs_create_invoice_task.py
  jobs/payment-jobs/tests/jobs/test_cfs_create_invoice_task.py
  pay-api/src/pay_api/config.py
  pay-api/src/pay_api/models/payment_transaction.py
  pay-api/src/pay_api/services/payment_transaction.py
  pay-api/src/pay_api/utils/enums.py
  queue_services/payment-reconciliations/app.py
  queue_services/payment-reconciliations/q_cli.py
  queue_services/payment-reconciliations/requirements.txt
  queue_services/payment-reconciliations/requirements/dev.txt
  queue_services/payment-reconciliations/requirements/prod.txt
  queue_services/payment-reconciliations/requirements/repo-libraries.txt
  queue_services/payment-reconciliations/setup.py
  queue_services/payment-reconciliations/src/reconciliations/config.py
  queue_services/payment-reconciliations/src/reconciliations/enums.py
  queue_services/payment-reconciliations/src/reconciliations/minio.py
  queue_services/payment-reconciliations/src/reconciliations/worker.py
  queue_services/payment-reconciliations/tests/conftest.py
  queue_services/payment-reconciliations/tests/docker-compose.yml
  queue_services/payment-reconciliations/tests/integration/factory.py
  queue_services/payment-reconciliations/tests/integration/test_payment_reconciliations.py
  queue_services/payment-reconciliations/tests/integration/utils.py
Labels: skip-changelog

#409 Dev to Test
  .github/workflows/bcol-api-cd.yml
  .github/workflows/events-listener-cd.yml
  .github/workflows/ftp-poller-cd.yml
  .github/workflows/pay-api-cd.yml
  .github/workflows/payment-jobs-cd.yml
  .github/workflows/payment-reconciliations-cd.yml
  .github/workflows/payment-reconciliations-ci.yml
  .github/workflows/report-api-cd.yml
  .gitignore
  jobs/ftp-poller/README.md
  jobs/ftp-poller/config.py
  jobs/ftp-poller/openshift/ftp-poller-deploy.json
  jobs/ftp-poller/services/sftp.py
  jobs/ftp-poller/tests/jobs/test_sftp.py
  jobs/payment-jobs/requirements/prod.txt
  jobs/payment-jobs/tasks/cfs_create_invoice_task.py
  jobs/payment-jobs/tests/jobs/test_cfs_create_invoice_task.py
  pay-api/migrations/versions/7c19ee3a58aa_invoice_amount_to_payment.py
  pay-api/src/pay_api/config.py
  pay-api/src/pay_api/models/payment.py
  pay-api/src/pay_api/models/payment_transaction.py
  pay-api/src/pay_api/services/base_payment_system.py
  pay-api/src/pay_api/services/bcol_service.py
  pay-api/src/pay_api/services/direct_pay_service.py
  pay-api/src/pay_api/services/internal_pay_service.py
  pay-api/src/pay_api/services/online_banking_service.py
  pay-api/src/pay_api/services/pad_service.py
  pay-api/src/pay_api/services/paybc_service.py
  pay-api/src/pay_api/services/payment.py
  pay-api/src/pay_api/services/payment_service.py
  pay-api/src/pay_api/services/payment_transaction.py
  pay-api/src/pay_api/utils/enums.py
  queue_services/payment-reconciliations/app.py
  queue_services/payment-reconciliations/q_cli.py
  queue_services/payment-reconciliations/requirements.txt
  queue_services/payment-reconciliations/requirements/dev.txt
  queue_services/payment-reconciliations/requirements/prod.txt
  queue_services/payment-reconciliations/requirements/repo-libraries.txt
  queue_services/payment-reconciliations/setup.py
  queue_services/payment-reconciliations/src/reconciliations/config.py
  queue_services/payment-reconciliations/src/reconciliations/enums.py
  queue_services/payment-reconciliations/src/reconciliations/minio.py
  queue_services/payment-reconciliations/src/reconciliations/worker.py
  queue_services/payment-reconciliations/tests/conftest.py
  queue_services/payment-reconciliations/tests/docker-compose.yml
  queue_services/payment-reconciliations/tests/integration/factory.py
  queue_services/payment-reconciliations/tests/integration/test_payment_reconciliations.py
  queue_services/payment-reconciliations/tests/integration/utils.py
Labels: skip-changelog

#410 Updating requirements to point to bcgov development branch.
  jobs/payment-jobs/requirements/prod.txt
  queue_services/payment-reconciliations/requirements.txt
  queue_services/payment-reconciliations/requirements/repo-libraries.txt
Labels: skip-changelog

#408 Pad confirmation related changes (#6)
  jobs/payment-jobs/README.md
  jobs/payment-jobs/config.py
  jobs/payment-jobs/invoke_jobs.py
  jobs/payment-jobs/requirements/dev.txt
  jobs/payment-jobs/requirements/prod.txt
  jobs/payment-jobs/run_activate_pad_account.sh
  jobs/payment-jobs/tasks/activate_pad_account_task.py
  jobs/payment-jobs/tasks/cfs_create_account_task.py
  jobs/payment-jobs/tests/jobs/factory.py
  jobs/payment-jobs/tests/jobs/test_activate_pad_account_task.py
  jobs/payment-jobs/tests/jobs/test_cfs_create_account_task.py
  jobs/payment-jobs/utils/__init__.py
  pay-api/migrations/versions/b624b5dbc9b9_added_pad_activation_dates.py
  pay-api/requirements.txt
  pay-api/src/pay_api/config.py
  pay-api/src/pay_api/factory/payment_system_factory.py
  pay-api/src/pay_api/models/cfs_account.py
  pay-api/src/pay_api/models/cfs_account_status_code.py
  pay-api/src/pay_api/models/payment_account.py
  pay-api/src/pay_api/services/payment_account.py
  pay-api/src/pay_api/services/payment_service.py
  pay-api/src/pay_api/utils/enums.py
  pay-api/src/pay_api/utils/errors.py
  pay-api/tests/unit/api/test_account.py
  pay-api/tests/unit/factory/test_payment_system_factory.py
  pay-api/tests/unit/services/test_payment_account.py
  pay-api/tests/utilities/base_test.py
Labels: enhancement

#411 Adding customer profile class to CFS Account creation payload
  pay-api/src/pay_api/services/cfs_service.py
  pay-api/src/pay_api/utils/constants.py
Labels: skip-changelog

#412 Dev to Test
  jobs/payment-jobs/README.md
  jobs/payment-jobs/config.py
  jobs/payment-jobs/invoke_jobs.py
  jobs/payment-jobs/requirements/dev.txt
  jobs/payment-jobs/requirements/prod.txt
  jobs/payment-jobs/run_activate_pad_account.sh
  jobs/payment-jobs/tasks/activate_pad_account_task.py
  jobs/payment-jobs/tasks/cfs_create_account_task.py
  jobs/payment-jobs/tests/jobs/factory.py
  jobs/payment-jobs/tests/jobs/test_activate_pad_account_task.py
  jobs/payment-jobs/tests/jobs/test_cfs_create_account_task.py
  jobs/payment-jobs/utils/__init__.py
  pay-api/migrations/versions/b624b5dbc9b9_added_pad_activation_dates.py
  pay-api/requirements.txt
  pay-api/src/pay_api/config.py
  pay-api/src/pay_api/factory/payment_system_factory.py
  pay-api/src/pay_api/models/cfs_account.py
  pay-api/src/pay_api/models/cfs_account_status_code.py
  pay-api/src/pay_api/models/payment_account.py
  pay-api/src/pay_api/services/cfs_service.py
  pay-api/src/pay_api/services/payment_account.py
  pay-api/src/pay_api/services/payment_service.py
  pay-api/src/pay_api/utils/constants.py
  pay-api/src/pay_api/utils/enums.py
  pay-api/src/pay_api/utils/errors.py
  pay-api/tests/unit/api/test_account.py
  pay-api/tests/unit/factory/test_payment_system_factory.py
  pay-api/tests/unit/services/test_payment_account.py
  pay-api/tests/utilities/base_test.py
Labels: skip-changelog

#413 Adding components diagram for accounts and payments
  docs/docs/architecture/Acccounts-Pay.gliffy
  docs/docs/architecture/Acccounts-Pay.png
Labels: documentation

#415 Fixing issue with distribution task
  jobs/payment-jobs/tasks/distribution_task.py
Labels: skip-changelog

#416 Dev to Test
  jobs/payment-jobs/tasks/distribution_task.py
Labels: skip-changelog

#417 Adding customer profile class to site creation
  pay-api/src/pay_api/services/cfs_service.py
Labels: skip-changelog

#418 5522: Adding fee codes for ULC and TRANS
  .github/workflows/pay-api-cd.yml
  pay-api/migrations/versions/b7443d501d98_entity_fee_codes.py
  pay-api/src/pay_api/resources/account.py
  pay-api/src/pay_api/services/payment_account.py
  pay-api/tests/unit/api/test_account.py
  pay-api/tests/unit/services/test_payment_service.py
  pay-api/tests/utilities/base_test.py
Labels: enhancement

#419 Changes to reflect CAS settlement file changes
  queue_services/payment-reconciliations/src/reconciliations/enums.py
  queue_services/payment-reconciliations/src/reconciliations/worker.py
  queue_services/payment-reconciliations/tests/integration/test_payment_reconciliations.py
Labels: skip-changelog

#420 Dev to Test
  .github/workflows/pay-api-cd.yml
  pay-api/migrations/versions/b7443d501d98_entity_fee_codes.py
  pay-api/src/pay_api/resources/account.py
  pay-api/src/pay_api/services/cfs_service.py
  pay-api/src/pay_api/services/payment_account.py
  pay-api/tests/unit/api/test_account.py
  pay-api/tests/unit/services/test_payment_service.py
  pay-api/tests/utilities/base_test.py
  queue_services/payment-reconciliations/src/reconciliations/enums.py
  queue_services/payment-reconciliations/src/reconciliations/worker.py
  queue_services/payment-reconciliations/tests/integration/test_payment_reconciliations.py
Labels: skip-changelog

#421 Changes to reflect CAS settlement file changes
  queue_services/payment-reconciliations/src/reconciliations/worker.py
Labels: skip-changelog

#422 Dev to Test
  queue_services/payment-reconciliations/src/reconciliations/worker.py
Labels: skip-changelog

#423 Changes to reflect CAS settlement file changes
  queue_services/payment-reconciliations/src/reconciliations/enums.py
Labels: skip-changelog

#424 Changes to reflect CAS settlement file changes
  queue_services/payment-reconciliations/src/reconciliations/worker.py
Labels: skip-changelog

#425 Changes to reflect CAS settlement file changes
  queue_services/payment-reconciliations/src/reconciliations/worker.py
Labels: skip-changelog

#426 Fixed activation time in utc
  pay-api/src/pay_api/config.py
  pay-api/src/pay_api/services/payment_account.py
  pay-api/tests/unit/services/test_payment_account.py
Labels: skip-changelog

#429 Fixing the typo in the mailer config
  pay-api/src/pay_api/services/payment_account.py
Labels: skip-changelog

#431 Changed the date from end of the day to 12.00AM
  pay-api/src/pay_api/services/payment_account.py
  pay-api/src/pay_api/utils/util.py
Labels: skip-changelog

#427 4857: Adding account payments endpoint to return all failed payments for NSF
  pay-api/migrations/versions/b05d371ad030_payment_failed_status.py
  pay-api/src/pay_api/models/invoice.py
  pay-api/src/pay_api/models/payment.py
  pay-api/src/pay_api/models/payment_account.py
  pay-api/src/pay_api/resources/__init__.py
  pay-api/src/pay_api/resources/account.py
  pay-api/src/pay_api/resources/invoice.py
  pay-api/src/pay_api/resources/invoices.py
  pay-api/src/pay_api/resources/payment.py
  pay-api/src/pay_api/services/payment.py
  pay-api/src/pay_api/services/payment_service.py
  pay-api/tests/unit/api/test_account.py
  pay-api/tests/unit/api/test_payment.py
  pay-api/tests/unit/api/test_payment_request.py
  pay-api/tests/unit/services/test_payment.py
  pay-api/tests/utilities/base_test.py
Labels: enhancement

#434 Creating POST payments to retry failed payments
  docs/docs/PayBC Mocking/paybc-1.0.0.yaml
  pay-api/src/pay_api/models/payment.py
  pay-api/src/pay_api/resources/payment.py
  pay-api/src/pay_api/services/cfs_service.py
  pay-api/src/pay_api/services/paybc_service.py
  pay-api/src/pay_api/services/payment.py
  pay-api/src/pay_api/services/payment_transaction.py
  pay-api/src/pay_api/utils/util.py
  pay-api/tests/docker/docker-compose.yml
  pay-api/tests/unit/api/test_payment.py
  pay-api/tests/unit/services/test_payment.py
  pay-api/tests/utilities/base_test.py
Labels: enhancement

#435 Changes to base_payment_system to make get_payment_system_url as not abstract
  pay-api/src/pay_api/services/base_payment_system.py
  pay-api/src/pay_api/services/bcol_service.py
  pay-api/src/pay_api/services/direct_pay_service.py
  pay-api/src/pay_api/services/internal_pay_service.py
  pay-api/src/pay_api/services/online_banking_service.py
  pay-api/src/pay_api/services/pad_service.py
  pay-api/src/pay_api/services/paybc_service.py
  pay-api/tests/unit/services/test_bcol_service.py
  pay-api/tests/unit/services/test_direct_pay_service.py
  pay-api/tests/unit/services/test_pad_service.py
  pay-api/tests/unit/services/test_payment_system_service.py
Labels: skip-changelog

#436 Changes for POST transactions on payment
  pay-api/src/pay_api/models/invoice_reference.py
  pay-api/src/pay_api/resources/__init__.py
  pay-api/src/pay_api/resources/transaction.py
  pay-api/src/pay_api/services/bcol_service.py
  pay-api/src/pay_api/services/internal_pay_service.py
  pay-api/src/pay_api/services/invoice_reference.py
  pay-api/src/pay_api/services/paybc_service.py
  pay-api/src/pay_api/services/payment_transaction.py
  pay-api/tests/unit/api/test_transaction.py
  pay-api/tests/unit/services/test_distribution_code.py
  pay-api/tests/unit/services/test_payment_transaction.py
  pay-api/tests/unit/services/test_receipt.py
Labels: enhancement

#437 Changes for PATCH transactions to handle unlock account.
  .github/workflows/pay-api-cd.yml
  pay-api/src/pay_api/models/invoice.py
  pay-api/src/pay_api/models/payment.py
  pay-api/src/pay_api/models/payment_transaction.py
  pay-api/src/pay_api/resources/payment.py
  pay-api/src/pay_api/resources/transaction.py
  pay-api/src/pay_api/services/paybc_service.py
  pay-api/src/pay_api/services/payment_account.py
  pay-api/src/pay_api/services/payment_transaction.py
  pay-api/src/pay_api/utils/constants.py
  pay-api/tests/unit/services/test_distribution_code.py
  pay-api/tests/unit/services/test_payment_transaction.py
  pay-api/tests/unit/services/test_receipt.py
  pay-api/tests/utilities/base_test.py
Labels: enhancement

#438 Changes to reconciliations job on NSF
  .github/workflows/payment-reconciliations-ci.yml
  docs/docs/PayBC Mocking/paybc-1.0.0.yaml
  pay-api/migrations/versions/e699674b1774_nsf_fee_code.py
  pay-api/requirements.txt
  pay-api/requirements/prod.txt
  pay-api/requirements/repo-libraries.txt
  pay-api/src/pay_api/services/cfs_service.py
  pay-api/src/pay_api/services/payment_account.py
  pay-api/tests/docker/docker-compose.yml
  queue_services/events-listener/requirements.txt
  queue_services/events-listener/requirements/repo-libraries.txt
  queue_services/payment-reconciliations/Dockerfile
  queue_services/payment-reconciliations/requirements.txt
  queue_services/payment-reconciliations/requirements/repo-libraries.txt
  queue_services/payment-reconciliations/src/reconciliations/config.py
  queue_services/payment-reconciliations/src/reconciliations/worker.py
  queue_services/payment-reconciliations/tests/docker-compose.yml
  queue_services/payment-reconciliations/tests/integration/factory.py
  queue_services/payment-reconciliations/tests/integration/test_payment_reconciliations.py
  queue_services/payment-reconciliations/tests/integration/utils.py
  queue_services/payment-reconciliations/tests/nginx.conf
Labels: enhancement

#439 Fixing issue with update site.
  pay-api/src/pay_api/services/cfs_service.py
  pay-api/src/pay_api/services/oauth_service.py
Labels: skip-changelog
