Repository bcgov/sbc-pay, pull requests merged in 2021-11, with the labels that each got.

#809 changed flush to commit since no commit follows
  jobs/payment-jobs/services/routing_slip.py
Labels: skip-changelog

#810 added EJV check for payment receipt generation
  report-api/report-templates/payment_receipt.html
  report-api/src/api/resources/report.py
  report-api/src/api/services/report_service.py
  report-api/src/api/services/template_service.py
  report-api/src/api/utils/logging.py
Labels: enhancement

#806 Added exception handling for wrong bank details
  jobs/payment-jobs/tasks/cfs_create_account_task.py
  jobs/payment-jobs/tests/jobs/test_cfs_create_account_task.py
Labels: enhancement

#812 Changes to invoice status for EJV refunds
  pay-api/src/pay_api/services/ejv_pay_service.py
  pay-api/src/pay_api/services/refund.py
Labels: bug

#813 Fixed EJV Report Generation
  pay-api/src/pay_api/resources/invoice_receipt.py
  pay-api/src/pay_api/services/receipt.py
Labels: skip-changelog

#811 Changes for allowing a sandbox account to be created by service account
  pay-api/src/pay_api/resources/account.py
  pay-api/src/pay_api/services/payment_account.py
  pay-api/src/pay_api/utils/enums.py
  pay-api/tests/unit/api/test_account.py
Labels: enhancement

#814 party name changed to account id instead of account name
  jobs/payment-jobs/requirements.txt
  jobs/payment-jobs/requirements/prod.txt
  jobs/payment-jobs/services/routing_slip.py
  jobs/payment-jobs/tasks/cfs_create_account_task.py
  pay-api/src/pay_api/config.py
  pay-api/src/pay_api/services/base_payment_system.py
  pay-api/src/pay_api/services/cfs_service.py
  pay-api/src/pay_api/services/deposit_service.py
  pay-api/src/pay_api/services/online_banking_service.py
  pay-api/src/pay_api/services/pad_service.py
  pay-api/src/pay_api/services/paybc_service.py
  pay-api/src/pay_api/services/payment_account.py
  pay-api/tests/unit/services/test_bcol_service.py
  pay-api/tests/unit/services/test_pad_service.py
Labels: enhancement

#816 made account update to work with partial data
  pay-api/src/pay_api/services/payment_account.py
  pay-api/tests/unit/api/test_account.py
Labels: skip-changelog

#817 Changes for marking payment records as complete for sandbox tokens
  pay-api/src/pay_api/services/base_payment_system.py
  pay-api/src/pay_api/services/bcol_service.py
  pay-api/src/pay_api/services/ejv_pay_service.py
  pay-api/src/pay_api/services/internal_pay_service.py
  pay-api/src/pay_api/services/pad_service.py
  pay-api/src/pay_api/utils/enums.py
  pay-api/src/pay_api/utils/user_context.py
  pay-api/tests/unit/api/test_payment_request.py
Labels: enhancement

#818 Fixing the API Spec to update some attributes
  docs/docs/api_contract/pay-api-1.0.0.yaml
Labels: skip-changelog

#821 Fixing spec for CSO
  docs/docs/api_contract/pay-api-1.0.0.yaml
Labels: skip-changelog

#819 rs invoices made to job
  docs/docs/PayBC Mocking/paybc-1.0.0.yaml
  jobs/payment-jobs/requirements.txt
  jobs/payment-jobs/requirements/prod.txt
  jobs/payment-jobs/tasks/cfs_create_invoice_task.py
  jobs/payment-jobs/tests/docker/docker-compose.yml
  jobs/payment-jobs/tests/jobs/factory.py
  jobs/payment-jobs/tests/jobs/test_cfs_create_invoice_task.py
  pay-api/src/pay_api/models/routing_slip.py
  pay-api/src/pay_api/services/cfs_service.py
  pay-api/src/pay_api/services/internal_pay_service.py
  pay-api/tests/unit/api/test_refund.py
Labels: enhancement

#825 Cancel inv cfs
  docs/docs/PayBC Mocking/paybc-1.0.0.yaml
  jobs/payment-jobs/requirements.txt
  jobs/payment-jobs/requirements/prod.txt
  jobs/payment-jobs/tasks/cfs_create_invoice_task.py
  pay-api/src/pay_api/models/receipt.py
  pay-api/src/pay_api/services/cfs_service.py
  pay-api/src/pay_api/services/internal_pay_service.py
  pay-api/src/pay_api/utils/constants.py
  pay-api/tests/unit/api/test_refund.py
Labels: enhancement

#828 fixed cfs_party and rebuilt
  jobs/payment-jobs/config.py
  jobs/payment-jobs/requirements.txt
  jobs/payment-jobs/requirements/prod.txt
Labels: skip-changelog

#826 10048 : Changes for variable fee code, and new codes for CSO
  .github/workflows/events-listener-cd.yml
  .github/workflows/events-listener-ci.yml
  .github/workflows/pay-admin-cd.yml
  .github/workflows/pay-admin-ci.yml
  .github/workflows/payment-jobs-cd.yml
  .github/workflows/payment-jobs-ci.yml
  .github/workflows/payment-reconciliations-cd.yml
  .github/workflows/payment-reconciliations-ci.yml
  pay-api/migrations/versions/5d9997f7e649_variable_fee_code.py
  pay-api/src/pay_api/models/fee_schedule.py
  pay-api/src/pay_api/schemas/schemas/filing_type.json
  pay-api/src/pay_api/services/fee_schedule.py
  pay-api/src/pay_api/services/payment_service.py
  pay-api/tests/unit/api/test_payment_request.py
  queue_services/events-listener/src/events_listener/config.py
Labels: enhancement

#827 linking routing slip added
  jobs/payment-jobs/invoke_jobs.py
  jobs/payment-jobs/requirements/prod.txt
  jobs/payment-jobs/run_routing_slip_tasks.sh
  jobs/payment-jobs/tasks/routing_slip_task.py
  jobs/payment-jobs/tests/jobs/test_cfs_create_routing_slip_linking.py
  pay-api/requirements.txt
  pay-api/src/pay_api/services/auth.py
  pay-api/src/pay_api/services/cfs_service.py
  pay-api/src/pay_api/utils/constants.py
Labels: enhancement

#832 9251: Adding SP and GP FRREG filing types
  pay-api/migrations/versions/b899b44570d0_registration_filing_type.py
Labels: enhancement

#833 Reverting the migration for 9251
  pay-api/migrations/versions/b899b44570d0_registration_filing_type.py
Labels: skip-changelog

#831 few tweaks in cfs integration
  jobs/payment-jobs/requirements.txt
  jobs/payment-jobs/requirements/prod.txt
  jobs/payment-jobs/tasks/cfs_create_invoice_task.py
  pay-api/src/pay_api/services/cfs_service.py
Labels: skip-changelog

#835 Changes for statement of registration filing type codes
  pay-api/migrations/versions/b336780735dc_registration_filing_type.py
Labels: skip-changelog

#829 10048: Changes to authorization to restrict access based on product_code
  pay-api/src/pay_api/services/auth.py
  pay-api/tests/unit/api/test_payment_request.py
  pay-api/tests/unit/services/test_auth.py
  pay-api/tests/utilities/base_test.py
Labels: enhancement
