Repository bcgov/sbc-pay, pull requests merged in 2021-07, with the labels that each got.

#720 Fixing repo reference.
  jobs/payment-jobs/requirements.txt
  jobs/payment-jobs/requirements/prod.txt
Labels: skip-changelog

#721 Fix repo
  jobs/payment-jobs/requirements.txt
  jobs/payment-jobs/requirements/prod.txt
  jobs/payment-jobs/tasks/distribution_task.py
Labels: skip-changelog

#722 Display '-' for empty folio number.
  report-api/report-templates/invoice.html
  report-api/report-templates/payment_receipt.html
  report-api/report-templates/statement_report.html
Labels: bug

#723 Fee Accounting System - data model changes
  jobs/payment-jobs/requirements.txt
  jobs/payment-jobs/requirements/prod.txt
  jobs/payment-jobs/tasks/cfs_create_account_task.py
  jobs/payment-jobs/tasks/ejv_payment_task.py
  jobs/payment-jobs/tasks/statement_notification_task.py
  jobs/payment-jobs/tests/jobs/factory.py
  jobs/payment-jobs/tests/jobs/test_generate_statements.py
  pay-api/migrations/versions/4c3b8d61d200_remove_unused_table.py
  pay-api/migrations/versions/5b1ae231f7d2_fas_table.py
  pay-api/requirements.txt
  pay-api/src/pay_api/__init__.py
  pay-api/src/pay_api/exceptions/__init__.py
  pay-api/src/pay_api/models/__init__.py
  pay-api/src/pay_api/models/payment.py
  pay-api/src/pay_api/models/payment_account.py
  pay-api/src/pay_api/models/routing_slip.py
  pay-api/src/pay_api/models/routing_slip_status_code.py
  pay-api/src/pay_api/resources/fas/__init__.py
  pay-api/src/pay_api/resources/fas/routing_slip.py
  pay-api/src/pay_api/schemas/schemas/payment.json
  pay-api/src/pay_api/schemas/schemas/routing_slip.json
  pay-api/src/pay_api/services/fas/__init__.py
  pay-api/src/pay_api/services/fas/routing_slip.py
  pay-api/src/pay_api/services/pad_service.py
  pay-api/src/pay_api/services/paybc_service.py
  pay-api/src/pay_api/services/payment.py
  pay-api/src/pay_api/services/payment_account.py
  pay-api/src/pay_api/services/payment_transaction.py
  pay-api/src/pay_api/services/statement_recipients.py
  pay-api/src/pay_api/utils/enums.py
  pay-api/tests/unit/api/test_payment.py
  queue_services/payment-reconciliations/requirements.txt
  queue_services/payment-reconciliations/requirements/repo-libraries.txt
  queue_services/payment-reconciliations/src/reconciliations/ejv_reconciliations.py
  queue_services/payment-reconciliations/src/reconciliations/payment_reconciliations.py
  queue_services/payment-reconciliations/tests/integration/factory.py
  queue_services/payment-reconciliations/tests/integration/test_payment_reconciliations.py
Labels: enhancement

#724 Fix migration to work in dev
  pay-api/migrations/versions/4c3b8d61d200_remove_unused_table.py
Labels: skip-changelog

#726 Defaulting the error response if the error is not configured in DB.
  pay-api/src/pay_api/exceptions/__init__.py
Labels: bug

#728 Marking paymentDate as optional
  pay-api/src/pay_api/schemas/schemas/payment.json
  pay-api/src/pay_api/services/fas/routing_slip.py
Labels: skip-changelog

#727 Release/1.14.15 to main
  pay-api/src/pay_api/exceptions/__init__.py
Labels: skip-changelog

#729 8195 : Adding rush service fee code for vital stats
  pay-api/migrations/versions/c871202927f0_rush_fee_code.py
Labels: enhancement

#730 Adding PATCH endpoint for routing slips
  pay-api/src/pay_api/models/routing_slip.py
  pay-api/src/pay_api/resources/fas/routing_slip.py
  pay-api/src/pay_api/services/fas/routing_slip.py
  pay-api/src/pay_api/utils/enums.py
  pay-api/src/pay_api/utils/errors.py
  pay-api/tests/unit/api/fas/test_routing_slip.py
Labels: enhancement

#731 Adding fas roles to endpoints and cleaning up some unused config.
  pay-api/src/pay_api/config.py
  pay-api/src/pay_api/factory/payment_system_factory.py
  pay-api/src/pay_api/resources/fas/routing_slip.py
  pay-api/src/pay_api/utils/enums.py
  pay-api/tests/unit/api/fas/test_routing_slip.py
  pay-api/tests/unit/api/test_payment_request.py
  pay-api/tests/unit/services/test_distribution_code.py
  pay-api/tests/unit/services/test_payment_service.py
  pay-api/tests/unit/services/test_payment_transaction.py
Labels: enhancement

#732 Adding code endpoint support for routing slip status
  pay-api/migrations/versions/5b1ae231f7d2_fas_table.py
  pay-api/src/pay_api/services/code.py
  pay-api/src/pay_api/utils/enums.py
  pay-api/tests/unit/api/test_code.py
Labels: enhancement

#733 Adding On Hold status
  pay-api/migrations/versions/5b1ae231f7d2_fas_table.py
Labels: skip-changelog

#735 fix for reports trimming into one page
  report-api/report-templates/statement_report.html
Labels: bug

#737 Few more fixes on statements
  report-api/report-templates/statement_report.html
Labels: skip-changelog

#736 8054 : minItems validation for filing types schema
  pay-api/src/pay_api/schemas/schemas/filing_info.json
  pay-api/tests/unit/api/test_payment_request.py
Labels: bug

#739 added missing font-bold
  report-api/report-templates/statement_report.html
Labels: skip-changelog
