Repository bcgov/sbc-pay, pull requests merged in 2021-08, with the labels that each got.

#742 added missing font-bold
  report-api/report-templates/statement_report.html
Labels: skip-changelog

#740 Changes for populating receipt_number to payments table for all payment types
  pay-api/migrations/versions/03b2c7caed21_populate_receipt_number_payments.py
  pay-api/src/pay_api/services/payment.py
  pay-api/src/pay_api/services/payment_transaction.py
  pay-api/tests/unit/services/test_payment_transaction.py
Labels: bug

#741 Adding fas_create role to endpoint
  pay-api/src/pay_api/resources/fas/routing_slip.py
  pay-api/src/pay_api/utils/enums.py
  pay-api/tests/unit/api/fas/test_routing_slip.py
Labels: skip-changelog

#744 Changes for populating receipt_number to payments table for all payme…
  pay-api/migrations/versions/03b2c7caed21_populate_receipt_number_payments.py
Labels: skip-changelog

#743 8266: Adding a search endpoint for payment requests and including account details in response
  docs/docs/api_contract/pay-api-1.0.0.yaml
  pay-api/src/pay_api/models/invoice.py
  pay-api/src/pay_api/models/payment_account.py
  pay-api/src/pay_api/resources/invoice.py
  pay-api/src/pay_api/services/invoice.py
  pay-api/src/pay_api/services/statement_recipients.py
  pay-api/tests/unit/api/test_account.py
  pay-api/tests/unit/api/test_fee.py
  pay-api/tests/unit/api/test_payment_request.py
  pay-api/tests/unit/api/test_receipt.py
  pay-api/tests/utilities/base_test.py
Labels: enhancement

#745 routing slip Search addded
  pay-api/requirements.txt
  pay-api/src/pay_api/config.py
  pay-api/src/pay_api/models/__init__.py
  pay-api/src/pay_api/models/payment.py
  pay-api/src/pay_api/models/routing_slip.py
  pay-api/src/pay_api/resources/fas/routing_slip.py
  pay-api/src/pay_api/schemas/schemas/routing_slip_search_request.json
  pay-api/src/pay_api/services/fas/routing_slip.py
  pay-api/tests/unit/api/fas/test_routing_slip.py
Labels: enhancement

#746 Merge to release
  docs/docs/api_contract/pay-api-1.0.0.yaml
  pay-api/migrations/versions/03b2c7caed21_populate_receipt_number_payments.py
  pay-api/requirements.txt
  pay-api/src/pay_api/config.py
  pay-api/src/pay_api/models/__init__.py
  pay-api/src/pay_api/models/invoice.py
  pay-api/src/pay_api/models/payment.py
  pay-api/src/pay_api/models/payment_account.py
  pay-api/src/pay_api/models/routing_slip.py
  pay-api/src/pay_api/resources/fas/routing_slip.py
  pay-api/src/pay_api/resources/invoice.py
  pay-api/src/pay_api/schemas/schemas/routing_slip_search_request.json
  pay-api/src/pay_api/services/fas/routing_slip.py
  pay-api/src/pay_api/services/invoice.py
  pay-api/src/pay_api/services/payment.py
  pay-api/src/pay_api/services/payment_transaction.py
  pay-api/src/pay_api/services/statement_recipients.py
  pay-api/src/pay_api/utils/enums.py
  pay-api/tests/unit/api/fas/test_routing_slip.py
  pay-api/tests/unit/api/test_account.py
  pay-api/tests/unit/api/test_fee.py
  pay-api/tests/unit/api/test_payment_request.py
  pay-api/tests/unit/api/test_receipt.py
  pay-api/tests/unit/services/test_payment_transaction.py
  pay-api/tests/utilities/base_test.py
Labels: skip-changelog

#748 data model for RS parent id
  pay-api/migrations/versions/c12b11093a87_parent_routing_slip.py
  pay-api/src/pay_api/models/routing_slip.py
Labels: enhancement

#747 changed initiator, date fields and return all
  pay-api/src/pay_api/models/routing_slip.py
  pay-api/src/pay_api/resources/fas/routing_slip.py
  pay-api/tests/unit/api/fas/test_routing_slip.py
  pay-api/tests/utilities/base_test.py
Labels: skip-changelog

#750 Added GET endpoint for linked RS and corrected parent rs to link to name
  pay-api/migrations/versions/10fa4c64f1da_parent_routing_slip_number.py
  pay-api/src/pay_api/models/routing_slip.py
  pay-api/src/pay_api/resources/__init__.py
  pay-api/src/pay_api/resources/fas/__init__.py
  pay-api/src/pay_api/resources/fas/routing_slip_links.py
  pay-api/src/pay_api/services/fas/routing_slip.py
Labels: enhancement

#749 misc tests including folio search and a model test
  pay-api/requirements.txt
  pay-api/requirements/dev.txt
  pay-api/src/pay_api/models/payment_account.py
  pay-api/tests/unit/api/fas/test_routing_slip.py
  pay-api/tests/unit/models/test_routing_slip.py
  pay-api/tests/utilities/base_test.py
Labels: skip-changelog

#751 Changes for daily reports
  pay-api/src/pay_api/models/routing_slip.py
  pay-api/src/pay_api/resources/fas/routing_slip.py
  pay-api/src/pay_api/resources/fee.py
  pay-api/src/pay_api/schemas/schemas/routing_slip_search_request.json
  pay-api/src/pay_api/services/fas/routing_slip.py
  pay-api/src/pay_api/services/statement.py
  pay-api/src/pay_api/utils/constants.py
  pay-api/src/pay_api/utils/util.py
  pay-api/tests/unit/api/fas/test_routing_slip.py
  pay-api/tests/unit/api/test_statement_settings.py
  pay-api/tests/unit/services/test_statement_settings.py
  pay-api/tests/utilities/base_test.py
  report-api/report-templates/routing_slip_report.html
  report-api/src/api/services/report_service.py
  report-api/tests/unit/api/test_reports.py
Labels: enhancement

#752 adding linking post
  pay-api/migrations/versions/10fa4c64f1da_parent_routing_slip_number.py
  pay-api/migrations/versions/c12b11093a87_parent_routing_slip.py
  pay-api/migrations/versions/f841ac43e15e_new_rs_status_and_error_codes.py
  pay-api/src/pay_api/models/routing_slip.py
  pay-api/src/pay_api/resources/__init__.py
  pay-api/src/pay_api/resources/fas/__init__.py
  pay-api/src/pay_api/resources/fas/routing_slip.py
  pay-api/src/pay_api/resources/fas/routing_slip_links.py
  pay-api/src/pay_api/schemas/schemas/routing_slip_link_request.json
  pay-api/src/pay_api/services/fas/routing_slip.py
  pay-api/src/pay_api/utils/enums.py
  pay-api/src/pay_api/utils/errors.py
  pay-api/tests/unit/api/fas/test_routing_slip.py
  pay-api/tests/unit/services/test_routing_slip_service.py
  pay-api/tests/utilities/base_test.py
Labels: enhancement

#756 Clean up , fixed child as parent bug for routing slip linking
  pay-api/migrations/versions/f841ac43e15e_new_rs_status_and_error_codes.py
  pay-api/requirements.txt
  pay-api/setup.cfg
  pay-api/src/pay_api/schemas/utils.py
  pay-api/src/pay_api/services/fas/routing_slip.py
  pay-api/src/pay_api/services/payment.py
  pay-api/src/pay_api/utils/errors.py
  pay-api/tests/conftest.py
  pay-api/tests/unit/api/fas/test_routing_slip.py
Labels: enhancement

#757 self linking and parent transcation fix
  pay-api/migrations/versions/f841ac43e15e_new_rs_status_and_error_codes.py
  pay-api/src/pay_api/services/fas/routing_slip.py
  pay-api/src/pay_api/utils/errors.py
  pay-api/tests/unit/api/fas/test_routing_slip.py
Labels: skip-changelog

#755 8390: Adding message and error codes for refund
  docs/docs/PayBC Mocking/paybc-1.0.0.yaml
  pay-api/migrations/versions/9543cbcb8b79_refund_error_messages.py
  pay-api/src/pay_api/resources/refund.py
  pay-api/src/pay_api/services/refund.py
  pay-api/src/pay_api/utils/constants.py
  pay-api/src/pay_api/utils/errors.py
  pay-api/tests/docker/docker-compose.yml
  pay-api/tests/unit/api/test_refund.py
  pay-api/tests/unit/services/test_refund.py
Labels: enhancement

#761 Staff does daily reconciliation#7821 | pdf style
  report-api/report-templates/routing_slip_report.html
Labels: skip-changelog

#762 added corp type and filing type to fee schedules endpoint
  pay-api/src/pay_api/models/fee_schedule.py
  pay-api/src/pay_api/resources/fee_schedule.py
  pay-api/src/pay_api/services/fee_schedule.py
  pay-api/tests/unit/api/test_fee_schedule.py
Labels: enhancement
