Repository bcgov/sbc-pay, pull requests merged in 2021-09, with the labels that each got.

#763 routing slip payment changes
  pay-api/requirements.txt
  pay-api/src/pay_api/schemas/schemas/business_info.json
  pay-api/src/pay_api/services/auth.py
  pay-api/src/pay_api/services/internal_pay_service.py
  pay-api/src/pay_api/utils/errors.py
  pay-api/tests/unit/api/test_payment_request.py
Labels: enhancement, skip-changelog

#765 Fixing format in CSV as per comment in #8280
  pay-api/src/pay_api/services/payment.py
Labels: enhancement

#764 auth_response None
  pay-api/src/pay_api/services/auth.py
  pay-api/tests/unit/api/test_payment_request.py
  pay-api/tests/utilities/base_test.py
Labels: skip-changelog

#770 Requirement and lint updates
  bcol-api/requirements.txt
  bcol-api/src/bcol_api/__init__.py
  bcol-api/src/bcol_api/exceptions/__init__.py
  bcol-api/src/bcol_api/schemas/utils.py
  jobs/payment-jobs/requirements.txt
  jobs/payment-jobs/tasks/common/cgi_ejv.py
  jobs/payment-jobs/tasks/ejv_partner_distribution_task.py
  jobs/payment-jobs/tasks/statement_task.py
  queue_services/events-listener/requirements.txt
  queue_services/payment-reconciliations/requirements.txt
  report-api/requirements.txt
Labels: skip-changelog

#771 PDF header and footer
  report-api/report-templates/routing_slip_report.html
Labels: bug

#772 Updating requirements to fix report-api
  report-api/requirements.txt
Labels: skip-changelog

#773 Adding processingFees to the schema, needs to be removed later
  docs/docs/api_contract/pay-api-1.0.0.yaml
Labels: skip-changelog

#774 Fixes on reconciliation
  jobs/payment-jobs/requirements.txt
  jobs/payment-jobs/tasks/cfs_create_invoice_task.py
  pay-api/src/pay_api/services/bcol_service.py
  queue_services/payment-reconciliations/src/reconciliations/payment_reconciliations.py
Labels: bug

#775 Changes for Rural Property Tax
  pay-api/migrations/versions/609b98d87a72_rpt.py
  pay-api/src/pay_api/services/auth.py
Labels: enhancement

#776 Adding PPR filing types, and fixing lint errors
  pay-api/migrations/versions/44bd57ece7b0_ppr_filing_types.py
  pay-api/src/pay_api/__init__.py
  pay-api/src/pay_api/config.py
  pay-api/src/pay_api/factory/payment_system_factory.py
  pay-api/src/pay_api/models/invoice.py
  pay-api/src/pay_api/models/payment_line_item.py
  pay-api/src/pay_api/resources/account.py
  pay-api/src/pay_api/resources/fas/routing_slip.py
  pay-api/src/pay_api/resources/invoice.py
  pay-api/src/pay_api/resources/invoice_receipt.py
  pay-api/src/pay_api/services/base_payment_system.py
  pay-api/src/pay_api/services/cfs_service.py
  pay-api/src/pay_api/services/distribution_code.py
  pay-api/src/pay_api/services/oauth_service.py
  pay-api/src/pay_api/services/paybc_service.py
  pay-api/src/pay_api/services/payment.py
  pay-api/src/pay_api/services/payment_account.py
  pay-api/src/pay_api/services/payment_line_item.py
  pay-api/src/pay_api/services/payment_service.py
  pay-api/src/pay_api/services/receipt.py
  pay-api/src/pay_api/utils/logging.py
Labels: enhancement

#777 9206: CSO Codes
  pay-api/migrations/versions/643790dd3334_cso.py
Labels: enhancement

#779 fix for routing slip not creating invoice_reference
  pay-api/src/pay_api/services/internal_pay_service.py
Labels: bug
