Repository bcgov/sbc-pay, pull requests merged in 2021-01, with the labels that each got.

#514 Generate and Download Invoice - Online Banking#5799
  report-api/report-templates/invoice.html
Labels: enhancement

#515 Generate and Download Invoice - Online Banking#5799
  report-api/report-templates/invoice.html
Labels: enhancement

#517 Generate and Download Invoice - Online Banking#5799
  report-api/report-templates/invoice.html
Labels: bug

#516 Miscellaneous fixes for invoice PDF and NSF bank update
  pay-api/src/pay_api/services/fee_schedule.py
  pay-api/src/pay_api/services/invoice.py
  pay-api/src/pay_api/services/pad_service.py
Labels: bug

#520 defaulting of pad_tos_accepted_date is removed
  pay-api/src/pay_api/services/payment_account.py
  pay-api/tests/unit/services/test_payment_account.py
Labels: bug

#529 Feature/download invoice
  report-api/report-templates/invoice.html
Labels: enhancement

#531 Dev to Test
  report-api/report-templates/invoice.html
Labels: skip-changelog

#530 Changes for 5860, to throw error if account doesn't have permissions.
  pay-api/src/pay_api/resources/invoice.py
  pay-api/src/pay_api/services/auth.py
  pay-api/src/pay_api/utils/user_context.py
  pay-api/tests/docker/docker-compose.yml
  pay-api/tests/utilities/base_test.py
Labels: bug

#533 view roled staff should be able to see payment info
  pay-api/src/pay_api/resources/account.py
  pay-api/tests/docker/docker-compose.yml
Labels: bug

#536 Changes to include calculated fields to invoice response
  pay-api/migrations/versions/41f76e6c82eb_online_banking_flags.py
  pay-api/src/pay_api/__init__.py
  pay-api/src/pay_api/models/corp_type.py
  pay-api/src/pay_api/models/invoice.py
  pay-api/src/pay_api/resources/invoice.py
  pay-api/src/pay_api/services/code.py
  pay-api/src/pay_api/services/invoice.py
  pay-api/src/pay_api/services/pad_service.py
  pay-api/src/pay_api/services/payment_account.py
  pay-api/src/pay_api/services/payment_service.py
  pay-api/src/pay_api/services/payment_transaction.py
  pay-api/src/pay_api/services/queue_publisher.py
  pay-api/src/pay_api/utils/enums.py
  pay-api/tests/conftest.py
  pay-api/tests/unit/api/test_payment_request.py
  pay-api/tests/utilities/base_test.py
  queue_services/payment-reconciliations/src/reconciliations/worker.py
Labels: enhancement

#535 returning message as a list incase of error scenarios
  pay-api/src/pay_api/services/cfs_service.py
Labels: bug

#538 Dev to test
  pay-api/migrations/versions/41f76e6c82eb_online_banking_flags.py
  pay-api/src/pay_api/__init__.py
  pay-api/src/pay_api/models/corp_type.py
  pay-api/src/pay_api/models/invoice.py
  pay-api/src/pay_api/resources/invoice.py
  pay-api/src/pay_api/services/cfs_service.py
  pay-api/src/pay_api/services/code.py
  pay-api/src/pay_api/services/invoice.py
  pay-api/src/pay_api/services/pad_service.py
  pay-api/src/pay_api/services/payment_account.py
  pay-api/src/pay_api/services/payment_service.py
  pay-api/src/pay_api/services/payment_transaction.py
  pay-api/src/pay_api/services/queue_publisher.py
  pay-api/src/pay_api/utils/enums.py
  pay-api/tests/conftest.py
  pay-api/tests/unit/api/test_payment_request.py
  pay-api/tests/utilities/base_test.py
  queue_services/payment-reconciliations/src/reconciliations/worker.py
Labels: skip-changelog

#537 5723: Changes for pre-padding bank transit and institution number
  docs/docs/PayBC Mocking/paybc-1.0.0.yaml
  pay-api/src/pay_api/services/cfs_service.py
  pay-api/tests/docker/docker-compose.yml
  pay-api/tests/unit/api/test_bank_accounts.py
Labels: enhancement

#539 Clean up config values and vaults.json file.
  .github/workflows/bcol-api-cd.yml
  .github/workflows/events-listener-cd.yml
  .github/workflows/ftp-poller-cd.yml
  .github/workflows/ftp-poller-ci.yml
  .github/workflows/pay-api-cd.yml
  .github/workflows/pay-api-ci.yml
  .github/workflows/payment-jobs-cd.yml
  .github/workflows/payment-jobs-ci.yml
  .github/workflows/payment-reconciliations-cd.yml
  .github/workflows/report-api-cd.yml
  bcol-api/devops/vaults.json
  bcol-api/jenkins/dev.groovy
  bcol-api/jenkins/prod.groovy
  bcol-api/jenkins/test.groovy
  bcol-api/requirements.txt
  bcol-api/src/bcol_api/services/bcol_payment.py
  bcol-api/src/bcol_api/services/bcol_profile.py
  jobs/ftp-poller/config.py
  jobs/ftp-poller/devops/vaults.json
  jobs/ftp-poller/tasks/poll_ftp_task.py
  jobs/ftp-poller/tests/jobs/conftest.py
  jobs/payment-jobs/config.py
  jobs/payment-jobs/devops/vaults.json
  jobs/payment-jobs/requirements.txt
  jobs/payment-jobs/tasks/cfs_create_account_task.py
  jobs/payment-jobs/tasks/cfs_create_invoice_task.py
  jobs/payment-jobs/tasks/statement_notification_task.py
  jobs/payment-jobs/tests/jobs/conftest.py
  jobs/payment-jobs/tests/jobs/test_cfs_create_account_task.py
  pay-api/devops/vaults.json
  pay-api/jenkins/dev.groovy
  pay-api/jenkins/prod.groovy
  pay-api/jenkins/test.groovy
  pay-api/src/pay_api/config.py
  queue_services/events-listener/coverage.xml
  queue_services/events-listener/devops/vaults.json
  queue_services/events-listener/jenkins/dev.groovy
  queue_services/events-listener/jenkins/prod.groovy
  queue_services/events-listener/jenkins/test.groovy
  queue_services/events-listener/requirements.txt
  queue_services/events-listener/tests/integration/__init__.py
  queue_services/payment-reconciliations/devops/vaults.json
  queue_services/payment-reconciliations/jenkins/dev.groovy
  queue_services/payment-reconciliations/jenkins/prod.groovy
  queue_services/payment-reconciliations/jenkins/test.groovy
  queue_services/payment-reconciliations/requirements.txt
  report-api/devops/vaults.json
  report-api/jenkins/dev.groovy
  report-api/jenkins/prod.groovy
  report-api/jenkins/test.groovy
Labels: devops

#541 Fixed the URL path setting issue.
  pay-api/src/pay_api/config.py
Labels: devops

#542 Merge to test
  .github/workflows/bcol-api-cd.yml
  .github/workflows/events-listener-cd.yml
  .github/workflows/ftp-poller-cd.yml
  .github/workflows/ftp-poller-ci.yml
  .github/workflows/pay-api-cd.yml
  .github/workflows/pay-api-ci.yml
  .github/workflows/payment-jobs-cd.yml
  .github/workflows/payment-jobs-ci.yml
  .github/workflows/payment-reconciliations-cd.yml
  .github/workflows/report-api-cd.yml
  bcol-api/devops/vaults.json
  bcol-api/jenkins/dev.groovy
  bcol-api/jenkins/prod.groovy
  bcol-api/jenkins/test.groovy
  bcol-api/requirements.txt
  bcol-api/src/bcol_api/services/bcol_payment.py
  bcol-api/src/bcol_api/services/bcol_profile.py
  docs/docs/PayBC Mocking/paybc-1.0.0.yaml
  jobs/ftp-poller/config.py
  jobs/ftp-poller/devops/vaults.json
  jobs/ftp-poller/tasks/poll_ftp_task.py
  jobs/ftp-poller/tests/jobs/conftest.py
  jobs/payment-jobs/config.py
  jobs/payment-jobs/devops/vaults.json
  jobs/payment-jobs/requirements.txt
  jobs/payment-jobs/tasks/cfs_create_account_task.py
  jobs/payment-jobs/tasks/cfs_create_invoice_task.py
  jobs/payment-jobs/tasks/statement_notification_task.py
  jobs/payment-jobs/tests/jobs/conftest.py
  jobs/payment-jobs/tests/jobs/test_cfs_create_account_task.py
  pay-api/devops/vaults.json
  pay-api/jenkins/dev.groovy
  pay-api/jenkins/prod.groovy
  pay-api/jenkins/test.groovy
  pay-api/src/pay_api/config.py
  pay-api/src/pay_api/services/cfs_service.py
  pay-api/tests/docker/docker-compose.yml
  pay-api/tests/unit/api/test_bank_accounts.py
  queue_services/events-listener/coverage.xml
  queue_services/events-listener/devops/vaults.json
  queue_services/events-listener/jenkins/dev.groovy
  queue_services/events-listener/jenkins/prod.groovy
  queue_services/events-listener/jenkins/test.groovy
  queue_services/events-listener/requirements.txt
  queue_services/events-listener/tests/integration/__init__.py
  queue_services/payment-reconciliations/devops/vaults.json
  queue_services/payment-reconciliations/jenkins/dev.groovy
  queue_services/payment-reconciliations/jenkins/prod.groovy
  queue_services/payment-reconciliations/jenkins/test.groovy
  queue_services/payment-reconciliations/requirements.txt
  report-api/devops/vaults.json
  report-api/jenkins/dev.groovy
  report-api/jenkins/prod.groovy
  report-api/jenkins/test.groovy
  report-api/requirements.txt
Labels: devops

#543 Changes for sending emails for online banking payments.
  queue_services/payment-reconciliations/src/reconciliations/worker.py
  queue_services/payment-reconciliations/tests/conftest.py
Labels: enhancement

#540 fine grained roles from account statements
  pay-api/src/pay_api/resources/account_statements_notifications.py
  pay-api/src/pay_api/resources/account_statements_settings.py
  pay-api/src/pay_api/utils/constants.py
  pay-api/tests/docker/docker-compose.yml
Labels: enhancement

#544 Dev to Test
  pay-api/src/pay_api/resources/account_statements_notifications.py
  pay-api/src/pay_api/resources/account_statements_settings.py
  pay-api/src/pay_api/utils/constants.py
  pay-api/tests/docker/docker-compose.yml
  queue_services/payment-reconciliations/src/reconciliations/worker.py
  queue_services/payment-reconciliations/tests/conftest.py
Labels: skip-changelog

#545 Changes for sending emails for online banking payments.
  queue_services/payment-reconciliations/src/reconciliations/worker.py
Labels: skip-changelog

#547 Name Request fee description update
  pay-api/migrations/versions/f1ed292af77f_name_req_description_changes.py
Labels: skip-changelog

#546 Dev to Test
  pay-api/migrations/versions/f1ed292af77f_name_req_description_changes.py
  queue_services/payment-reconciliations/src/reconciliations/worker.py
Labels: skip-changelog

#548 Changing append to extend to fix issues with multiple line items
  jobs/payment-jobs/tasks/cfs_create_invoice_task.py
Labels: skip-changelog

#549 Fixing issue with auth api config value
  jobs/payment-jobs/config.py
Labels: skip-changelog

#550 Dev to Test
  jobs/payment-jobs/config.py
  jobs/payment-jobs/tasks/cfs_create_invoice_task.py
Labels: skip-changelog

#552 Adding an event for mailer if PAD account creation fails
  jobs/payment-jobs/requirements.txt
  jobs/payment-jobs/tasks/cfs_create_account_task.py
Labels: enhancement

#551 Changes for encrypting bank account number
  pay-api/migrations/versions/90afcc0d6d9f_encrypt_bank_account.py
  pay-api/requirements.txt
  pay-api/requirements/prod.txt
  pay-api/src/pay_api/config.py
  pay-api/src/pay_api/models/cfs_account.py
  pay-api/src/pay_api/services/payment_account.py
Labels: enhancement

#553 Fixing permissions so that staff can get the failed payment statuses
  pay-api/src/pay_api/resources/payment.py
Labels: bug

#556 Changes for adding encryption keys to job
  jobs/payment-jobs/devops/vaults.json
  pay-api/devops/vaults.json
  queue_services/payment-reconciliations/devops/vaults.json
Labels: devops

#557 Changes for adding encryption keys to job
  jobs/payment-jobs/config.py
  jobs/payment-jobs/tasks/cfs_create_account_task.py
  queue_services/payment-reconciliations/src/reconciliations/config.py
Labels: skip-changelog

#558 rename tables added
  pay-api/migrations/versions/b6e28faea978_rename_tables_to_plurals.py
  pay-api/src/pay_api/models/cfs_account.py
  pay-api/src/pay_api/models/cfs_account_status_code.py
  pay-api/src/pay_api/models/corp_type.py
  pay-api/src/pay_api/models/credit.py
  pay-api/src/pay_api/models/daily_payment_batch.py
  pay-api/src/pay_api/models/daily_payment_batch_link.py
  pay-api/src/pay_api/models/distribution_code.py
  pay-api/src/pay_api/models/ejv_batch.py
  pay-api/src/pay_api/models/ejv_batch_link.py
  pay-api/src/pay_api/models/error_code.py
  pay-api/src/pay_api/models/fee_code.py
  pay-api/src/pay_api/models/fee_schedule.py
  pay-api/src/pay_api/models/filing_type.py
  pay-api/src/pay_api/models/invoice.py
  pay-api/src/pay_api/models/invoice_batch.py
  pay-api/src/pay_api/models/invoice_batch_link.py
  pay-api/src/pay_api/models/invoice_reference.py
  pay-api/src/pay_api/models/invoice_reference_status_code.py
  pay-api/src/pay_api/models/invoice_status_code.py
  pay-api/src/pay_api/models/line_item_status_code.py
  pay-api/src/pay_api/models/notification_status_code.py
  pay-api/src/pay_api/models/payment.py
  pay-api/src/pay_api/models/payment_account.py
  pay-api/src/pay_api/models/payment_line_item.py
  pay-api/src/pay_api/models/payment_method.py
  pay-api/src/pay_api/models/payment_status_code.py
  pay-api/src/pay_api/models/payment_system.py
  pay-api/src/pay_api/models/payment_transaction.py
  pay-api/src/pay_api/models/receipt.py
  pay-api/src/pay_api/models/refund.py
  pay-api/src/pay_api/models/statement.py
  pay-api/src/pay_api/models/statement_invoices.py
  pay-api/src/pay_api/models/statement_recipients.py
  pay-api/src/pay_api/models/statement_settings.py
  pay-api/src/pay_api/models/transaction_status_code.py
Labels: enhancement

#555 Changes for releasing records if the account have credit.
  pay-api/src/pay_api/resources/invoice.py
  pay-api/src/pay_api/services/base_payment_system.py
  pay-api/src/pay_api/services/online_banking_service.py
  pay-api/src/pay_api/services/pad_service.py
  pay-api/src/pay_api/services/paybc_service.py
  pay-api/src/pay_api/services/payment_account.py
  pay-api/src/pay_api/services/payment_service.py
  pay-api/tests/unit/api/test_payment_request.py
Labels: enhancement

#560 Changes for adding encryption keys to job
  jobs/payment-jobs/tasks/cfs_create_account_task.py
Labels: skip-changelog

#561 mail added for pending payment
  jobs/payment-jobs/config.py
  jobs/payment-jobs/invoke_jobs.py
  jobs/payment-jobs/run_notify_unpaid_invoices.sh
  jobs/payment-jobs/tasks/unpaid_invoice_notify_task.py
  jobs/payment-jobs/tests/jobs/factory.py
  jobs/payment-jobs/tests/jobs/test_unpaid_invoice_notifytask.py
Labels: enhancement

#563 added payment-job vault section
  jobs/payment-jobs/devops/vaults.json
Labels: skip-changelog

#565 Updating paid amount to invoice incase if it's a partial credit
  pay-api/src/pay_api/services/payment_service.py
Labels: enhancement
