Repository bcgov/sbc-pay, pull requests merged in 2021-06, with the labels that each got.

#713 Added RPPR product
  pay-api/migrations/versions/9c8a93ba9da2_restricted_ppr_fee_codes.py
  pay-api/tests/docker/docker-compose.yml
Labels: enhancement

#714 7786: Adding incorporation filing types
  pay-api/migrations/versions/c67213f860ea_incorporation_fee_codes.py
Labels: enhancement

#715 Fixing build error and changing the repo branch to main.
  jobs/payment-jobs/tasks/stale_payment_task.py
  jobs/payment-jobs/tests/docker/docker-compose.yml
  queue_services/payment-reconciliations/requirements.txt
  queue_services/payment-reconciliations/requirements/repo-libraries.txt
  queue_services/payment-reconciliations/tests/docker-compose.yml
Labels: skip-changelog

#716 Rename CCC to CC
  pay-api/migrations/versions/e67a61c01cbb_rename_ccc_to_cc.py
Labels: skip-changelog

#717 Changes to receipt pdf. Excluding NR in adding dynamic details field.
  pay-api/src/pay_api/models/invoice.py
  report-api/report-templates/payment_receipt.html
  report-api/src/api/services/report_service.py
Labels: enhancement

#719 8007: Fixing bcol applied charge error
  bcol-api/src/bcol_api/services/bcol_payment.py
  pay-api/migrations/versions/099ba5cf19a3_bcol_invalid_account_error.py
  pay-api/src/pay_api/utils/errors.py
Labels: bug

#718 Changes for account delete
  jobs/payment-jobs/requirements/prod.txt
  jobs/payment-jobs/tasks/cfs_create_invoice_task.py
  pay-api/src/pay_api/config.py
  pay-api/src/pay_api/models/cfs_account.py
  pay-api/src/pay_api/models/invoice.py
  pay-api/src/pay_api/models/payment_account.py
  pay-api/src/pay_api/resources/account.py
  pay-api/src/pay_api/services/cfs_service.py
  pay-api/src/pay_api/services/payment.py
  pay-api/src/pay_api/services/payment_account.py
  pay-api/src/pay_api/utils/errors.py
  pay-api/src/pay_api/utils/util.py
  pay-api/tests/unit/api/test_account.py
  pay-api/tests/unit/services/test_payment_account.py
  pay-api/tests/utilities/base_test.py
Labels: enhancement
