Repository bcgov/sbc-pay, pull requests merged in 2021-02, with the labels that each got.

#566 correcting message type
  jobs/payment-jobs/tasks/unpaid_invoice_notify_task.py
Labels: skip-changelog

#562 Changes for splitting GL codes into more scalable structure.
  pay-api/migrations/versions/6f0fe9f23d8c_distribution_code_changes.py
  pay-api/src/pay_api/models/__init__.py
  pay-api/src/pay_api/models/daily_payment_batch.py
  pay-api/src/pay_api/models/disbursement_status_code.py
  pay-api/src/pay_api/models/distribution_code.py
  pay-api/src/pay_api/models/ejv_batch.py
  pay-api/src/pay_api/models/ejv_file.py
  pay-api/src/pay_api/models/ejv_invoice_link.py
  pay-api/src/pay_api/models/invoice.py
  pay-api/src/pay_api/schemas/schemas/distribution_code.json
  pay-api/src/pay_api/services/cfs_service.py
  pay-api/src/pay_api/services/direct_pay_service.py
  pay-api/src/pay_api/services/distribution_code.py
  pay-api/tests/docker/docker-compose.yml
  pay-api/tests/unit/api/test_distributions.py
  pay-api/tests/unit/api/test_payment_request.py
  pay-api/tests/unit/services/test_direct_pay_service.py
  pay-api/tests/unit/services/test_distribution_code.py
  pay-api/tests/utilities/base_test.py
Labels: enhancement

#570 6072-Fix GHA issue with reconciliations
  .github/workflows/payment-reconciliations-ci.yml
  queue_services/payment-reconciliations/requirements.txt
  queue_services/payment-reconciliations/tests/conftest.py
Labels: bug

#573 Dev to Test
  .github/workflows/payment-reconciliations-ci.yml
  pay-api/migrations/versions/6f0fe9f23d8c_distribution_code_changes.py
  pay-api/src/pay_api/models/__init__.py
  pay-api/src/pay_api/models/daily_payment_batch.py
  pay-api/src/pay_api/models/disbursement_status_code.py
  pay-api/src/pay_api/models/distribution_code.py
  pay-api/src/pay_api/models/ejv_batch.py
  pay-api/src/pay_api/models/ejv_file.py
  pay-api/src/pay_api/models/ejv_invoice_link.py
  pay-api/src/pay_api/models/invoice.py
  pay-api/src/pay_api/schemas/schemas/distribution_code.json
  pay-api/src/pay_api/services/cfs_service.py
  pay-api/src/pay_api/services/direct_pay_service.py
  pay-api/src/pay_api/services/distribution_code.py
  pay-api/tests/docker/docker-compose.yml
  pay-api/tests/unit/api/test_distributions.py
  pay-api/tests/unit/api/test_payment_request.py
  pay-api/tests/unit/services/test_direct_pay_service.py
  pay-api/tests/unit/services/test_distribution_code.py
  pay-api/tests/utilities/base_test.py
  queue_services/payment-reconciliations/requirements.txt
  queue_services/payment-reconciliations/tests/conftest.py
Labels: skip-changelog

#571 Amount displayed in OB pending amount email
  jobs/payment-jobs/tasks/unpaid_invoice_notify_task.py
  jobs/payment-jobs/tests/jobs/test_unpaid_invoice_notifytask.py
Labels: bug

#572 New job for calling CGI added (#7)
  jobs/ftp-poller/config.py
  jobs/ftp-poller/invoke_jobs.py
  jobs/ftp-poller/requirements.txt
  jobs/ftp-poller/services/sftp.py
  jobs/ftp-poller/tasks/cas_poller_ftp.py
  jobs/ftp-poller/tasks/cgi_feeder_poller_task.py
  jobs/ftp-poller/tasks/poll_ftp_task.py
  jobs/ftp-poller/utils/constants.py
  jobs/ftp-poller/utils/minio.py
  jobs/ftp-poller/utils/utils.py
Labels: enhancement

#577 Changes for uploading JV and TRG file to FTP
  .gitignore
  jobs/payment-jobs/config.py
  jobs/payment-jobs/devops/vaults.json
  jobs/payment-jobs/openshift/payment-job-deploy.json
  jobs/payment-jobs/requirements.txt
  jobs/payment-jobs/requirements/prod.txt
  jobs/payment-jobs/tasks/cgi_ejv_task.py
  jobs/payment-jobs/tests/docker/docker-compose.yml
  jobs/payment-jobs/tests/jobs/conftest.py
  jobs/payment-jobs/tests/jobs/test_cgi_ejv_task.py
  jobs/payment-jobs/utils/sftp.py
  queue_services/payment-reconciliations/src/reconciliations/config.py
Labels: enhancement

#575 Changes to design diagram for JV
  docs/docs/architecture/Acccounts-Pay.gliffy
  docs/docs/architecture/Acccounts-Pay.png
Labels: documentation

#581 Dev to test
  .gitignore
  docs/docs/architecture/Acccounts-Pay.gliffy
  docs/docs/architecture/Acccounts-Pay.png
  jobs/payment-jobs/config.py
  jobs/payment-jobs/devops/vaults.json
  jobs/payment-jobs/openshift/payment-job-deploy.json
  jobs/payment-jobs/requirements.txt
  jobs/payment-jobs/requirements/prod.txt
  jobs/payment-jobs/tasks/cgi_ejv_task.py
  jobs/payment-jobs/tests/docker/docker-compose.yml
  jobs/payment-jobs/tests/jobs/conftest.py
  jobs/payment-jobs/tests/jobs/test_cgi_ejv_task.py
  jobs/payment-jobs/utils/sftp.py
  queue_services/payment-reconciliations/src/reconciliations/config.py
Labels: skip-changelog

#579 Changes for refactoring reconciliations to include JV reconciliations
  queue_services/payment-reconciliations/requirements.txt
  queue_services/payment-reconciliations/requirements/prod.txt
  queue_services/payment-reconciliations/src/reconciliations/payment_reconciliations.py
  queue_services/payment-reconciliations/src/reconciliations/worker.py
Labels: skip-changelog

#582 Added missing sh file
  jobs/ftp-poller/invoke_jobs.py
  jobs/ftp-poller/run_cgi_feeder_poller.sh
Labels: skip-changelog

#580 file name changed to reflect business day
  jobs/payment-jobs/config.py
  jobs/payment-jobs/requirements.txt
  jobs/payment-jobs/requirements/prod.txt
  jobs/payment-jobs/tasks/cgi_ejv_task.py
  pay-api/src/pay_api/config.py
  pay-api/src/pay_api/utils/util.py
  pay-api/tests/unit/utils/test_util.py
Labels: enhancement

#587 Changing PAD invoice status to COMPLETED as an interim fix.
  pay-api/src/pay_api/models/invoice.py
  pay-api/tests/unit/services/test_payment_service.py
Labels: skip-changelog

#588 Changing PAD invoice status to COMPLETED as an interim fix.
  pay-api/src/pay_api/models/invoice.py
  pay-api/tests/unit/services/test_payment_service.py
Labels: skip-changelog

#586 Fix for receipt for pending pad payments
  pay-api/src/pay_api/services/receipt.py
  pay-api/tests/unit/api/test_receipt.py
Labels: enhancement

#585 Handle receipt for PAD (not yet PAID) invoices | template changes
  report-api/report-templates/payment_receipt.html
Labels: enhancement

#584 Added reason code to DB and a mapping to reflect in UI
  pay-api/migrations/versions/1803b51e5689_added_pay_system_reason_code.py
  pay-api/src/pay_api/models/payment_transaction.py
  pay-api/src/pay_api/services/base_payment_system.py
  pay-api/src/pay_api/services/direct_pay_service.py
  pay-api/src/pay_api/services/payment_transaction.py
  pay-api/src/pay_api/utils/paybc_transaction_error_message.py
  pay-api/tests/unit/api/test_transaction.py
Labels: enhancement

#592 Added paymentMethodCode to be passed to report api
  pay-api/src/pay_api/services/receipt.py
  report-api/report-templates/payment_receipt.html
Labels: skip-changelog

#590 Changes for listening and parsing JV response
  .gitignore
  jobs/ftp-poller/utils/constants.py
  jobs/payment-jobs/requirements.txt
  jobs/payment-jobs/requirements/prod.txt
  jobs/payment-jobs/tasks/cgi_ejv_task.py
  pay-api/migrations/versions/073b9f59b447_jv_feedback_changes.py
  pay-api/src/pay_api/models/distribution_code.py
  pay-api/src/pay_api/models/ejv_file.py
  pay-api/src/pay_api/models/ejv_header.py
  pay-api/src/pay_api/models/ejv_invoice_link.py
  pay-api/src/pay_api/services/distribution_code.py
  queue_services/payment-reconciliations/q_cli.py
  queue_services/payment-reconciliations/requirements.txt
  queue_services/payment-reconciliations/requirements/repo-libraries.txt
  queue_services/payment-reconciliations/src/reconciliations/ejv_reconciliations.py
  queue_services/payment-reconciliations/src/reconciliations/worker.py
  queue_services/payment-reconciliations/tests/integration/factory.py
  queue_services/payment-reconciliations/tests/integration/test_ejv_reconciliations.py
  queue_services/payment-reconciliations/tests/integration/utils.py
Labels: enhancement

#596 Fix poller
  jobs/ftp-poller/run_cgi_feeder_poller.sh
  jobs/ftp-poller/run_ftp_poller.sh
  jobs/ftp-poller/tasks/cgi_feeder_poller_task.py
Labels: enhancement

#595 Dev to Test
  .gitignore
  jobs/ftp-poller/run_cgi_feeder_poller.sh
  jobs/ftp-poller/run_ftp_poller.sh
  jobs/ftp-poller/tasks/cgi_feeder_poller_task.py
  jobs/ftp-poller/utils/constants.py
  jobs/payment-jobs/requirements.txt
  jobs/payment-jobs/requirements/prod.txt
  jobs/payment-jobs/tasks/cgi_ejv_task.py
  pay-api/migrations/versions/073b9f59b447_jv_feedback_changes.py
  pay-api/src/pay_api/models/distribution_code.py
  pay-api/src/pay_api/models/ejv_file.py
  pay-api/src/pay_api/models/ejv_header.py
  pay-api/src/pay_api/models/ejv_invoice_link.py
  pay-api/src/pay_api/services/distribution_code.py
  queue_services/payment-reconciliations/q_cli.py
  queue_services/payment-reconciliations/requirements.txt
  queue_services/payment-reconciliations/requirements/repo-libraries.txt
  queue_services/payment-reconciliations/src/reconciliations/ejv_reconciliations.py
  queue_services/payment-reconciliations/src/reconciliations/worker.py
  queue_services/payment-reconciliations/tests/integration/factory.py
  queue_services/payment-reconciliations/tests/integration/test_ejv_reconciliations.py
  queue_services/payment-reconciliations/tests/integration/utils.py
Labels: skip-changelog

#598 Changes for fixing fiscal and some cleanup
  jobs/payment-jobs/requirements.txt
  jobs/payment-jobs/requirements/prod.txt
  jobs/update-stale-payment/README.md
  jobs/update-stale-payment/__init__.py
  jobs/update-stale-payment/config.py
  jobs/update-stale-payment/logging.conf
  jobs/update-stale-payment/openshift/cron-update-stale-payment.yaml
  jobs/update-stale-payment/openshift/update-stale-payment-records-build.json
  jobs/update-stale-payment/requirements.txt
  jobs/update-stale-payment/requirements/dev.txt
  jobs/update-stale-payment/requirements/prod.txt
  jobs/update-stale-payment/run.sh
  jobs/update-stale-payment/tests/unit/__init__.py
  jobs/update-stale-payment/tests/unit/conftest.py
  jobs/update-stale-payment/tests/unit/test_update_stale_payment_records.py
  jobs/update-stale-payment/update_stale_payment_records.py
  jobs/update-stale-payment/utils/__init__.py
  jobs/update-stale-payment/utils/logging.py
  pay-api/src/pay_api/utils/util.py
  queue_services/payment-reconciliations/requirements.txt
  queue_services/payment-reconciliations/requirements/repo-libraries.txt
Labels: skip-changelog

#597 Handle receipt for PAD (not yet PAID) invoices
  report-api/report-templates/payment_receipt.html
Labels: skip-changelog

#599 Dev to Test
  jobs/payment-jobs/requirements.txt
  jobs/payment-jobs/requirements/prod.txt
  jobs/update-stale-payment/README.md
  jobs/update-stale-payment/__init__.py
  jobs/update-stale-payment/config.py
  jobs/update-stale-payment/logging.conf
  jobs/update-stale-payment/openshift/cron-update-stale-payment.yaml
  jobs/update-stale-payment/openshift/update-stale-payment-records-build.json
  jobs/update-stale-payment/requirements.txt
  jobs/update-stale-payment/requirements/dev.txt
  jobs/update-stale-payment/requirements/prod.txt
  jobs/update-stale-payment/run.sh
  jobs/update-stale-payment/tests/unit/__init__.py
  jobs/update-stale-payment/tests/unit/conftest.py
  jobs/update-stale-payment/tests/unit/test_update_stale_payment_records.py
  jobs/update-stale-payment/update_stale_payment_records.py
  jobs/update-stale-payment/utils/__init__.py
  jobs/update-stale-payment/utils/logging.py
  pay-api/src/pay_api/utils/util.py
  queue_services/payment-reconciliations/requirements.txt
  queue_services/payment-reconciliations/requirements/repo-libraries.txt
  report-api/report-templates/payment_receipt.html
Labels: skip-changelog

#600 trg file removed
  jobs/ftp-poller/config.py
  jobs/ftp-poller/tasks/cgi_feeder_poller_task.py
Labels: skip-changelog

#602 Feature/5776 2
  report-api/report-templates/payment_receipt.html
Labels: skip-changelog

#605 Feature/5776 3
  report-api/report-templates/payment_receipt.html
Labels: skip-changelog

#609 Payment recipt
  report-api/report-templates/payment_receipt.html
Labels: skip-changelog

#608 added INBOX ignore
  jobs/ftp-poller/config.py
  jobs/ftp-poller/tasks/cgi_feeder_poller_task.py
Labels: skip-changelog

#610 dev to master
  jobs/ftp-poller/config.py
  jobs/ftp-poller/tasks/cgi_feeder_poller_task.py
  report-api/report-templates/payment_receipt.html
Labels: skip-changelog

#611 Changes for fixing fiscal
  pay-api/src/pay_api/utils/util.py
Labels: skip-changelog

#612 Dev to test
  pay-api/src/pay_api/utils/util.py
Labels: skip-changelog

#613 Changes for fixing fiscal
  jobs/payment-jobs/requirements.txt
Labels: skip-changelog

#614 Dev to Test
  jobs/payment-jobs/requirements.txt
Labels: skip-changelog
