Repository bcgov/sbc-pay, pull requests merged in 2021-05, with the labels that each got.

#686 GI/GA transaction changes
  jobs/payment-jobs/tasks/ejv_partner_distribution_task.py
  jobs/payment-jobs/tests/jobs/factory.py
  jobs/payment-jobs/tests/jobs/test_ejv_partner_distribution_task.py
Labels: enhancement

#687 Dev to Test
  jobs/payment-jobs/tasks/ejv_partner_distribution_task.py
  jobs/payment-jobs/tests/jobs/factory.py
  jobs/payment-jobs/tests/jobs/test_ejv_partner_distribution_task.py
Labels: skip-changelog

#689 Changes for adding details to transaction
  docs/docs/api_contract/pay-api-1.0.0.yaml
  pay-api/migrations/versions/7b8f813d7a14_invoice_details.py
  pay-api/src/pay_api/models/invoice.py
  pay-api/src/pay_api/schemas/schemas/invoice.json
  pay-api/src/pay_api/schemas/schemas/invoice_details.json
  pay-api/src/pay_api/schemas/schemas/payment_request.json
  pay-api/src/pay_api/services/invoice.py
  pay-api/src/pay_api/services/payment.py
  pay-api/src/pay_api/services/payment_service.py
  pay-api/src/pay_api/utils/constants.py
  pay-api/src/pay_api/utils/enums.py
  pay-api/tests/unit/api/test_payment_request.py
  report-api/report-templates/statement_report.html
  report-api/src/api/services/csv_service.py
Labels: enhancement

#692 Added Online Banking and Direct Pay to notebook report #7552
  jobs/notebook-report/weekly/pay.ipynb
Labels: devops

#694 Dev to test
  docs/docs/api_contract/pay-api-1.0.0.yaml
  jobs/notebook-report/weekly/pay.ipynb
  jobs/payment-jobs/tasks/ejv_partner_distribution_task.py
  jobs/payment-jobs/tasks/ejv_payment_task.py
  pay-api/migrations/versions/7b8f813d7a14_invoice_details.py
  pay-api/src/pay_api/models/invoice.py
  pay-api/src/pay_api/schemas/schemas/invoice.json
  pay-api/src/pay_api/schemas/schemas/invoice_details.json
  pay-api/src/pay_api/schemas/schemas/payment_request.json
  pay-api/src/pay_api/services/invoice.py
  pay-api/src/pay_api/services/payment.py
  pay-api/src/pay_api/services/payment_service.py
  pay-api/src/pay_api/utils/constants.py
  pay-api/src/pay_api/utils/enums.py
  pay-api/tests/unit/api/test_payment_request.py
  queue_services/payment-reconciliations/src/reconciliations/ejv_reconciliations.py
  queue_services/payment-reconciliations/tests/conftest.py
  report-api/report-templates/statement_report.html
  report-api/src/api/services/csv_service.py
Labels: skip-changelog

#693 Adding partner on-boarding document
  docs/docs/api_contract/pay-api-1.0.0.yaml
Labels: skip-changelog

#695 Changes for adding NOFEE filing type code
  pay-api/migrations/versions/0aa7d4deef8a_nofee_filing_type.py
Labels: enhancement

#696 Role changes
  pay-api/src/pay_api/resources/account.py
  pay-api/src/pay_api/resources/fee_schedule.py
  pay-api/src/pay_api/utils/enums.py
  pay-api/tests/unit/api/test_account.py
  pay-api/tests/unit/api/test_distributions.py
  pay-api/tests/unit/api/test_fee.py
  pay-api/tests/unit/api/test_payment_request.py
Labels: skip-changelog

#697 Dev to Test
  docs/docs/api_contract/pay-api-1.0.0.yaml
  pay-api/migrations/versions/0aa7d4deef8a_nofee_filing_type.py
  pay-api/src/pay_api/resources/account.py
  pay-api/src/pay_api/resources/fee_schedule.py
  pay-api/src/pay_api/utils/enums.py
  pay-api/tests/unit/api/test_account.py
  pay-api/tests/unit/api/test_distributions.py
  pay-api/tests/unit/api/test_fee.py
  pay-api/tests/unit/api/test_payment_request.py
Labels: skip-changelog

#698 Fixing statement alignment
  queue_services/payment-reconciliations/requirements.txt
  queue_services/payment-reconciliations/requirements/repo-libraries.txt
  report-api/report-templates/statement_report.html
Labels: skip-changelog

#699 Dev to Test
  queue_services/payment-reconciliations/requirements.txt
  queue_services/payment-reconciliations/requirements/repo-libraries.txt
  report-api/report-templates/statement_report.html
Labels: skip-changelog

#700 Changes for fixing gov account pay calculation for business affiliations
  pay-api/src/pay_api/services/auth.py
  pay-api/src/pay_api/utils/user_context.py
Labels: skip-changelog

#702 Fixing the repo back to bcgov
  queue_services/events-listener/requirements.txt
  queue_services/events-listener/requirements/repo-libraries.txt
Labels: skip-changelog

#703 Added disbursement delay
  jobs/payment-jobs/config.py
  jobs/payment-jobs/tasks/ejv_partner_distribution_task.py
  jobs/payment-jobs/tests/jobs/factory.py
  jobs/payment-jobs/tests/jobs/test_ejv_partner_distribution_task.py
Labels: enhancement

#705 Troubleshooting issue with reports api
  report-api/config.py
  report-api/src/api/__init__.py
  report-api/tests/unit/conf/test_configuration.py
Labels: skip-changelog

#706 Fix for calculating the fees for govm accounts.
  pay-api/requirements/prod.txt
  pay-api/src/pay_api/services/auth.py
  pay-api/src/pay_api/utils/user_context.py
  pay-api/tests/unit/api/test_payment_request.py
  pay-api/tests/unit/services/test_auth.py
Labels: skip-changelog

#707 CI/CD Upgrade.
  .github/workflows/bcol-api-cd.yml
  .github/workflows/bcol-api-ci.yml
  .github/workflows/draft-release.yml
  .github/workflows/events-listener-cd.yml
  .github/workflows/events-listener-ci.yml
  .github/workflows/ftp-poller-cd.yml
  .github/workflows/ftp-poller-ci.yml
  .github/workflows/main-pr-check.yml
  .github/workflows/pay-api-cd.yml
  .github/workflows/pay-api-ci.yml
  .github/workflows/payment-jobs-cd.yml
  .github/workflows/payment-jobs-ci.yml
  .github/workflows/payment-reconciliations-cd.yml
  .github/workflows/payment-reconciliations-ci.yml
  .github/workflows/pr-label-check.yml
  .github/workflows/report-api-cd.yml
  .github/workflows/report-api-ci.yml
  bcol-api/Makefile
  bcol-api/jenkins/dev.groovy
  bcol-api/jenkins/prod.groovy
  bcol-api/jenkins/test.groovy
  bcol-api/openshift/templates/bcol-api-pipeline.json
  bcol-api/requirements.txt
  jobs/ftp-poller/Makefile
  jobs/payment-jobs/Makefile
  pay-api/Makefile
  pay-api/jenkins/dev.groovy
  pay-api/jenkins/prod.groovy
  pay-api/jenkins/test.groovy
  pay-api/openshift/templates/pay-api-pipeline.json
  queue_services/events-listener/Makefile
  queue_services/events-listener/jenkins/dev.groovy
  queue_services/events-listener/jenkins/prod.groovy
  queue_services/events-listener/jenkins/test.groovy
  queue_services/events-listener/openshift/templates/events-listener-pipeline.json
  queue_services/payment-reconciliations/Makefile
  queue_services/payment-reconciliations/jenkins/dev.groovy
  queue_services/payment-reconciliations/jenkins/prod.groovy
  queue_services/payment-reconciliations/jenkins/test.groovy
  queue_services/payment-reconciliations/openshift/templates/payment-reconciliations-pipeline.json
  queue_services/payment-reconciliations/requirements.txt
  report-api/Makefile
  report-api/jenkins/dev.groovy
  report-api/jenkins/prod.groovy
  report-api/jenkins/test.groovy
  report-api/openshift/templates/report-api-pipeline.json
Labels: devops
