Repository bcgov/sbc-pay, pull requests merged in 2021-03, with the labels that each got.

#617 removed paymentMethodDescription from reciept schema so that Nr is not failing
  pay-api/src/pay_api/resources/invoice_receipt.py
Labels: bug

#618 fixed param for ftp-poller
  jobs/ftp-poller/run_ftp_poller.sh
Labels: skip-changelog

#593 unpaid invoices logic changed
  jobs/payment-jobs/tasks/unpaid_invoice_notify_task.py
  jobs/payment-jobs/tests/jobs/test_unpaid_invoice_notifytask.py
Labels: enhancement

#619 Dev to Test
  jobs/ftp-poller/run_ftp_poller.sh
  jobs/payment-jobs/tasks/unpaid_invoice_notify_task.py
  jobs/payment-jobs/tests/jobs/test_unpaid_invoice_notifytask.py
  pay-api/src/pay_api/resources/invoice_receipt.py
Labels: skip-changelog

#620 Changes for skipping TRG file check on condition
  jobs/ftp-poller/tasks/cgi_feeder_poller_task.py
  jobs/payment-jobs/tasks/cgi_ejv_task.py
Labels: skip-changelog

#621 Dev to Test
  jobs/ftp-poller/tasks/cgi_feeder_poller_task.py
  jobs/payment-jobs/tasks/cgi_ejv_task.py
Labels: skip-changelog

#622 Changes for skipping invoice creation for Online banking if the corp type is not enabled
  jobs/payment-jobs/tasks/cfs_create_invoice_task.py
Labels: bug

#623 Dev to Test
  jobs/payment-jobs/tasks/cfs_create_invoice_task.py
Labels: skip-changelog

#624 Fixing control total issue in JV file
  jobs/payment-jobs/tasks/cgi_ejv_task.py
Labels: skip-changelog

#625 Dev to Test
  jobs/payment-jobs/tasks/cgi_ejv_task.py
Labels: skip-changelog

#626 Changing the header to Product-Code to match with auth api changes
  pay-api/src/pay_api/services/auth.py
  pay-api/src/pay_api/utils/util.py
Labels: enhancement

#639 Refactoring pay system service and updates for new lint version
  pay-api/requirements.txt
  pay-api/requirements/dev.txt
  pay-api/src/pay_api/exceptions/__init__.py
  pay-api/src/pay_api/services/base_payment_system.py
  pay-api/src/pay_api/services/bcol_service.py
  pay-api/src/pay_api/services/deposit_service.py
  pay-api/src/pay_api/services/direct_pay_service.py
  pay-api/src/pay_api/services/eft_service.py
  pay-api/src/pay_api/services/internal_pay_service.py
  pay-api/src/pay_api/services/oauth_service.py
  pay-api/src/pay_api/services/online_banking_service.py
  pay-api/src/pay_api/services/pad_service.py
  pay-api/src/pay_api/services/paybc_service.py
Labels: skip-changelog

#638 Pad receipt changes
  pay-api/src/pay_api/schemas/schemas/payment_receipt_input.json
  report-api/report-templates/payment_receipt.html
Labels: enhancement

#641 Fixing issue with setting wrong status for JV distribution.
  queue_services/payment-reconciliations/requirements.txt
  queue_services/payment-reconciliations/requirements/prod.txt
  queue_services/payment-reconciliations/src/reconciliations/ejv_reconciliations.py
Labels: skip-changelog

#642 dev to test
  pay-api/requirements.txt
  pay-api/requirements/dev.txt
  pay-api/src/pay_api/exceptions/__init__.py
  pay-api/src/pay_api/schemas/schemas/payment_receipt_input.json
  pay-api/src/pay_api/services/base_payment_system.py
  pay-api/src/pay_api/services/bcol_service.py
  pay-api/src/pay_api/services/deposit_service.py
  pay-api/src/pay_api/services/direct_pay_service.py
  pay-api/src/pay_api/services/eft_service.py
  pay-api/src/pay_api/services/internal_pay_service.py
  pay-api/src/pay_api/services/oauth_service.py
  pay-api/src/pay_api/services/online_banking_service.py
  pay-api/src/pay_api/services/pad_service.py
  pay-api/src/pay_api/services/paybc_service.py
  queue_services/payment-reconciliations/requirements.txt
  queue_services/payment-reconciliations/requirements/prod.txt
  queue_services/payment-reconciliations/src/reconciliations/ejv_reconciliations.py
  report-api/report-templates/payment_receipt.html
Labels: skip-changelog

#640 Adding GL codes to gov accounts
  pay-api/migrations/versions/7c127b25168f_gov_account.py
  pay-api/requirements.txt
  pay-api/requirements/prod.txt
  pay-api/src/pay_api/factory/payment_system_factory.py
  pay-api/src/pay_api/models/distribution_code.py
  pay-api/src/pay_api/schemas/schemas/payment_info.json
  pay-api/src/pay_api/services/distribution_code.py
  pay-api/src/pay_api/services/ejv_pay_service.py
  pay-api/src/pay_api/services/payment_account.py
  pay-api/src/pay_api/utils/enums.py
  pay-api/tests/unit/api/test_account.py
  pay-api/tests/unit/api/test_payment_request.py
  pay-api/tests/unit/services/test_payment_account.py
  pay-api/tests/utilities/base_test.py
Labels: enhancement

#644 Fixing issue with reconcilations
  queue_services/payment-reconciliations/src/reconciliations/ejv_reconciliations.py
Labels: skip-changelog

#645 Dev to Test
  pay-api/migrations/versions/7c127b25168f_gov_account.py
  pay-api/requirements.txt
  pay-api/requirements/prod.txt
  pay-api/src/pay_api/factory/payment_system_factory.py
  pay-api/src/pay_api/models/distribution_code.py
  pay-api/src/pay_api/schemas/schemas/payment_info.json
  pay-api/src/pay_api/services/distribution_code.py
  pay-api/src/pay_api/services/ejv_pay_service.py
  pay-api/src/pay_api/services/payment_account.py
  pay-api/src/pay_api/utils/enums.py
  pay-api/tests/unit/api/test_account.py
  pay-api/tests/unit/api/test_payment_request.py
  pay-api/tests/unit/services/test_payment_account.py
  pay-api/tests/utilities/base_test.py
  queue_services/payment-reconciliations/src/reconciliations/ejv_reconciliations.py
Labels: skip-changelog

#643 Adding filing types for PPR
  pay-api/migrations/versions/2efd8e2b92a1_ppr_fee_codes.py
  pay-api/src/pay_api/services/online_banking_service.py
  pay-api/src/pay_api/services/payment_service.py
Labels: enhancement

#652 Dev to Test
  pay-api/migrations/versions/2efd8e2b92a1_ppr_fee_codes.py
  pay-api/src/pay_api/services/online_banking_service.py
  pay-api/src/pay_api/services/payment_service.py
Labels: skip-changelog
