Repository bcgov/sbc-pay, pull requests merged in 2021-12, with the labels that each got.

#834 Routing slip receipt number fix for linked routing slips
  bcol-api/requirements.txt
  bcol-api/src/bcol_api/utils/logging.py
  docs/docs/PayBC Mocking/paybc-1.0.0.yaml
  jobs/payment-jobs/requirements.txt
  jobs/payment-jobs/requirements/prod.txt
  jobs/payment-jobs/tasks/cfs_create_invoice_task.py
  jobs/payment-jobs/tasks/routing_slip_task.py
  jobs/payment-jobs/tests/docker/docker-compose.yml
  jobs/payment-jobs/tests/jobs/test_cfs_create_routing_slip_linking.py
  pay-api/requirements.txt
  pay-api/src/pay_api/services/cfs_service.py
  pay-api/src/pay_api/utils/constants.py
Labels: enhancement

#837 Fixing JV where the distribution was always updated to stop_ejv=true
  queue_services/payment-reconciliations/src/reconciliations/ejv_reconciliations.py
Labels: skip-changelog

#836 CFS Integration for NSF
  jobs/payment-jobs/config.py
  jobs/payment-jobs/invoke_jobs.py
  jobs/payment-jobs/requirements.txt
  jobs/payment-jobs/requirements/prod.txt
  jobs/payment-jobs/setup.cfg
  jobs/payment-jobs/tasks/cfs_create_invoice_task.py
  jobs/payment-jobs/tasks/routing_slip_task.py
  jobs/payment-jobs/tests/jobs/factory.py
  jobs/payment-jobs/tests/jobs/test_cfs_create_routing_slip_linking.py
  jobs/payment-jobs/tests/jobs/test_routing_slip_task.py
  pay-api/setup.cfg
  pay-api/src/pay_api/services/direct_pay_service.py
  pay-api/src/pay_api/services/fas/routing_slip.py
  pay-api/src/pay_api/services/internal_pay_service.py
  pay-api/src/pay_api/utils/constants.py
  pay-api/tests/unit/api/fas/test_routing_slip.py
Labels: enhancement

#839 fix for broken statement settings
  pay-api/src/pay_api/schemas/schemas/statement_notification_request.json
Labels: bug

#838 CFS integration for routing slip write off and refund
  jobs/payment-jobs/invoke_jobs.py
  jobs/payment-jobs/requirements.txt
  jobs/payment-jobs/requirements/prod.txt
  jobs/payment-jobs/tasks/routing_slip_task.py
  jobs/payment-jobs/tests/docker/docker-compose.yml
  jobs/payment-jobs/tests/jobs/test_cfs_create_account_task.py
  jobs/payment-jobs/tests/jobs/test_routing_slip_task.py
  pay-api/migrations/versions/aa9207187d6b_fas_routing_slip_status_updates.py
  pay-api/src/pay_api/services/cfs_service.py
  pay-api/src/pay_api/utils/enums.py
  pay-api/tests/unit/api/fas/test_routing_slip.py
Labels: enhancement

#841 Adding refund_amount column and update its value on routing_slips model
  jobs/payment-jobs/tasks/routing_slip_task.py
  pay-api/migrations/versions/0d885750ded9_routing_slip_refund_amount.py
  pay-api/src/pay_api/models/routing_slip.py
Labels: skip-changelog

#843 Adjusting report API timeout to 360 seconds in gunicorn
  report-api/Dockerfile
  report-api/entrypoint.sh
Labels: enhancement

#842 AP Job for refunding FAS routing slips
  jobs/payment-jobs/config.py
  jobs/payment-jobs/invoke_jobs.py
  jobs/payment-jobs/requirements.txt
  jobs/payment-jobs/requirements/prod.txt
  jobs/payment-jobs/run_ap_routing_slip_refund_task.sh
  jobs/payment-jobs/tasks/ap_routing_slip_refund_task.py
  jobs/payment-jobs/tasks/common/cgi_ap.py
  jobs/payment-jobs/tasks/common/cgi_ejv.py
  jobs/payment-jobs/tasks/ejv_partner_distribution_task.py
  jobs/payment-jobs/tasks/ejv_payment_task.py
  jobs/payment-jobs/tasks/routing_slip_task.py
  jobs/payment-jobs/tests/jobs/factory.py
  jobs/payment-jobs/tests/jobs/test_ap_routing_slip_refund_task.py
  jobs/payment-jobs/tests/jobs/test_ejv_payment_task.py
  jobs/payment-jobs/tests/jobs/test_routing_slip_task.py
  pay-api/migrations/versions/f8408a4a782c_ap_changes.py
  pay-api/requirements.txt
  pay-api/src/pay_api/models/ejv_file.py
  pay-api/src/pay_api/utils/enums.py
  queue_services/payment-reconciliations/requirements.txt
  queue_services/payment-reconciliations/requirements/repo-libraries.txt
  queue_services/payment-reconciliations/src/reconciliations/ejv_reconciliations.py
  queue_services/payment-reconciliations/tests/integration/test_ejv_reconciliations.py
  report-api/gunicorn_config.py
Labels: enhancement

#844 Added get fee endpoint
  pay-api/src/pay_api/resources/account.py
  pay-api/src/pay_api/services/payment_account.py
  pay-api/tests/unit/api/test_account.py
Labels: enhancement

#846 Update spec for adding variable fee
  docs/docs/api_contract/pay-api-1.0.0.yaml
Labels: skip-changelog

#847 10068 - API validation for routing slip number length
  pay-api/src/pay_api/schemas/schemas/routing_slip.json
  pay-api/tests/unit/api/fas/test_routing_slip.py
  pay-api/tests/unit/api/test_payment_request.py
  pay-api/tests/utilities/base_test.py
Labels: bug
