Repository bcgov/sbc-pay, pull requests merged in 2021-04, with the labels that each got.

#656 Fixing issue with receipt
  report-api/report-templates/payment_receipt.html
Labels: bug

#658 Report fix
  docs/docs/api_contract/pay-api-1.0.0.yaml
  report-api/report-templates/payment_receipt.html
Labels: bug

#654 Api gateway integration changes
  pay-api/src/pay_api/utils/user_context.py
Labels: enhancement

#657 Update Dockerfile, Makefile and CICD flow scripts.
  .github/workflows/bcol-api-cd.yml
  .github/workflows/bcol-api-ci.yml
  .github/workflows/events-listener-cd.yml
  .github/workflows/events-listener-ci.yml
  .github/workflows/ftp-poller-cd.yml
  .github/workflows/ftp-poller-ci.yml
  .github/workflows/pay-api-cd.yml
  .github/workflows/pay-api-ci.yml
  .github/workflows/payment-jobs-cd.yml
  .github/workflows/payment-jobs-ci.yml
  .github/workflows/payment-reconciliations-cd.yml
  .github/workflows/payment-reconciliations-ci.yml
  .github/workflows/report-api-cd.yml
  .github/workflows/report-api-ci.yml
  bcol-api/Dockerfile
  bcol-api/Makefile
  jobs/ftp-poller/Dockerfile
  jobs/ftp-poller/Makefile
  jobs/payment-jobs/Dockerfile
  jobs/payment-jobs/Makefile
  pay-api/Dockerfile
  pay-api/Makefile
  queue_services/events-listener/Dockerfile
  queue_services/events-listener/Makefile
  queue_services/payment-reconciliations/Dockerfile
  queue_services/payment-reconciliations/Makefile
  report-api/Dockerfile
  report-api/Makefile
Labels: devops

#662 Updating the requirements as bot is finding some vulnerabilities.
  bcol-api/requirements.txt
  jobs/ftp-poller/requirements.txt
  jobs/payment-jobs/requirements.txt
  pay-api/requirements.txt
  queue_services/events-listener/requirements.txt
  queue_services/payment-reconciliations/requirements.txt
Labels: skip-changelog

#664 Changes for adding service fee only once
  pay-api/src/pay_api/jwt_wrapper.py
  pay-api/src/pay_api/services/payment_service.py
  pay-api/src/pay_api/utils/auth.py
  pay-api/tests/unit/api/test_payment_request.py
  pay-api/tests/utilities/base_test.py
Labels: enhancement

#665 Refactoring current JV code to support multiple JVs
  jobs/payment-jobs/invoke_jobs.py
  jobs/payment-jobs/requirements.txt
  jobs/payment-jobs/run_cgi_ejv_task.sh
  jobs/payment-jobs/run_cgi_partner_ejv_task.sh
  jobs/payment-jobs/tasks/cgi_ejv.py
  jobs/payment-jobs/tasks/ejv_partner_distribution_task.py
  jobs/payment-jobs/tests/jobs/test_ejv_partner_distribution_task.py
Labels: enhancement

#671 Automated Query Request #6972
  jobs/notebook-report/Dockerfile
  jobs/notebook-report/Makefile
  jobs/notebook-report/README.md
  jobs/notebook-report/config.py
  jobs/notebook-report/jenkins/dev.groovy
  jobs/notebook-report/jenkins/prod.groovy
  jobs/notebook-report/jenkins/test.groovy
  jobs/notebook-report/logging.conf
  jobs/notebook-report/notebookreport.py
  jobs/notebook-report/openshift/Readme.md
  jobs/notebook-report/openshift/templates/bc.yaml
  jobs/notebook-report/openshift/templates/cronjob.yaml
  jobs/notebook-report/requirements.txt
  jobs/notebook-report/requirements/dev.txt
  jobs/notebook-report/requirements/prod.txt
  jobs/notebook-report/run.sh
  jobs/notebook-report/setup.cfg
  jobs/notebook-report/setup.py
  jobs/notebook-report/tests/unit/__init__.py
  jobs/notebook-report/tests/unit/conftest.py
  jobs/notebook-report/tests/unit/test_job.py
  jobs/notebook-report/util/__init__.py
  jobs/notebook-report/util/logging.py
  jobs/notebook-report/weekly/pay.ipynb
Labels: devops

#669 Changes for creating and uploading JV for gov account payments
  jobs/payment-jobs/config.py
  jobs/payment-jobs/invoke_jobs.py
  jobs/payment-jobs/run_cgi_payment_ejv_task.sh
  jobs/payment-jobs/tasks/common/__init__.py
  jobs/payment-jobs/tasks/common/cgi_ejv.py
  jobs/payment-jobs/tasks/ejv_partner_distribution_task.py
  jobs/payment-jobs/tasks/ejv_payment_task.py
  jobs/payment-jobs/tasks/stale_payment_task.py
  jobs/payment-jobs/tests/jobs/factory.py
  jobs/payment-jobs/tests/jobs/test_activate_pad_account_task.py
  jobs/payment-jobs/tests/jobs/test_cfs_create_invoice_task.py
  jobs/payment-jobs/tests/jobs/test_ejv_payment_task.py
  jobs/payment-jobs/tests/jobs/test_generate_statements.py
Labels: enhancement

#672 Changes for reconciling multiple JV details in single file and to sync EJV payments
  jobs/payment-jobs/tasks/ejv_payment_task.py
  jobs/payment-jobs/tests/jobs/factory.py
  queue_services/payment-reconciliations/src/reconciliations/ejv_reconciliations.py
  queue_services/payment-reconciliations/tests/integration/factory.py
  queue_services/payment-reconciliations/tests/integration/test_ejv_reconciliations.py
Labels: enhancement

#674 Dev to Test
  jobs/notebook-report/Dockerfile
  jobs/notebook-report/Makefile
  jobs/notebook-report/README.md
  jobs/notebook-report/config.py
  jobs/notebook-report/jenkins/dev.groovy
  jobs/notebook-report/jenkins/prod.groovy
  jobs/notebook-report/jenkins/test.groovy
  jobs/notebook-report/logging.conf
  jobs/notebook-report/notebookreport.py
  jobs/notebook-report/openshift/Readme.md
  jobs/notebook-report/openshift/templates/bc.yaml
  jobs/notebook-report/openshift/templates/cronjob.yaml
  jobs/notebook-report/requirements.txt
  jobs/notebook-report/requirements/dev.txt
  jobs/notebook-report/requirements/prod.txt
  jobs/notebook-report/run.sh
  jobs/notebook-report/setup.cfg
  jobs/notebook-report/setup.py
  jobs/notebook-report/tests/unit/__init__.py
  jobs/notebook-report/tests/unit/conftest.py
  jobs/notebook-report/tests/unit/test_job.py
  jobs/notebook-report/util/__init__.py
  jobs/notebook-report/util/logging.py
  jobs/notebook-report/weekly/pay.ipynb
  jobs/payment-jobs/config.py
  jobs/payment-jobs/invoke_jobs.py
  jobs/payment-jobs/run_cgi_payment_ejv_task.sh
  jobs/payment-jobs/tasks/common/__init__.py
  jobs/payment-jobs/tasks/common/cgi_ejv.py
  jobs/payment-jobs/tasks/ejv_partner_distribution_task.py
  jobs/payment-jobs/tasks/ejv_payment_task.py
  jobs/payment-jobs/tasks/stale_payment_task.py
  jobs/payment-jobs/tests/jobs/factory.py
  jobs/payment-jobs/tests/jobs/test_activate_pad_account_task.py
  jobs/payment-jobs/tests/jobs/test_cfs_create_invoice_task.py
  jobs/payment-jobs/tests/jobs/test_ejv_payment_task.py
  jobs/payment-jobs/tests/jobs/test_generate_statements.py
  queue_services/payment-reconciliations/src/reconciliations/ejv_reconciliations.py
  queue_services/payment-reconciliations/tests/integration/factory.py
  queue_services/payment-reconciliations/tests/integration/test_ejv_reconciliations.py
Labels: skip-changelog

#673 Changes for BCOL refund events, adding version to distribution_codes table
  pay-api/migrations/versions/9335f4e0aa22_distribution_code_version.py
  pay-api/requirements.txt
  pay-api/requirements/dev.txt
  pay-api/src/pay_api/models/distribution_code.py
  pay-api/src/pay_api/services/refund.py
  pay-api/tests/unit/api/test_refund.py
  pay-api/tests/unit/services/test_queue_publisher.py
Labels: enhancement

#675 Dev to Test
  pay-api/migrations/versions/9335f4e0aa22_distribution_code_version.py
  pay-api/requirements.txt
  pay-api/requirements/dev.txt
  pay-api/src/pay_api/models/distribution_code.py
  pay-api/src/pay_api/services/refund.py
  pay-api/tests/unit/api/test_refund.py
  pay-api/tests/unit/services/test_queue_publisher.py
Labels: skip-changelog

#676 6945 - Standardize country code.
  bcol-api/requirements.txt
  bcol-api/requirements/prod.txt
  bcol-api/src/bcol_api/services/bcol_profile.py
  bcol-api/tests/unit/services/test_bcol_profile.py
Labels: enhancement

#678 Adding fee overrides for gov accounts
  pay-api/migrations/versions/7649a31bfe39_account_fee.py
  pay-api/src/pay_api/models/__init__.py
  pay-api/src/pay_api/models/account_fee.py
  pay-api/src/pay_api/models/corp_type.py
  pay-api/src/pay_api/resources/account.py
  pay-api/src/pay_api/schemas/schemas/account_fee.json
  pay-api/src/pay_api/schemas/schemas/account_fees.json
  pay-api/src/pay_api/services/code.py
  pay-api/src/pay_api/services/fee_schedule.py
  pay-api/src/pay_api/services/payment_account.py
  pay-api/src/pay_api/utils/enums.py
  pay-api/tests/unit/api/test_account.py
  pay-api/tests/unit/api/test_code.py
  pay-api/tests/unit/api/test_fee.py
  pay-api/tests/unit/api/test_payment_request.py
Labels: enhancement

#677 dev to test
  bcol-api/requirements.txt
  bcol-api/requirements/prod.txt
  bcol-api/src/bcol_api/services/bcol_profile.py
  bcol-api/tests/unit/services/test_bcol_profile.py
  pay-api/migrations/versions/7649a31bfe39_account_fee.py
  pay-api/src/pay_api/models/__init__.py
  pay-api/src/pay_api/models/account_fee.py
  pay-api/src/pay_api/models/corp_type.py
  pay-api/src/pay_api/resources/account.py
  pay-api/src/pay_api/schemas/schemas/account_fee.json
  pay-api/src/pay_api/schemas/schemas/account_fees.json
  pay-api/src/pay_api/services/code.py
  pay-api/src/pay_api/services/fee_schedule.py
  pay-api/src/pay_api/services/payment_account.py
  pay-api/src/pay_api/utils/enums.py
  pay-api/tests/unit/api/test_account.py
  pay-api/tests/unit/api/test_code.py
  pay-api/tests/unit/api/test_fee.py
  pay-api/tests/unit/api/test_payment_request.py
Labels: skip-changelog

#679 Miscellaneous bug fixes reported by other teams.
  pay-api/src/pay_api/services/payment_transaction.py
  pay-api/src/pay_api/services/refund.py
  pay-api/src/pay_api/utils/enums.py
  pay-api/src/pay_api/utils/util.py
Labels: skip-changelog

#680 Dev to Test
  pay-api/src/pay_api/services/payment_transaction.py
  pay-api/src/pay_api/services/refund.py
  pay-api/src/pay_api/utils/enums.py
  pay-api/src/pay_api/utils/util.py
Labels: skip-changelog

#681 Updating requirement for new release
  jobs/payment-jobs/requirements.txt
  queue_services/events-listener/requirements.txt
  queue_services/payment-reconciliations/requirements.txt
Labels: skip-changelog

#682 Dev to Test
  jobs/payment-jobs/requirements.txt
  queue_services/events-listener/requirements.txt
  queue_services/payment-reconciliations/requirements.txt
Labels: skip-changelog
