Repository bcgov/sbc-pay, pull requests merged in 2022-12, with the labels that each got.

#1027 14382 - Changes for new invoice status codes: CREDITED and CANCELLED.
  docs/docs/api_contract/pay-api-1.0.3.yaml
  pay-api/migrations/versions/833b83dc67ac_new_invoice_statuses.py
  pay-api/src/pay_api/config.py
  pay-api/src/pay_api/services/base_payment_system.py
  pay-api/src/pay_api/services/direct_pay_service.py
  pay-api/src/pay_api/services/online_banking_service.py
  pay-api/src/pay_api/services/pad_service.py
  pay-api/src/pay_api/services/paybc_service.py
  pay-api/src/pay_api/utils/enums.py
  pay-api/src/pay_api/version.py
  pay-api/tests/unit/api/test_refund.py
  pay-api/tests/unit/services/test_direct_pay_service.py
  pay-api/tests/unit/services/test_refund.py
Labels: enhancement, DoNotMerge

#1029 14180 - Don't set waived fee amount on variable fees
  pay-api/src/pay_api/services/fee_schedule.py
  pay-api/tests/unit/api/test_payment_request.py
Labels: bug

#1030 bcol refund confirmation job
  jobs/payment-jobs/Makefile
  jobs/payment-jobs/config.py
  jobs/payment-jobs/devops/vaults.json
  jobs/payment-jobs/invoke_jobs.py
  jobs/payment-jobs/requirements.txt
  jobs/payment-jobs/requirements/bcregistry-libraries.txt
  jobs/payment-jobs/requirements/prod.txt
  jobs/payment-jobs/run_bcol_refund_confirmation_task.sh
  jobs/payment-jobs/services/__init__.py
  jobs/payment-jobs/services/oracle.py
  jobs/payment-jobs/tasks/bcol_refund_confirmation_task.py
  jobs/payment-jobs/tests/jobs/test_bcol_refund_confirmation_task.py
Labels: enhancement

#1031 Bug 14107 Statements have footer rendered on top of the content
  report-api/report-templates/statement_report.html
  report-api/requirements/dev.txt
Labels: bug

#1033 Fix rate type.
  pay-api/src/pay_api/services/bcol_service.py
Labels: bug

#1034 Put the rate type back. Put in a bypass for is_apply_charge, for CSO …
  bcol-api/requirements.txt
  bcol-api/requirements/dev.txt
  bcol-api/src/bcol_api/resources/bcol_payment.py
  bcol-api/src/bcol_api/schemas/schemas/payment_request.json
  bcol-api/src/bcol_api/schemas/utils.py
  jobs/ftp-poller/requirements/dev.txt
  jobs/notebook-report/requirements/dev.txt
  pay-admin/requirements/dev.txt
  pay-api/src/pay_api/models/payment_account.py
  pay-api/src/pay_api/services/bcol_service.py
  queue_services/events-listener/requirements/dev.txt
  queue_services/payment-reconciliations/requirements/dev.txt
Labels: bug, enhancement

#1032 14381 bcol refund confirmation 2
  jobs/payment-jobs/requirements.txt
  jobs/payment-jobs/requirements/bcregistry-libraries.txt
Labels: dependencies, maintenance

#1035 11314 - Part 1 - Changes required for VOID routing slips.
  jobs/payment-jobs/tests/docker/docker-compose.yml
  pay-api/migrations/versions/5418ad1a5fdd_.py
  pay-api/src/pay_api/models/invoice_reference.py
  pay-api/src/pay_api/models/routing_slip.py
  pay-api/src/pay_api/services/base_payment_system.py
  pay-api/src/pay_api/services/cfs_service.py
  pay-api/src/pay_api/services/direct_pay_service.py
  pay-api/src/pay_api/services/fas/routing_slip.py
  pay-api/src/pay_api/services/fas/routing_slip_status_transition_service.py
  pay-api/src/pay_api/services/invoice_reference.py
  pay-api/src/pay_api/services/payment.py
  pay-api/src/pay_api/utils/constants.py
  pay-api/src/pay_api/utils/enums.py
  pay-api/tests/docker/docker-compose.yml
Labels: enhancement

#1036 11314 - Part 2 - Update to jobs for VOID routing slips.
  jobs/payment-jobs/Makefile
  jobs/payment-jobs/invoke_jobs.py
  jobs/payment-jobs/requirements.txt
  jobs/payment-jobs/requirements/bcregistry-libraries.txt
  jobs/payment-jobs/tasks/cfs_create_invoice_task.py
  jobs/payment-jobs/tasks/ejv_payment_task.py
  jobs/payment-jobs/tasks/routing_slip_task.py
  jobs/payment-jobs/tests/jobs/test_cfs_create_invoice_task.py
  jobs/payment-jobs/tests/jobs/test_ejv_payment_task.py
  jobs/payment-jobs/tests/jobs/test_routing_slip_task.py
  queue_services/payment-reconciliations/src/reconciliations/cgi_reconciliations.py
  queue_services/payment-reconciliations/tests/integration/test_cgi_reconciliations.py
Labels: enhancement

#1047 Update github workflows, so we don't run into codecov errors.
  .github/CODEOWNERS
  .github/workflows/bcol-api-cd.yml
  .github/workflows/bcol-api-ci.yml
  .github/workflows/events-listener-cd.yml
  .github/workflows/events-listener-ci.yml
  .github/workflows/ftp-poller-cd.yml
  .github/workflows/ftp-poller-ci.yml
  .github/workflows/pay-admin-cd.yml
  .github/workflows/pay-admin-ci.yml
  .github/workflows/pay-api-cd.yml
  .github/workflows/pay-api-ci.yml
  .github/workflows/payment-jobs-cd.yml
  .github/workflows/payment-jobs-ci.yml
  .github/workflows/payment-reconciliations-cd.yml
  .github/workflows/payment-reconciliations-ci.yml
  .github/workflows/ppr-report-api-cd.yml
  .github/workflows/pr-label-check.yml
  .github/workflows/report-api-cd.yml
  .github/workflows/report-api-ci.yml
Labels: maintenance

#1050 add oracle stuff to dockerfile
  jobs/payment-jobs/Dockerfile
Labels: bug

#1049 11314 & 11167 - Part 3 - More changes for VOID, also starting the ground work for CORRECTION.
  jobs/payment-jobs/invoke_jobs.py
  jobs/payment-jobs/tasks/routing_slip_task.py
  jobs/payment-jobs/tests/jobs/test_routing_slip_task.py
  pay-api/migrations/versions/f497d603602e_routing_slip_correction_state.py
  pay-api/src/pay_api/services/fas/routing_slip.py
  pay-api/src/pay_api/services/fas/routing_slip_status_transition_service.py
  pay-api/src/pay_api/services/internal_pay_service.py
  pay-api/src/pay_api/utils/enums.py
  pay-api/src/pay_api/utils/errors.py
  pay-api/tests/unit/api/fas/test_routing_slip.py
Labels: enhancement

#1051 Put in max length for folio number, filing identifier.
  pay-api/src/pay_api/schemas/schemas/filing_info.json
Labels: bug

#1052 Release changes using launch darkly plus minor tweaks
  bcol-api/src/bcol_api/schemas/utils.py
  docs/docs/database/bca_monthly_invoices.sql
  jobs/payment-jobs/tasks/routing_slip_task.py
  pay-api/flags.json
  pay-api/src/pay_api/__init__.py
  pay-api/src/pay_api/models/db.py
  pay-api/src/pay_api/schemas/utils.py
  pay-api/src/pay_api/services/__init__.py
  pay-api/src/pay_api/services/base_payment_system.py
  pay-api/src/pay_api/services/bcol_service.py
  pay-api/src/pay_api/services/cfs_service.py
  pay-api/src/pay_api/services/fee_schedule.py
  pay-api/src/pay_api/services/flags.py
  pay-api/src/pay_api/utils/enums.py
  pay-api/src/pay_api/version.py
Labels: enhancement

#1054 Update payment jobs deps.
  jobs/payment-jobs/requirements.txt
  pay-api/src/pay_api/services/cfs_service.py
  pay-api/src/pay_api/utils/enums.py
Labels: bug, dependencies

#1055 Fix rs jobs - fix flags
  jobs/payment-jobs/requirements.txt
  jobs/payment-jobs/tests/jobs/test_routing_slip_task.py
  pay-api/src/pay_api/services/base_payment_system.py
  pay-api/src/pay_api/services/bcol_service.py
  pay-api/src/pay_api/services/fee_schedule.py
  pay-api/src/pay_api/services/flags.py
  pay-api/tests/unit/services/test_flags.py
Labels: bug

#1056 Repoint requirements.txt to latest main.
  jobs/payment-jobs/requirements.txt
Labels: bug

#1058 allow job to run with more than 1000 records to update
  jobs/payment-jobs/tasks/bcol_refund_confirmation_task.py
Labels: bug

#1059 14346 - update CfsReceiptStatus
  pay-api/src/pay_api/utils/enums.py
Labels: bug

#1060 14346 add receipt status check before sending reverse request
  jobs/payment-jobs/requirements.txt
  jobs/payment-jobs/tasks/routing_slip_task.py
  jobs/payment-jobs/tests/jobs/test_routing_slip_task.py
Labels: bug

#1061 14507 - added a column of FOILO and change FEE CODE to PRODUCT CODE
  docs/docs/database/bca_monthly_invoices.sql
Labels: documentation

#1062 14507 - Convert UTC to PDT/PST
  docs/docs/database/bca_monthly_invoices.sql
Labels: documentation
