Repository bcgov/sbc-pay, pull requests merged in 2022-10, with the labels that each got.

#997 13055 - CAS Settlement error, plus ACK issues
  pay-api/migrations/versions/9abc5b5245b6_cas_settlements.py
  pay-api/src/pay_api/models/__init__.py
  pay-api/src/pay_api/models/cas_settlement.py
  pay-api/src/pay_api/models/ejv_file.py
  queue_services/payment-reconciliations/requirements.txt
  queue_services/payment-reconciliations/src/reconciliations/cgi_reconciliations.py
  queue_services/payment-reconciliations/src/reconciliations/payment_reconciliations.py
  queue_services/payment-reconciliations/tests/conftest.py
  queue_services/payment-reconciliations/tests/integration/test_cgi_reconciliations.py
Labels: bug

#998 Update dockerfile.
  queue_services/payment-reconciliations/Dockerfile
Labels: bug

#999 Update logging file + minor fixes + minor pay permission fix
  pay-api/src/pay_api/services/auth.py
  pay-api/src/pay_api/utils/enums.py
  pay-api/src/pay_api/version.py
  queue_services/payment-reconciliations/logging.conf
  queue_services/payment-reconciliations/src/reconciliations/payment_reconciliations.py
  queue_services/payment-reconciliations/src/reconciliations/version.py
Labels: maintenance

#1000 13611 - PAY - Add launch darkly
  pay-api/devops/vaults.json
  pay-api/flags.json
  pay-api/requirements.txt
  pay-api/requirements/prod.txt
  pay-api/src/pay_api/__init__.py
  pay-api/src/pay_api/config.py
  pay-api/src/pay_api/services/__init__.py
  pay-api/src/pay_api/services/flags.py
  pay-api/tests/unit/services/test_flags.py
Labels: enhancement

#1001 Launchdarkly vault.json fix
  pay-api/devops/vaults.json
Labels: enhancement

#977 13309 - $0 Totals stuck in Approved for EJV/PAD
  jobs/payment-jobs/requirements.txt
  jobs/payment-jobs/requirements/prod.txt
  jobs/payment-jobs/tasks/ejv_payment_task.py
  jobs/payment-jobs/tests/jobs/test_cfs_create_invoice_task.py
  pay-api/src/pay_api/services/cfs_service.py
  pay-api/src/pay_api/services/payment_line_item.py
  pay-api/src/pay_api/version.py
  pay-api/tests/unit/api/test_account.py
  pay-api/tests/unit/api/test_payment_request.py
Labels: bug

#1002 13611 - added LD flag service to queue services and payment jobs
  jobs/payment-jobs/config.py
  jobs/payment-jobs/devops/vaults.json
  jobs/payment-jobs/invoke_jobs.py
  jobs/payment-jobs/requirements.txt
  jobs/payment-jobs/requirements/prod.txt
  queue_services/events-listener/devops/vaults.json
  queue_services/events-listener/requirements.txt
  queue_services/events-listener/requirements/prod.txt
  queue_services/events-listener/src/events_listener/config.py
  queue_services/events-listener/src/events_listener/worker.py
  queue_services/payment-reconciliations/devops/vaults.json
  queue_services/payment-reconciliations/requirements.txt
  queue_services/payment-reconciliations/requirements/prod.txt
  queue_services/payment-reconciliations/src/reconciliations/config.py
  queue_services/payment-reconciliations/src/reconciliations/worker.py
Labels: enhancement

#1004 9431 - Added key to BCOL refund emails
  pay-api/src/pay_api/services/base_payment_system.py
Labels: enhancement

#1003 14055 - Pay job logging fix, also payment reconciliation
  jobs/payment-jobs/tasks/cfs_create_invoice_task.py
  queue_services/payment-reconciliations/src/reconciliations/payment_reconciliations.py
Labels: bug
