Repository bcgov/sbc-pay, pull requests merged in 2022-01, with the labels that each got.

#845 Changes for AP reconciliations.
  jobs/payment-jobs/config.py
  jobs/payment-jobs/requirements.txt
  jobs/payment-jobs/requirements/prod.txt
  jobs/payment-jobs/tasks/ap_routing_slip_refund_task.py
  jobs/payment-jobs/tasks/common/cgi_ap.py
  pay-api/src/pay_api/models/routing_slip.py
  pay-api/src/pay_api/resources/refund.py
  pay-api/src/pay_api/services/refund.py
  queue_services/payment-reconciliations/requirements.txt
  queue_services/payment-reconciliations/requirements/repo-libraries.txt
  queue_services/payment-reconciliations/src/reconciliations/cgi_reconciliations.py
  queue_services/payment-reconciliations/src/reconciliations/worker.py
  queue_services/payment-reconciliations/tests/integration/factory.py
  queue_services/payment-reconciliations/tests/integration/test_cgi_reconciliations.py
Labels: enhancement

#849 10400: Restricting service accounts to only their transactions.
  pay-api/src/pay_api/models/payment.py
  pay-api/tests/unit/api/test_account.py
Labels: enhancement

#850 Trying a GET on invoice, if invoice creation fails.
  jobs/payment-jobs/tasks/cfs_create_invoice_task.py
  jobs/payment-jobs/tasks/stale_payment_task.py
  queue_services/payment-reconciliations/src/reconciliations/payment_reconciliations.py
Labels: skip-changelog

#851 Changing NSF routing slip status to ACTIVE once linking is complete
  jobs/payment-jobs/tasks/routing_slip_task.py
  jobs/payment-jobs/tests/jobs/test_routing_slip_task.py
Labels: enhancement

#853 9381: Changes for supporting custom status in allowed status list
  pay-api/src/pay_api/services/fas/routing_slip.py
  pay-api/src/pay_api/services/fas/routing_slip_status_transition_service.py
  pay-api/src/pay_api/utils/enums.py
  pay-api/tests/unit/api/fas/test_routing_slip.py
Labels: enhancement

#854 9381: Changes for supporting custom status in allowed status list
  pay-api/src/pay_api/services/fas/routing_slip.py
  pay-api/src/pay_api/services/fas/routing_slip_status_transition_service.py
  pay-api/tests/unit/api/fas/test_routing_slip.py
Labels: skip-changelog

#855 Improve performance and font issue.
  report-api/Dockerfile
  report-api/requirements.txt
  report-api/src/api/services/report_service.py
Labels: devops

#852 Fixing stale payment to include service unavailable failed transactions
  jobs/payment-jobs/tasks/cfs_create_invoice_task.py
  jobs/payment-jobs/tasks/stale_payment_task.py
  pay-api/src/pay_api/services/payment_transaction.py
Labels: enhancement

#856 10492 - Add filter by remaining amount in routing slip search
  pay-api/src/pay_api/models/routing_slip.py
Labels: enhancement

#857 Using FAS client for FAS receipt creation
  jobs/payment-jobs/config.py
  jobs/payment-jobs/requirements.txt
  jobs/payment-jobs/requirements/prod.txt
  jobs/payment-jobs/services/routing_slip.py
  jobs/payment-jobs/tasks/common/cgi_ap.py
  jobs/payment-jobs/tasks/routing_slip_task.py
  pay-api/migrations/versions/e7fb85dbffae_fas_audit_fields.py
  pay-api/src/pay_api/models/account_fee.py
  pay-api/src/pay_api/models/refund.py
  pay-api/src/pay_api/services/cfs_service.py
  pay-api/src/pay_api/services/refund.py
Labels: skip-changelog

#858 Adding FAS auditable values
  pay-api/migrations/versions/e7fb85dbffae_fas_audit_fields.py
Labels: skip-changelog

#859 Changes to add correct number of transaction lines in AP Job
  jobs/payment-jobs/requirements.txt
  jobs/payment-jobs/requirements/prod.txt
  jobs/payment-jobs/tasks/ap_routing_slip_refund_task.py
  jobs/payment-jobs/tasks/common/cgi_ap.py
Labels: enhancement

#861 Fixing FAS token response
  jobs/payment-jobs/services/routing_slip.py
  jobs/payment-jobs/tasks/routing_slip_task.py
Labels: skip-changelog

#862 Logging improvements, and small bug fix on the pay admin to populate default value
  jobs/ftp-poller/requirements.txt
  jobs/ftp-poller/tests/jobs/conftest.py
  jobs/ftp-poller/utils/logger.py
  pay-admin/admin/views/distribution_code.py
  pay-admin/requirements.txt
  pay-api/requirements.txt
  pay-api/src/pay_api/factory/payment_system_factory.py
  pay-api/src/pay_api/resources/invoice.py
  pay-api/src/pay_api/services/auth.py
  pay-api/src/pay_api/services/base_payment_system.py
  pay-api/src/pay_api/services/bcol_service.py
  pay-api/src/pay_api/services/cfs_service.py
  pay-api/src/pay_api/services/direct_pay_service.py
  pay-api/src/pay_api/services/ejv_pay_service.py
  pay-api/src/pay_api/services/fee_schedule.py
  pay-api/src/pay_api/services/internal_pay_service.py
  pay-api/src/pay_api/services/online_banking_service.py
  pay-api/src/pay_api/services/pad_service.py
  pay-api/src/pay_api/services/paybc_service.py
  pay-api/src/pay_api/services/payment_account.py
  pay-api/src/pay_api/services/payment_service.py
  pay-api/src/pay_api/services/payment_transaction.py
Labels: skip-changelog

#864 Fixed receipt font display issue.
  report-api/report-templates/payment_receipt.html
Labels: bug

#863 Fix for sending state in CFS Site creation for Non-Canadian addresses
  pay-api/src/pay_api/services/cfs_service.py
Labels: bug

#865 Calculate the account level service fee only if fee schedule got service fee configured.
  jobs/payment-jobs/requirements.txt
  pay-api/src/pay_api/services/fee_schedule.py
Labels: skip-changelog

#867 Fixed the bold font issue.
  report-api/report-templates/payment_receipt.html
Labels: bug

#866 Changes to send different customer profile class for FAS customer profile
  jobs/payment-jobs/requirements.txt
  jobs/payment-jobs/requirements/prod.txt
  jobs/payment-jobs/services/routing_slip.py
  jobs/payment-jobs/tasks/cfs_create_invoice_task.py
  pay-api/src/pay_api/services/cfs_service.py
  pay-api/src/pay_api/utils/constants.py
Labels: skip-changelog

#868 Group cfs lines
  jobs/payment-jobs/requirements.txt
  jobs/payment-jobs/requirements/prod.txt
  pay-api/src/pay_api/services/cfs_service.py
Labels: enhancement

#869 Fixing name length for distribution codes
  jobs/payment-jobs/requirements.txt
  jobs/payment-jobs/requirements/prod.txt
  pay-admin/requirements.txt
  pay-admin/requirements/repo-libraries.txt
  pay-api/migrations/versions/ff2d7fe31ec9_name_length_gl_codes.py
  pay-api/src/pay_api/models/distribution_code.py
Labels: skip-changelog

#860 FAS integration documentation
  docs/docs/architecture/FAS_Intgeration.md
  docs/docs/architecture/fas/cancel_transaction.svg
  docs/docs/architecture/fas/cancel_transaction_partial.svg
  docs/docs/architecture/fas/link.svg
  docs/docs/architecture/fas/nsf.svg
  docs/docs/architecture/fas/refund_approved.svg
  docs/docs/architecture/fas/routing_slip.svg
  docs/docs/architecture/fas/routing_slip_transaction.svg
  docs/docs/architecture/fas/write_off.svg
Labels: documentation

#870 Adding some error handling in place to avoid unwanted errors
  pay-api/src/pay_api/services/direct_pay_service.py
  pay-api/src/pay_api/services/payment_transaction.py
  pay-api/tests/unit/services/test_payment_transaction.py
Labels: skip-changelog

#871 Adding refund status to Invoice schema
  docs/docs/api_contract/pay-api-1.0.0.yaml
Labels: skip-changelog
