Repository bcgov/sbc-pay, pull requests merged in 2022-05, with the labels that each got.

#914 12019 - Fix failing CI workflows
  pay-api/requirements.txt
  queue_services/events-listener/requirements/prod.txt
  queue_services/payment-reconciliations/requirements/prod.txt
  queue_services/payment-reconciliations/tests/conftest.py
  queue_services/payment-reconciliations/tests/docker-compose.yml
Labels: bug

#923 12027 - Add in missing indexes.
  pay-api/migrations/alembic.ini
  pay-api/migrations/versions/f218f09ea2d2_add_missing_indexes_thanks_patrick.py
Labels: bug

#917 11957 - Payment job fixes
  jobs/payment-jobs/tasks/cfs_create_account_task.py
Labels: bug

#924 12047 - Feature/fix internal pay
  pay-api/src/pay_api/services/internal_pay_service.py
  pay-api/tests/unit/services/test_payment_service.py
  pay-api/tests/utilities/base_test.py
Labels: bug

#922 12039 - Move logging to the directory Openshift will pick it up.
  pay-api/src/pay_api/logging.conf
Labels: bug

#925 12032 - Performance search improvements.
  pay-api/README.md
  pay-api/migrations/versions/2ccbd2aad2dc_more_indexes_for_performance.py
  pay-api/src/pay_api/models/routing_slip.py
  pay-api/src/pay_api/services/fas/routing_slip.py
  pay-api/tests/unit/api/fas/test_routing_slip.py
Labels: bug, enhancement

#919 11899 - CSO total and service fee fix
  pay-api/src/pay_api/schemas/schemas/line_item.json
  pay-api/src/pay_api/services/fee_schedule.py
  pay-api/src/pay_api/services/payment_line_item.py
  pay-api/tests/unit/api/test_account.py
  pay-api/tests/utilities/base_test.py
Labels: bug

#926 12032 - FAS - Performance - Query optimization
  pay-api/src/pay_api/models/routing_slip.py
  pay-api/src/pay_api/services/fas/routing_slip.py
  pay-api/tests/unit/models/test_routing_slip.py
Labels: bug

#927 11989 - Migration to fix error message.
  pay-api/migrations/versions/175c11863186_fix_rs_cant_link_nsf_description.py
Labels: bug

#929 Rollback payment_line_item.py changes.
  pay-api/src/pay_api/services/payment_line_item.py
Labels: bug

#930 12104 - Add "variable" to fee code admin
  pay-admin/admin/views/fee_schedule.py
  pay-admin/requirements.txt
  pay-ui/.browserslistrc
  pay-ui/.editorconfig
  pay-ui/.eslintrc.js
  pay-ui/.gitignore
  pay-ui/Jenkinsfile
  pay-ui/Jenkinsfile.pipeline.param
  pay-ui/README.md
  pay-ui/babel.config.js
  pay-ui/dockerfile
  pay-ui/openshift/templates/pay-ui-build.json
  pay-ui/openshift/templates/pay-ui-deploy.json
  pay-ui/openshift/templates/pay-ui-runtime-build.json
  pay-ui/openshift/templates/pay-ui-service.json
  pay-ui/package.json
  pay-ui/postcss.config.js
  pay-ui/public/favicon.ico
  pay-ui/public/img/icons/android-chrome-192x192.png
  pay-ui/public/img/icons/android-chrome-512x512.png
  pay-ui/public/img/icons/apple-touch-icon-120x120.png
  pay-ui/public/img/icons/apple-touch-icon-152x152.png
  pay-ui/public/img/icons/apple-touch-icon-180x180.png
  pay-ui/public/img/icons/apple-touch-icon-60x60.png
  pay-ui/public/img/icons/apple-touch-icon-76x76.png
  pay-ui/public/img/icons/apple-touch-icon.png
  pay-ui/public/img/icons/favicon-16x16.png
  pay-ui/public/img/icons/favicon-32x32.png
  pay-ui/public/img/icons/msapplication-icon-144x144.png
  pay-ui/public/img/icons/mstile-150x150.png
  pay-ui/public/img/icons/safari-pinned-tab.svg
  pay-ui/public/index.html
  pay-ui/public/manifest.json
  pay-ui/public/robots.txt
  pay-ui/src/App.vue
  pay-ui/src/assets/images/gov3_bc_logo.png
  pay-ui/src/assets/vue-logo.png
  pay-ui/src/components/HelloWorld.vue
  pay-ui/src/components/StdHeader.vue
  pay-ui/src/main.ts
  pay-ui/src/plugins/vuetify.ts
  pay-ui/src/registerServiceWorker.ts
  pay-ui/src/router.ts
  pay-ui/src/shims-tsx.d.ts
  pay-ui/src/shims-vue.d.ts
  pay-ui/src/store.ts
  pay-ui/src/views/About.vue
  pay-ui/src/views/Home.vue
  pay-ui/tests/e2e/custom-assertions/elementCount.js
  pay-ui/tests/e2e/specs/test.js
  pay-ui/tests/unit/.eslintrc.js
  pay-ui/tests/unit/example.spec.ts
  pay-ui/tsconfig.json
Labels: enhancement

#931 12050/12047 - FAS - Incorrectly saying balance is less than transaction amount
  pay-api/src/pay_api/services/fee_schedule.py
  pay-api/src/pay_api/services/internal_pay_service.py
  pay-api/src/pay_api/utils/util.py
  pay-api/tests/unit/api/test_fee.py
Labels: bug

#928 Update README.md
  README.md
Labels: documentation

#933 12060 - Update any fonts in routing_slip_report.html to at least 13px.
  report-api/report-templates/routing_slip_report.html
  report-api/requirements.txt
  report-api/requirements/prod.txt
Labels: enhancement

#934 12203 - Add new codes for BC Assessment.
  pay-api/migrations/versions/e3644698c172_.py
  pay-api/migrations/versions/e748b5c19247_.py
  pay-api/requirements.txt
  pay-api/src/pay_api/models/invoice.py
  pay-api/src/pay_api/models/payment.py
  pay-api/src/pay_api/models/payment_line_item.py
  pay-api/src/pay_api/models/receipt.py
  pay-api/src/pay_api/models/routing_slip.py
Labels: enhancement

#935 Migration Error - Fix data being null
  pay-api/migrations/versions/e3644698c172_.py
Labels: bug

#936 11527 - Receipt updates needed for SP/GP Registration
  pay-api/src/pay_api/models/invoice.py
  pay-api/src/pay_api/utils/constants.py
  report-api/report-templates/payment_receipt.html
Labels: bug

#937 Create CODEOWNERS
  .github/CODEOWNERS
Labels: maintenance

#938 11924 - Small fix for folioNumber, it's reading from the token but can be blank.
  pay-api/src/pay_api/services/payment_service.py
  pay-api/tests/unit/api/test_payment_request.py
Labels: bug

#939 11924 - API - Status ENUM not following spec
  pay-api/src/pay_api/services/payment.py
  pay-api/tests/unit/services/test_payment.py
Labels: bug

#940 11924 - Remove status_code_description, it's only used internally.
  pay-api/src/pay_api/services/payment.py
  pay-api/tests/unit/services/test_payment.py
Labels: bug

#941 12316 - Add missing if condition for invoice_reference.
  pay-api/src/pay_api/services/payment_service.py
Labels: bug
