Repository bcgov/sbc-pay, pull requests merged in 2022-02, with the labels that each got.

#872 Sending correct key for BCOL refund email
  pay-api/docker-entrypoint.sh
  pay-api/src/pay_api/services/bcol_service.py
Labels: skip-changelog

#874 Adding gunicorn config to docker entry point
  pay-api/docker-entrypoint.sh
  pay-api/gunicorn_config.py
Labels: skip-changelog

#876 Removing gunicorn_config from the start script as it needs gevent dep…
  pay-api/docker-entrypoint.sh
Labels: skip-changelog

#878 Fixing reconciliation where the account got updated from PAD to DRAWDOWN after transactions are done
  jobs/payment-jobs/tasks/cfs_create_invoice_task.py
  queue_services/payment-reconciliations/devops/vaults.json
Labels: skip-changelog

#873 10507 - Add new columns in Routing slip, payment to store payment in USD
  pay-api/migrations/versions/d73cbcdd2f25_add_new_column_total_usd_for_routing_.py
  pay-api/src/pay_api/models/payment.py
  pay-api/src/pay_api/models/routing_slip.py
  pay-api/src/pay_api/services/fas/routing_slip.py
  pay-api/src/pay_api/services/payment.py
  pay-api/tests/unit/models/test_payment.py
  pay-api/tests/unit/models/test_routing_slip.py
  pay-api/tests/unit/services/test_payment.py
  pay-api/tests/unit/services/test_routing_slip_service.py
  pay-api/tests/utilities/base_test.py
Labels: enhancement

#882 Avoid duplicate entries and fix false alarm on reconciliations
  queue_services/payment-reconciliations/requirements.txt
  queue_services/payment-reconciliations/src/reconciliations/payment_reconciliations.py
Labels: skip-changelog

#883 Skipping failed payment process if already exists to avoid duplicate …
  queue_services/payment-reconciliations/src/reconciliations/payment_reconciliations.py
Labels: skip-changelog

#881 10507 - Total USD update for daily report generation Routing slips
  pay-api/src/pay_api/services/fas/routing_slip.py
Labels: enhancement

#884 FAS - Additional Role Permissions
  pay-api/src/pay_api/services/fas/routing_slip.py
  pay-api/src/pay_api/services/fas/routing_slip_status_transition_service.py
  pay-api/tests/unit/api/fas/test_refund.py
  pay-api/tests/unit/api/fas/test_routing_slip.py
Labels: enhancement

#880 Report API CD update.
  .github/workflows/report-api-cd.yml
  report-api/devops/values.dev.yaml
  report-api/devops/values.prod.yaml
  report-api/devops/values.test.yaml
  report-api/gunicorn_config.py
Labels: devops

#885 Feature/10507 report issue
  report-api/report-templates/routing_slip_report.html
Labels: enhancement

#886 Feature/10507 report null-type fix
  pay-api/src/pay_api/services/fas/routing_slip.py
Labels: enhancement

#887 list removal issue fixed
  pay-api/src/pay_api/services/fas/routing_slip_status_transition_service.py
Labels: skip-changelog

#888 10507 - Daily RS report fix for total USD amount display
  pay-api/src/pay_api/services/fas/routing_slip.py
Labels: bug

#892 bank account name changed to org name
  jobs/payment-jobs/tasks/cfs_bank_name_updater.py
  jobs/payment-jobs/tasks/cfs_create_account_task.py
  pay-api/src/pay_api/services/cfs_service.py
Labels: enhancement

#894 kc version made sticky
  bcol-api/requirements.txt
  bcol-api/requirements/prod.txt
  bcol-api/tests/docker/docker-compose.yml
  jobs/payment-jobs/requirements.txt
  jobs/payment-jobs/requirements/prod.txt
  jobs/payment-jobs/tests/docker/docker-compose.yml
  pay-api/requirements.txt
  pay-api/requirements/prod.txt
  pay-api/tests/docker/docker-compose.yml
  report-api/requirements.txt
  report-api/requirements/prod.txt
  report-api/tests/docker/docker-compose.yml
Labels: devops

#895 Feature/11184
  pay-api/src/pay_api/services/fas/routing_slip_status_transition_service.py
  pay-api/tests/unit/api/fas/test_routing_slip.py
Labels: enhancement

#893 Bank account name updater job added
  jobs/payment-jobs/tasks/cfs_bank_name_updater.py
  jobs/payment-jobs/tasks/cfs_create_account_task.py
  pay-api/src/pay_api/services/cfs_service.py
Labels: enhancement

#896 fixing dependency
  jobs/payment-jobs/requirements.txt
Labels: skip-changelog

#889 Padding fix ap line comment
  jobs/payment-jobs/tasks/ap_routing_slip_refund_task.py
Labels: bug

#897 fixing dependency
  queue_services/events-listener/requirements.txt
  queue_services/events-listener/requirements/prod.txt
Labels: skip-changelog

#898 11192 - FAS Routing slip creation validation
  pay-api/src/pay_api/schemas/schemas/routing_slip.json
  pay-api/src/pay_api/services/fas/routing_slip.py
  pay-api/tests/unit/api/fas/test_routing_slip.py
  pay-api/tests/unit/api/test_payment_request.py
Labels: enhancement
