Repository bcgov/sbc-pay, pull requests merged in 2022-11, with the labels that each got.

#1006 14137 - Update API spec to include SETTLEMENT_SCHED
  docs/docs/api_contract/pay-api-1.0.2.yaml
  jobs/payment-jobs/tests/docker/docker-compose.yml
  pay-api/tests/docker/docker-compose.yml
Labels: documentation

#1008 14092 - Use decimals for Invoices / Payment Line Items / Payment Accounts / Fees - Part 2
  jobs/payment-jobs/requirements.txt
  jobs/payment-jobs/requirements/prod.txt
  jobs/payment-jobs/tasks/cfs_create_invoice_task.py
  jobs/payment-jobs/tasks/routing_slip_task.py
  jobs/payment-jobs/utils/mailer.py
  pay-api/migrations/versions/1e62e1c27b08_move_fee_codes_to_numeric.py
  pay-api/src/pay_api/models/fee_code.py
  pay-api/src/pay_api/services/fee_schedule.py
  pay-api/src/pay_api/services/payment_service.py
Labels: bug

#1010 Job fixes, unit test fixes.
  .gitignore
  jobs/payment-jobs/tasks/cfs_create_invoice_task.py
  jobs/payment-jobs/tasks/unpaid_invoice_notify_task.py
  pay-api/src/pay_api/services/paybc_service.py
  pay-api/src/pay_api/services/payment_account.py
  pay-api/tests/unit/services/test_paybc_service.py
  pay-api/tests/unit/services/test_statement_recipients.py
  pay-api/tests/unit/services/test_statement_settings.py
Labels: bug

#1013 More reconciliation fixes for spaces, turns out it can be larger than 2.
  queue_services/payment-reconciliations/src/reconciliations/cgi_reconciliations.py
  queue_services/payment-reconciliations/tests/integration/test_cgi_reconciliations.py
Labels: bug

#1015 14180 - Reverse CSO specific changes for service_fees.
  pay-api/src/pay_api/services/fee_schedule.py
Labels: bug, DoNotMerge

#1014 14086 PAY-JOBS - Issue with invoice reference already exists - Routing Slips
  jobs/payment-jobs/tasks/cfs_create_invoice_task.py
  jobs/payment-jobs/tests/jobs/mocks.py
  jobs/payment-jobs/tests/jobs/test_cfs_create_invoice_task.py
Labels: bug

#1019 Revert "14180 - Reverse CSO specific changes for service_fees."
  pay-api/src/pay_api/services/fee_schedule.py
Labels: bug

#1020 Version update.
  pay-api/src/pay_api/version.py
Labels: maintenance

#1021 Revert "Revert "14180 - Reverse CSO specific changes for service_fees.""
  pay-api/src/pay_api/services/fee_schedule.py
Labels: maintenance

#1016 14316 - Override staff bcol code for CSO fee.
  .github/CODEOWNERS
  pay-api/Makefile
  pay-api/src/pay_api/services/bcol_service.py
  pay-api/src/pay_api/version.py
Labels: bug

#1022 14384 - Fix for routing_slip_task.py
  jobs/payment-jobs/requirements.txt
  jobs/payment-jobs/requirements/prod.txt
  jobs/payment-jobs/tasks/cfs_create_invoice_task.py
  jobs/payment-jobs/tasks/routing_slip_task.py
  jobs/payment-jobs/tests/jobs/mocks.py
  jobs/payment-jobs/tests/jobs/test_cfs_create_invoice_task.py
  pay-api/src/pay_api/services/cfs_service.py
  pay-api/src/pay_api/services/paybc_service.py
  pay-api/src/pay_api/services/payment.py
  pay-api/tests/unit/services/test_payment_service.py
Labels: bug

#1024 Fix requirements.txt
  jobs/payment-jobs/requirements.txt
  jobs/payment-jobs/requirements/prod.txt
Labels: maintenance

#1025 14435 - Minor change to PAD job that should fix cfs_account_id being blank. T…
  jobs/payment-jobs/requirements/dev.txt
  jobs/payment-jobs/tasks/cfs_create_invoice_task.py
  pay-api/requirements/dev.txt
Labels: bug

#1026 speed up partner distribution task
  jobs/payment-jobs/tasks/ejv_partner_distribution_task.py
Labels: bug
