Repository bcgov/sbc-pay, pull requests merged in 2023-02, with the labels that each got.

#1084 Add try except for create_cfs_account. That way if it fails it doesn'…
  jobs/payment-jobs/tasks/cfs_create_account_task.py
  pay-api/src/pay_api/version.py
Labels: bug

#1085 enhancements added to transactions history
  pay-api/src/pay_api/models/payment.py
  pay-api/src/pay_api/resources/account.py
  pay-api/src/pay_api/services/auth.py
  pay-api/src/pay_api/services/payment.py
  pay-api/src/pay_api/utils/enums.py
  pay-api/tests/unit/api/test_account.py
  pay-api/tests/unit/services/test_payment.py
  pay-api/tests/utilities/base_test.py
Labels: enhancement

#1086 Fix null details.
  pay-api/src/pay_api/services/payment_service.py
Labels: bug

#1088 Add transistion to complete.
  pay-api/src/pay_api/services/fas/routing_slip_status_transition_service.py
Labels: bug

#1091 Fix rs correction api
  pay-api/src/pay_api/services/fas/routing_slip.py
  pay-api/tests/unit/api/fas/test_routing_slip.py
Labels: bug

#1092 Enable the AP refund reconciliation always.
  queue_services/payment-reconciliations/src/reconciliations/cgi_reconciliations.py
  queue_services/payment-reconciliations/src/reconciliations/config.py
Labels: bug

#1097 15276 - Add in SQL to load in test data for pay.
  pay-db/test-data-load/test-data-cleanup.sql
  pay-db/test-data-load/test-data-load.sql
Labels: documentation

#1096 added indexes on invoice ref table
  pay-api/migrations/README
  pay-api/migrations/README.md
  pay-api/migrations/alembic.ini
  pay-api/migrations/versions/2023_02_08_inv_ref_indexes.py
  pay-api/src/pay_api/models/invoice_reference.py
Labels: bug

#1098 15290 - Search optimizations.
  pay-api/src/pay_api/models/payment.py
  pay-api/src/pay_api/services/payment.py
  pay-api/src/pay_api/utils/errors.py
Labels: bug

#1100 Sorting fix + pad activation date fix.
  jobs/payment-jobs/tasks/activate_pad_account_task.py
  pay-api/src/pay_api/models/payment.py
Labels: bug

#1104 bcol refund fix float/decimal conversion
  jobs/payment-jobs/tasks/bcol_refund_confirmation_task.py
Labels: bug

#1116 add in additionalProperties for Invoice object.
  docs/docs/api_contract/pay-api-1.0.3.yaml
Labels: bug

#1103 14850 - allow basic accounts access to transaction route
  pay-api/src/pay_api/resources/account.py
Labels: enhancement

#1117 14850 - Unit test for basic account - transaction screen
  pay-api/tests/unit/api/test_account.py
Labels: bug

#1119 Fix for bcol logging.
  pay-api/src/pay_api/services/bcol_service.py
Labels: bug

#1118 Use decimal instead of float.
  queue_services/payment-reconciliations/src/reconciliations/payment_reconciliations.py
Labels: bug

#1120 Update enums.py
  pay-api/src/pay_api/utils/enums.py
Labels: enhancement

#1123 To fix all notebook reports Sent but not delivered Issue#2247
  jobs/notebook-report/notebookreport.py
Labels: bug

#1125 Fix for BCOL + missing fields.
  pay-api/src/pay_api/models/payment.py
  pay-api/src/pay_api/services/bcol_service.py
  pay-api/src/pay_api/services/payment.py
Labels: bug

#1122 14847 - AP non-gov disbursement for BCA.
  jobs/payment-jobs/config.py
  jobs/payment-jobs/invoke_jobs.py
  jobs/payment-jobs/requirements.txt
  jobs/payment-jobs/requirements/prod.txt
  jobs/payment-jobs/run_ap_routing_slip_refund_task.sh
  jobs/payment-jobs/run_ap_task.sh
  jobs/payment-jobs/tasks/ap_routing_slip_refund_task.py
  jobs/payment-jobs/tasks/ap_task.py
  jobs/payment-jobs/tasks/common/cgi_ap.py
  jobs/payment-jobs/tasks/common/dataclasses.py
  jobs/payment-jobs/tasks/ejv_partner_distribution_task.py
  jobs/payment-jobs/tests/jobs/factory.py
  jobs/payment-jobs/tests/jobs/test_ap_task.py
  pay-api/src/pay_api/services/bcol_service.py
  queue_services/payment-reconciliations/Makefile
  queue_services/payment-reconciliations/requirements.txt
  queue_services/payment-reconciliations/requirements/bcregistry-libraries.txt
  queue_services/payment-reconciliations/src/reconciliations/cgi_reconciliations.py
  queue_services/payment-reconciliations/tests/integration/__init__.py
  queue_services/payment-reconciliations/tests/integration/factory.py
  queue_services/payment-reconciliations/tests/integration/test_cgi_reconciliations.py
Labels: enhancement

#1128 Remove time check in task, just do this via CRONTAB instead.
  jobs/payment-jobs/tasks/direct_pay_automated_refund_task.py
  jobs/payment-jobs/tests/jobs/test_direct_pay_automated_refund_task.py
Labels: enhancement

#1115 15257 - Fix statements serialization issue
  pay-api/docker-entrypoint.sh
  pay-api/gunicorn_config.py
  pay-api/migrations/versions/b6e28faea978_rename_tables_to_plurals.py
  pay-api/requirements.txt
  pay-api/requirements/prod.txt
  pay-api/src/pay_api/models/__init__.py
  pay-api/src/pay_api/models/invoice.py
  pay-api/src/pay_api/models/payment.py
  pay-api/src/pay_api/models/payment_account.py
  pay-api/src/pay_api/models/payment_line_item.py
  pay-api/src/pay_api/resources/account.py
  pay-api/src/pay_api/services/payment.py
  pay-api/src/pay_api/utils/converter.py
  pay-api/tests/unit/api/test_account.py
  pay-api/tests/utilities/base_test.py
  pay-db/test-data-load/test-data-load.sql
Labels: bug

#1129 Change auth_account_id to accountId..
  pay-api/src/pay_api/models/payment_account.py
Labels: bug
