Repository bcgov/sbc-pay, pull requests merged in 2023-01, with the labels that each got.

#1063 14618 - PAY-API changes for routing slip corrections - Part 1
  pay-api/migrations/versions/fd5c02bb9e01_.py
  pay-api/src/pay_api/models/payment.py
  pay-api/src/pay_api/models/routing_slip.py
  pay-api/src/pay_api/services/fas/routing_slip.py
  pay-api/tests/unit/api/fas/test_routing_slip.py
Labels: enhancement

#1065 12777 - System Exit 1 / Performance fixes for Invoice searching, also statement building
  pay-api/migrations/versions/39c2491d0a07_migration_for_business_details.py
  pay-api/src/pay_api/models/invoice.py
  pay-api/src/pay_api/models/payment.py
  pay-api/src/pay_api/services/payment.py
  pay-api/src/pay_api/utils/constants.py
  pay-api/src/pay_api/version.py
Labels: bug

#1066 14618 - add CORRECTION.value to RoutingSlipStatus
  pay-api/src/pay_api/services/fas/routing_slip_status_transition_service.py
Labels: bug

#1067 Skip over sending queue message for CSO payments.
  pay-api/src/pay_api/services/base_payment_system.py
  pay-api/src/pay_api/utils/enums.py
Labels: bug

#1068 Skip over certain corp types for queue messages.
  pay-api/src/pay_api/services/base_payment_system.py
  pay-api/src/pay_api/services/payment_transaction.py
  pay-api/src/pay_api/utils/enums.py
Labels: bug

#1069 Create job to schedule reports - invoice reconciliation #14945
  .github/workflows/notebook-report-cd.yml
  .github/workflows/notebook-report-ci.yml
  jobs/notebook-report/Makefile
  jobs/notebook-report/README.md
  jobs/notebook-report/config.py
  jobs/notebook-report/daily/reconciliation_details.ipynb
  jobs/notebook-report/devops/vaults.json
  jobs/notebook-report/jenkins/dev.groovy
  jobs/notebook-report/jenkins/prod.groovy
  jobs/notebook-report/jenkins/test.groovy
  jobs/notebook-report/monthly/reconciliation_summary.ipynb
  jobs/notebook-report/notebookreport.py
  jobs/notebook-report/openshift/templates/cronjob.yaml
  jobs/notebook-report/requirements.txt
  jobs/notebook-report/requirements/dev.txt
  jobs/notebook-report/requirements/prod.txt
  jobs/notebook-report/tests/unit/__init__.py
  jobs/notebook-report/tests/unit/conftest.py
  jobs/notebook-report/tests/unit/test_job.py
  jobs/notebook-report/util/logging.py
  jobs/notebook-report/weekly/pay.ipynb
Labels: enhancement, devops

#1078 Create job to schedule reports - invoice reconciliation #14945
  jobs/notebook-report/notebookreport.py
  jobs/notebook-report/setup.cfg
Labels: enhancement

#1079 Create job to schedule reports - invoice reconciliation #14945
  .github/workflows/notebook-report-cd.yml
Labels: enhancement

#1071 backend updates for transaction table
  pay-api/src/pay_api/models/payment.py
  pay-api/src/pay_api/schemas/schemas/purchase_history_request.json
  pay-api/src/pay_api/version.py
  pay-api/tests/unit/services/test_payment.py
  pay-api/tests/utilities/base_test.py
Labels: enhancement

#1077 14618 - Fix from feedback, casting float to Decimal.
  pay-api/src/pay_api/services/fas/routing_slip.py
Labels: bug

#1080 Missing str for decimal
  pay-api/src/pay_api/services/fas/routing_slip.py
Labels: bug

#1081 Adding in pylint to requirements.txt, renaming the CI name.
  .github/workflows/notebook-report-ci.yml
  .github/workflows/pr-label-check.yml
  jobs/notebook-report/requirements.txt
Labels: devops

#1082 14618 - Routing Slip job changes for Corrections
  jobs/payment-jobs/invoke_jobs.py
  jobs/payment-jobs/requirements.txt
  jobs/payment-jobs/tasks/routing_slip_task.py
  jobs/payment-jobs/tests/jobs/test_routing_slip_task.py
  pay-api/src/pay_api/services/fas/routing_slip.py
  pay-api/src/pay_api/services/fas/routing_slip_status_transition_service.py
  pay-api/src/pay_api/services/internal_pay_service.py
Labels: enhancement

#1083 15161 - Add in change for invoice.disbursment_date
  pay-api/migrations/versions/286acad5d366_.py
  pay-api/src/pay_api/models/invoice.py
  queue_services/payment-reconciliations/src/reconciliations/cgi_reconciliations.py
Labels: enhancement
