Repository bcgov/sbc-pay, pull requests merged in 2023-03, with the labels that each got.

#1131 15467 - Statement performance optimizations, also weekly / monthly weren't wo…
  jobs/payment-jobs/requirements.txt
  jobs/payment-jobs/tasks/statement_task.py
  pay-api/src/pay_api/models/payment.py
  pay-api/src/pay_api/utils/util.py
Labels: enhancement

#1124 15387 - invoices table enhancement
  jobs/payment-jobs/tasks/bcol_refund_confirmation_task.py
  jobs/payment-jobs/tasks/cfs_create_invoice_task.py
  jobs/payment-jobs/tasks/direct_pay_automated_refund_task.py
  jobs/payment-jobs/tasks/distribution_task.py
  jobs/payment-jobs/tasks/routing_slip_task.py
  jobs/payment-jobs/tests/jobs/factory.py
  jobs/payment-jobs/tests/jobs/test_direct_pay_automated_refund_task.py
  jobs/payment-jobs/tests/jobs/test_distribution_task.py
  jobs/payment-jobs/tests/jobs/test_ejv_partner_distribution_task.py
  pay-api/migrations/versions/2023_02_23_0a3ad7c041f6_add_refund_date_to_invoices.py
  pay-api/migrations/versions/2023_02_23_d2d9864164d1_update_refund_payment_date_to_invoices.py
  pay-api/src/pay_api/models/invoice.py
  pay-api/src/pay_api/models/payment.py
  pay-api/src/pay_api/services/base_payment_system.py
  pay-api/src/pay_api/services/invoice.py
  pay-api/src/pay_api/services/payment_transaction.py
  pay-api/tests/unit/api/test_refund.py
  pay-api/tests/unit/services/test_direct_pay_service.py
  pay-api/tests/unit/services/test_refund.py
  queue_services/payment-reconciliations/src/reconciliations/cgi_reconciliations.py
  queue_services/payment-reconciliations/src/reconciliations/payment_reconciliations.py
Labels: enhancement

#1132 15467 - Revert requirements.txt.
  jobs/payment-jobs/requirements.txt
  jobs/payment-jobs/tasks/statement_task.py
Labels: maintenance

#1133 AP disbursement changes + statement tweak.
  jobs/payment-jobs/requirements.txt
  jobs/payment-jobs/tasks/ap_task.py
  jobs/payment-jobs/tasks/common/cgi_ap.py
  jobs/payment-jobs/tasks/common/dataclasses.py
  jobs/payment-jobs/tasks/statement_task.py
  pay-api/src/pay_api/utils/util.py
Labels: bug

#1134 15257- Fix for exception not coming back correctly.
  jobs/payment-jobs/requirements.txt
  pay-api/src/pay_api/resources/account.py
Labels: bug

#1135 15467 - Statement enhancements, remove duplicates - fix the sort order in pay as well.
  jobs/payment-jobs/requirements.txt
  jobs/payment-jobs/tasks/statement_task.py
  jobs/payment-jobs/tests/jobs/test_generate_statements.py
  pay-api/src/pay_api/models/statement.py
  pay-api/src/pay_api/version.py
Labels: bug, enhancement

#1139 Add in db.session.flush()
  jobs/payment-jobs/tasks/statement_task.py
Labels: bug

#1140 15197 - Models _mapping for service backwards compatibility
  pay-api/src/pay_api/models/account_fee.py
  pay-api/src/pay_api/models/cas_settlement.py
  pay-api/src/pay_api/models/cfs_account.py
  pay-api/src/pay_api/models/cfs_account_status_code.py
  pay-api/src/pay_api/models/comment.py
  pay-api/src/pay_api/models/corp_type.py
  pay-api/src/pay_api/models/credit.py
  pay-api/src/pay_api/models/disbursement_status_code.py
  pay-api/src/pay_api/models/distribution_code.py
  pay-api/src/pay_api/models/ejv_file.py
  pay-api/src/pay_api/models/ejv_header.py
  pay-api/src/pay_api/models/ejv_invoice_link.py
  pay-api/src/pay_api/models/error_code.py
  pay-api/src/pay_api/models/fee_code.py
  pay-api/src/pay_api/models/fee_schedule.py
  pay-api/src/pay_api/models/filing_type.py
  pay-api/src/pay_api/models/invoice.py
  pay-api/src/pay_api/models/invoice_batch.py
  pay-api/src/pay_api/models/invoice_batch_link.py
  pay-api/src/pay_api/models/invoice_reference.py
  pay-api/src/pay_api/models/invoice_reference_status_code.py
  pay-api/src/pay_api/models/invoice_status_code.py
  pay-api/src/pay_api/models/line_item_status_code.py
  pay-api/src/pay_api/models/notification_status_code.py
  pay-api/src/pay_api/models/payment.py
  pay-api/src/pay_api/models/payment_account.py
  pay-api/src/pay_api/models/payment_line_item.py
  pay-api/src/pay_api/models/payment_method.py
  pay-api/src/pay_api/models/payment_status_code.py
  pay-api/src/pay_api/models/payment_system.py
  pay-api/src/pay_api/models/payment_transaction.py
  pay-api/src/pay_api/models/receipt.py
  pay-api/src/pay_api/models/refund.py
  pay-api/src/pay_api/models/routing_slip.py
  pay-api/src/pay_api/models/routing_slip_status_code.py
  pay-api/src/pay_api/models/statement.py
  pay-api/src/pay_api/models/statement_invoices.py
  pay-api/src/pay_api/models/statement_recipients.py
  pay-api/src/pay_api/models/statement_settings.py
  pay-api/src/pay_api/models/transaction_status_code.py
Labels: enhancement

#1141 Add in line to print out invoice id.
  queue_services/payment-reconciliations/src/reconciliations/cgi_reconciliations.py
Labels: enhancement

#1138 Adding in developer notes
  DEVELOPER_NOTES.md
Labels: documentation

#1142 Small fix for payment reconciliation for online banking.
  queue_services/payment-reconciliations/src/reconciliations/payment_reconciliations.py
Labels: bug

#1143 Add in data for no fee, add in details field for credits, update developer notes.
  DEVELOPER_NOTES.md
  pay-api/migrations/versions/2023_03_07_f4a1388844ed_.py
  pay-api/src/pay_api/models/credit.py
  pay-api/src/pay_api/version.py
Labels: enhancement

#1145 Performance tweak statements
  jobs/payment-jobs/tasks/statement_task.py
Labels: bug

#1151 15699 - Changes to accomodate 3 tiers of service fees in BCOL.
  bcol-api/src/bcol_api/resources/bcol_payment.py
  bcol-api/src/bcol_api/services/bcol_payment.py
  bcol-api/tests/conftest.py
  bcol-api/tests/unit/services/test_bcol_payment.py
  pay-api/migrations/versions/2023_03_21_33bbd4d9a85c_.py
  pay-api/src/pay_api/models/corp_type.py
  pay-api/src/pay_api/models/fee_schedule.py
  pay-api/src/pay_api/services/bcol_service.py
  pay-api/tests/unit/services/test_bcol_service.py
Labels: bug

#1152 Cast to float
  bcol-api/src/bcol_api/services/bcol_payment.py
  bcol-api/tests/unit/api/test_bcol_payment.py
Labels: bug

#1153 New columns for pay-admin.
  pay-admin/admin/views/corp_type.py
Labels: bug

#1154 PAY-JOBS - Use the latest version of pay-api.
  jobs/payment-jobs/requirements.txt
Labels: bug

#1155 15719 - Skip EJV Disbursement / Payment on holidays
  jobs/payment-jobs/logging.conf
  jobs/payment-jobs/requirements.txt
  jobs/payment-jobs/requirements/prod.txt
  jobs/payment-jobs/tasks/ejv_partner_distribution_task.py
  jobs/payment-jobs/tasks/ejv_payment_task.py
  jobs/payment-jobs/tests/jobs/conftest.py
  jobs/payment-jobs/tests/jobs/test_ejv_payment_task.py
  jobs/payment-jobs/utils/date.py
  jobs/payment-jobs/utils/logger.py
  pay-api/src/pay_api/services/fee_schedule.py
  queue_services/payment-reconciliations/requirements.txt
Labels: bug
