Repository bcgov/sbc-pay, pull requests merged in 2023-05, with the labels that each got.

#1175 16458 - cast service_fee
  pay-api/src/pay_api/services/bcol_service.py
Labels: bug

#1185 partial of the new queue service
  pay-api/requirements.txt
  pay-api/requirements/prod.txt
  pay-api/requirements/repo-libraries.txt
  pay-api/setup.cfg
  pay-api/src/pay_api/config.py
  pay-api/src/pay_api/services/gcp_queue_publisher.py
  pay-api/src/pay_api/services/payment_transaction.py
Labels: maintenance

#1193 adding the vault for gcp-queue
  pay-api/devops/vaults.json
Labels: enhancement
